### ISSUE TITLE
Add optional support for TypeScript

### ISSUE THREAD

**Issue by marvinhagemeister** [developit/preact-cli#10]
The webpack config already lists `.ts` and `.tsx` as resolvable extensions, but it seems like the loader for ts is missing.

**Comment by lukeed** [comment]
I think the `npm-install-loader` would be a good fit for this [here](https://github.com/developit/preact-cli/blob/master/src/lib/webpack-config.js#L135)! This would conditionally install a TypeScript loader & apply settings for it if-and-only-if CLI detects `.ts` files.

**Comment by marvinhagemeister** [comment]
@lukeed Already at it :)

**Comment by KatSick** [comment]
Great! I can help you if you need some @marvinhagemeister

**Comment by wub** [comment]
In the meantime, you can drop in [this plugin](https://github.com/wub/preact-cli-plugin-typescript)

**Comment by marvinhagemeister** [comment]
@wub That's awesome! I guess this can be closed now.
