### ISSUE TITLE
Can not run demo app Error: ENOENT: no such file or directory, open '~/my-great-app/schema/loader.json'

### ISSUE THREAD

**Issue by vijayrawatsan** [developit/preact-cli#100]
Can not run demo app
### once and you're good: 
npm i -g preact-cli
==> works

### create a new project: 
preact create my-great-app
cd my-great-app
==> works

### start a live-reload/HMR dev server: 
npm start
 ==> fails with:
Error: ENOENT: no such file or directory, open '~/my-great-app/schema/loader.json'

I have node 8.0.0, npm 5.0.0.
macOS Sierra 10.12.3

**Comment by developit** [comment]
I wonder if this is to do with npm@5 or node@8?  I've not had a chance to test `preact-cli` in either.

**Comment by lukeed** [comment]
From the other issue, it seems that `npm cache clean && npm i` might solve this.

**Comment by developit** [comment]
Yup, this is just something you have to do when upgrading to npm 5.
