### ISSUE TITLE
Error: ENOENT: no such file or directory, schema/loader.json'

### ISSUE THREAD

**Issue by AvraamMavridis** [developit/preact-cli#105]
When I run `npm run build` I am getting `Error: ENOENT` for a loader file.

`Error: ENOENT: no such file or directory, open '/Users/avraammavridis/Documents/newsaggregator/frontend/schema/loader.json'`

This started happening suddenly. Even installing again preact-cli didnt help. Any idea?

**Comment by lukeed** [comment]
Duplicate of #100 it seems. Don't think anyone has had a chance to dive into this yet.

**Comment by AvraamMavridis** [comment]
Cleaning the npm cache and re-installing node modules solves the issue.

`npm cache clean`
`npm i`

**Comment by developit** [comment]
Ah - had you just updated node or npm, by chance?

**Comment by AvraamMavridis** [comment]
I updated npm to 5, and then back to 4.6 but I cant remember with which I made then `npm i`

**Comment by developit** [comment]
Ah yeah - if you ran the install under npm 5 and then downgraded that would produce a botched node_modules. Cheers!
