### ISSUE TITLE
Create project in current directory

### ISSUE THREAD

**Issue by jrock2004** [developit/preact-cli#110]
So I want to upgrade my current git project with preact. This app is just html and JS. So how can I create a new project in the current directory instead of creating a new folder? Thanks

I tried this:

`preact create lcac --type root --dest . `

**Comment by framp** [comment]
It will say the directory already exists. 

I don't think we have an option to bypass that right now (maybe a generic `--force -f`? ) but this works:
```
preact create lcac -type root && move lcac/* . && rm -rf lcac
```

**Comment by developit** [comment]
Ah, took me a second to realize what the issue was there - you're right @framp. A --force option sounds good.
