### ISSUE TITLE
Firebase Authentication Redirect Not Working Due To Service Worker

### ISSUE THREAD

**Issue by Kiricon** [developit/preact-cli#114]
I'm having the problem as described in [this](https://github.com/Polymer/polymer-cli/issues/290) issue. 

TDLR;
The auto generated service worker won't allow hosted firebase applications to redirect when the `/__/auth/` url path is hit. This path is essential for firebase authentication. 

I recommend providing a service worker prebuild file or excluding the `/__/` path from falling back to the index page.

**Comment by reznord** [comment]
we need to add `navigateFallbackWhitelist`, [here](https://github.com/developit/preact-cli/blob/master/src/lib/webpack-config.js#L444) so it takes care of the `/__/auth/` as well.

@developit @lukeed @rkostrzewski any thoughts?

**Comment by reznord** [comment]
Adding this `navigateFallbackWhitelist: [/^(?!\/__).*/],` after `navigateFallback` in [here](https://github.com/developit/preact-cli/blob/master/src/lib/webpack-config.js#L444) will do the work.

Will make a PR if this is good to go

**Comment by rkostrzewski** [comment]
@reznord sounds good to me.
