### ISSUE TITLE
[v1.1.1] Favicon

### ISSUE THREAD

**Issue by omarchehab98** [developit/preact-cli#115]
# Reproduce

```
preact create my-great-app
cd my-great-app
```

Replace preact favicon in `src/assets/favicon.ico` with custom `favicon.ico` 

```
npm run build
```
# Actual

`build/index.html`
```html
<link rel="shortcut icon" href="/favicon.ico">
```

`build/favicon.ico` is the preact logo

`build/assets/favicon.ico` is my custom favicon

# Expected

`build/index.html`
```html
<link rel="shortcut icon" href="/favicon.ico">
```

`build/favicon.ico` is my custom favicon

# Blame

[883c08 src/lib/webpack-config.js#L452](https://github.com/developit/preact-cli/blob/883c0822e9b7793585fe93c0b003477d037269c0/src/lib/webpack-config.js#L452)

**Comment by developit** [comment]
Hmm - related: https://github.com/developit/preact-cli/blob/883c0822e9b7793585fe93c0b003477d037269c0/src/lib/webpack-config.js#L283-L286
