### ISSUE TITLE
alias to the src folder

### ISSUE THREAD

**Issue by AvraamMavridis** [developit/preact-cli#118]
That is a suggestion.

What about adding an alias to the webpack config that will point to the src folder to avoid the `../..` relative paths. Something like:

```
      alias: {
        app: path.resolve(__dirname, '../src/'),
     }
```

So instead of having 
```
import Profile from '../routes/profile';
```

Will have

```
import Profile from 'app/routes/profile';
```

If you think is a good idea, I can submit a small PR for it.

**Comment by developit** [comment]
I'd love to have this, as long as we call it `src` so it's 1:1.

```js
      alias: {
        src: path.resolve(__dirname, '../src/'),
     }
```

It's particularly useful in tests.

**Comment by AvraamMavridis** [comment]
@developit Cool! I make a PR if thats fine for you.

**Comment by developit** [comment]
Yup!

**Comment by AvraamMavridis** [comment]
Cool! will send my PR during this week(end).

**Comment by hassanbazzi** [comment]
I made one of those PRs a while ago and we decided to keep that up to the user after the config PR lands. I do agree with us waiting on these to make the app less opinionated.

**Comment by hassanbazzi** [comment]
Custom config has landed. Feel free to add your aliases there :)

**Comment by AvraamMavridis** [comment]
Thx, I will close the issue :)
