### ISSUE TITLE
Request or a how-to guide - measure your application's performance while developing

### ISSUE THREAD

**Issue by oren** [developit/preact-cli#121]
I would like to request a how-to guide for keeping track of Preact app performance. I will be happy to write it myself but need to get educated by the community first.

Each time we make a code change, there is a potential for deteriorating the user experience.  What are the steps one should do to measure the performance impact of each change?  Someone on slack mentioned [this great article](https://hackernoon.com/10-things-i-learned-making-the-fastest-site-in-the-world-18a0e1cdf4a7) about performance but I am looking for a more details and practical steps I should take in order to measure it.  I understand that some of those steps might be manual and lengthy and it will not be possible to follow it on every code change, but it will still be valuable to know what, in a perfect world, one should do in order to keep her app's performance in a good shape.

Here is how I would start this how-to.

This goal of this guide is to keep your app's performance high while you add more feature to it.

## Prerequisites:
```
npm install -g lighthouse
```
(explain here what Lighthouse is)

After every code change generate the following performance reports:

## 1. Lighthouse
```
lighthouse http://0.0.0.0:8080
```
The output of this command will be an html page with lighthouse report. Save this html file somewhere so you can compare it after you make another code change.

## 2. Chrome's performance tab
Open the performance tab in Chrome and hit refresh on the page where your new feature was implemented. Take a screenshot of the output and save the image somewhere so you can compare it after you make another code change.
If you are happy with the performance implications of this code change, use git to commit it and add some details about the performance changes in the git commit message. For example you can have something like this: `git commit -am "use slider component for hours of operation. Lighthouse performance score went down: 82 -> 21"`

This is just an example. I don't understand how to use the Chrome's tab but I'll be happy to learn from people here that have more experience. Also, the lighthouse-cli have JSON output that might be better than the html output in some cases.

### Before:
![pic](http://i.imgur.com/e1tyxlS.png)
![pic](http://i.imgur.com/BwLWdXh.png)

### After:
![pic](http://i.imgur.com/8fOvpqG.png)
![Imgur](http://i.imgur.com/IJtCTlZ.png)

**Comment by thangngoc89** [comment]
@oren `http://0.0.0.0:8080`  is the development server, isn't it? So measuring any kind of performance there mean nothing. Build your website with `preact build` and measure it instead. 

Lighthouse includes a details section about why your score is so slow. Compare between 2 build to see why. 

For example:

![image](https://user-images.githubusercontent.com/3049054/27270697-48439fb6-54ea-11e7-8523-0a0c133fed9c.png)

**Comment by oren** [comment]
thanks! 

lighthouse doesn't work on htps://localhost:8080. I should figure out how set SSL certs on ubuntu and try that.

**Comment by wub** [comment]
Not sure if related, or helpful, but just in case: https://github.com/github/lightcrawler (uses lighthouse)

**Comment by oren** [comment]
very interesting! thank you
