### ISSUE TITLE
Honor browserslist in package.json for Babel, Autoprefixer, etc.

### ISSUE THREAD

**Issue by ethanroday** [developit/preact-cli#124]
Rather than hard-code a list of browsers in babel and webpack configs, it would be great if the CLI just added a default `browserslist` entry in `package.json` that the user could then edit. For those of us developing for, say, UC Browser for Android, there's currently no recourse to get the full set of required prefixes other than forking this repo and altering the webpack config manually.

**Comment by lukeed** [comment]
@ethanroday I'm not very familiar with all these config options, but is there a convention for passing _specific_ browser targets for Babel?

I ask because `browserlist` is an array of browser conditions -- but the `babel-preset-env` also accepts something like:

```js
require('babel-preset-env)({
  targets: {
    chrome: 52
  },
  browsers: [ 'last 2 versions']
});
```

Should we even allow `targets` like that? Do you (personally) care if that's not an option?

Appreciate any insight!

**Comment by rkostrzewski** [comment]
[This](https://github.com/babel/babel-preset-env/pull/19#issuecomment-252415998) probably can shed some light. Seems like it was just left there and browserslist can handle anything that browser specific targets  (i.e. `targets: { chrome: ... } }`) can (most likely apart from node but we don't have to care).

**Comment by lukeed** [comment]
Yeah, looks like anything can be written as a `browser` string. I don't personally think there's a need for the additional `target` keys, but I'm asking just in case.

**Comment by developit** [comment]
I like the idea that this gives people a single source of truth for defining their support targets.

**Comment by alex-shamshurin** [comment]
So does it support `.browserlistrc` ?

**Comment by developit** [comment]
No, only the package.json option.

**Comment by reznord** [comment]
for now 😛
