### ISSUE TITLE
Can I edit template.html to add links to <head>?

### ISSUE THREAD

**Issue by peterpme** [developit/preact-cli#130]
Hey,

It goes without saying that THIS IS AWESOME!

preact-mdl seems to be included, so bad example, but what about other external stylesheets or <head> elements I may want to add?

Thanks!

**Comment by thangngoc89** [comment]
I never do this but by reading the code, you can pass a template option to  the cli 

https://github.com/developit/preact-cli/blob/2175efc4c4157ab3dbfa7b5804043f646d170f5a/src/lib/webpack-config.js#L446

**Comment by peterpme** [comment]
thank you so much!

**Comment by bestwestern** [comment]
@peterpme could you please write how you solved this?

**Comment by peterpme** [comment]
hey @bestwestern , see @thangngoc89's comment
