### ISSUE TITLE
Idea: run lighthouse-ci on the demo output

### ISSUE THREAD

**Issue by developit** [developit/preact-cli#134]
Would it be useful to run [Lighthouse CI](https://github.com/ebidel/lighthouse-ci) on our builds?  Might be nice to track that metric since we're judged on it.

**Comment by reznord** [comment]
I would love that.

**Comment by rkostrzewski** [comment]
FYI Headless Chrome doesnt work with lighthouse well because some features are yet to be implemented.

Nothing stops us from using GUI version via xvfb tough.
