### ISSUE TITLE
Uglify settings break library code

### ISSUE THREAD

**Issue by dignifiedquire** [developit/preact-cli#136]
I have some crypto library code that when I include it breaks due to the very agressive uglify settings here: https://github.com/developit/preact-cli/blob/master/src/lib/webpack-config.js#L405 

Once I remove the `unsafe_comps` and `unsafe` options everything works fine. I know it's nice to get smaller code but maybe it would be good to disable unsafe options by default as I suspect that there are quite a few libraries out there that will break due to these optimisations. And this is especially hard to catch as tests usually run against dev builds and not against production builds.

#56 would allow me to workaround it, but I still feel that not breaking libraries should be rather the default and unsafe optimisations should be behind a flag.

**Comment by developit** [comment]
I think we could remove those, they are unlikely having too much effect.

**Comment by lukeed** [comment]
Yeah, we can remove. But going forward, #56 should be the way to handle this or any custom settings.

**Comment by dignifiedquire** [comment]
Fixed in #144
