### ISSUE TITLE
Push manifest doesn't include custom chunks

### ISSUE THREAD

**Issue by rkostrzewski** [developit/preact-cli#137]
**Description**:
Push manifest does not contain chunks created by using webpack's dynamic imports (`import()`) most likely by [this line](https://github.com/developit/preact-cli/blob/master/src/lib/push-manifest.js#L7). 

TBH I have no idea how to fix this or even if we should fix this.
Obviously we don't want to include chunks used by specific routes on every route. Maybe looking into webpack dependency graph and including them based on their parent (e.g. if it was `bundle.js` or `route-*.js` will do.

**Steps to reproduce**:
- `preact create app`
- `cd app`
- `echo "console.log('bar')" > ./src/foo.js`
- `echo "import('./foo.js')" >> ./src/index.js`
- `preact build --no-prerender`
- `cat ./build/push-manifest.json`

Generated chunk isn't there (should be called `2.chunk.*.js`)

**Comment by thangngoc89** [comment]
> TBH I have no idea how to fix

It happends because preact-cli only includes chunks that starts with `route-`  https://github.com/developit/preact-cli/blob/60ba2ae81f539978309539bdf6a77ad25435ccdd/src/lib/push-manifest.js#L7

**Comment by developit** [comment]
The dep graph could be a really cool way of doing this.  Right now we have no way to know that those chunks correspond to a given URL.
