### ISSUE TITLE
Chunk with polyfills is not added to the html file

### ISSUE THREAD

**Issue by jt3k** [developit/preact-cli#141]
I decided to try this tool in Windows. I ran the installation, then build the project `preact build`. After that, the browser opened the Internet explorer 11, and saw 'Promise is undefined' in console.

In our readme it is indicated that polyfills for promises have been added, but I do not see them in the resulting html-file.

![image](https://user-images.githubusercontent.com/1261240/27564490-b65fd522-5ae0-11e7-9ffa-e749c59acfe9.png)

Is it a bug, or have I not finished reading the documentation?

**Comment by developit** [comment]
In the current npm version of preact-cli, the polyfills are loaded using a dynamically created script tag, not directly in the html.

**Comment by rkostrzewski** [comment]
@jt3k this will be fixed in next release. What @developit described is future behaviour.

Right now pollyfils are placed in weback generated chunk, which is loaded by weback at runtime - however this requires a Promise to exist in the first place and fails on IE.

**Comment by jt3k** [comment]
ок! thanx
