### ISSUE TITLE
Maybe it's not a good idea to depend on global packages

### ISSUE THREAD

**Issue by sxcooler** [developit/preact-cli#146]
This repo design to handle all the preact developing by the global preact-cli pack. But may be it's not a good idea, because the created project can't run/build by themselves, and we need a global preact-cli on every environment, so the version compatibility is a problem too.
I think the [vue-cli](https://github.com/vuejs/vue-cli) and the [create-react-app](https://github.com/facebookincubator/create-react-app) ways are better.
I'm just giving some advice, if my language is not proper, forgive me I'm not a native speaker.

**Comment by lukeed** [comment]
Hi @sxcooler! Looks like you found your own answer 😅 The `preact-cli` _can_ be installed globally, but is perfectly suited to running as a local `devDependency` too!
