### ISSUE TITLE
clidemo: Complete SSR

### ISSUE THREAD

**Issue by leandrobrunner** [developit/preact-cli#147]
Only the root path is rendered in the server.

Example: [https://clidemo.preactjs.com/profile/john](https://clidemo.preactjs.com/profile/john) with javascript disabled shows the home component instead of the profile component.

**Comment by thangngoc89** [comment]
@leandrobrunner SSR isn't supported (or planing to) in preact-cli. We only prerender the index route

**Comment by developit** [comment]
I'm open to pre-rendering static routes, since we already parse them out.  Also there's a PR #88 that exports the Webpack Compiler instance so you could mount that into an Express server and do true SSR if you wanted.

**Comment by rkostrzewski** [comment]
I would totally like to expose compiler with full example on how to set up SSR, possibly with inlining critical css and loading the rest later.

**Comment by reznord** [comment]
regarding inlining critical-css there this [webpack plugin](https://www.npmjs.com/package/webpack-plugin-critical). It installs `phantom-prebuilt` while installing. If that is not an issue, we can use this.

Ideally the code for inlining critical-css should go [here](https://github.com/developit/preact-cli/blob/master/src/lib/webpack/webpack-client-config.js#L153).

**Comment by thangngoc89** [comment]
@reznord phantom? That thing is so old and can't keep up with mordern browser. Today we have chrome headless

**Comment by reznord** [comment]
Yeah !! Then it is better to go with [Addy Osmani's critical package](https://github.com/addyosmani/critical)

**Comment by rkostrzewski** [comment]
Which uses phantom under the hood :)

I think for the examples there's no need for that stuff as we've got css modules which we can select

**Comment by reznord** [comment]
I'd love to go with `styled-components`. 

It has pretty good SSR support and very easy in identifying critical-css !!

**Comment by lukeed** [comment]
Or [`emotion`](https://github.com/tkh44/emotion) 😉 

Paging Dr @tkh44

**Comment by rkostrzewski** [comment]
Yeah, css in js makes it a piece of cake 💯

**Comment by reznord** [comment]
> Browser Support no ie11 support (from emotion readme)

Emotion doesn't have support for IE11? o.O

**Comment by reznord** [comment]
And we have this - https://github.com/tkh44/emotion#usage-with-css-modules

**Comment by tkh44** [comment]
@reznord emotion supports ie11 just fine in inline mode.

**Comment by tkh44** [comment]
I've been meaning to add native preact support for you guys 😅 

Gimme 10 min

**Comment by thangngoc89** [comment]
@tkh44 You have to keep preact/react component in sync once you do that :sob:

**Comment by tkh44** [comment]
Yeah but it's < 30 lines

**Comment by lukeed** [comment]
Here's a [demo repo](https://github.com/lukeed/preact-cli-ssr) for a complete SSR solution using Preact CLI's output & an Express server.

There's now also [`preact-cli-plugin-critical-css`](https://github.com/matthewlynch/preact-cli-plugin-critical-css), in addition to some others, as a solution for critical CSS extraction per route.
