### ISSUE TITLE
Babel on node_modules folder fails when libraries have custom .babelrc

### ISSUE THREAD

**Issue by ethanroday** [developit/preact-cli#158]
### Steps to reproduce (on latest `master`):
1. Run `preact create <app-name>`
2. `cd <app-name>`
3. `npm install --save redux preact-redux`
4. In `app.js`, initialize a store and hook it up with a `<Provider>` component
5. `npm run build`

### Expected result:
The build will succeed.

### Actual result:
The build fails, since `node_modules/preact-redux` has a `.babelrc` file, which references the `transform-node-env-inline` plugin. Since #117, ES6 code under `node_modules` gets run through Babel. Babel picks up the `.babelrc` file in `node_modules/preact-redux` and fails, since the `transform-node-env-inline` dependency is not installed.
Installing the plugin (as well as the `react` and `es2015` presets) fixes the problem, but I certainly don't think the expected behavior should be for the build process to `npm i` in every library folder that contains ES6 code (especially because most of them, `preact-redux` included, already ship with a precompiled ES5 version). Then again, you can't just assume that the CLI's Babel config will be sufficient for any given library that _doesn't_ ship with ES5 code.
@prateekbh, thoughts?

**Comment by developit** [comment]
What version of preact-cli are you using?

**Comment by ethanroday** [comment]
Hm, I don't think so. I ran a fresh `npm i`. Why, are you not getting this?

**Comment by thangngoc89** [comment]
@ethanroday this PR supposes to fix that https://github.com/developit/preact-cli/pull/153 . It's in preact-cli@1.3.0.

**Comment by ethanroday** [comment]
Ah I last pulled yesterday mid-morning PST. Assumed I was on latest master but I wasn't! You guys move so fast!
Can confirm that this particular case is fixed.

**Comment by lukeed** [comment]
Aye, we saw this as an issue right after releasing 1.2.0

Thanks for such detailed reports though!
