### ISSUE TITLE
Code is over 6k. Plz fix

### ISSUE THREAD

**Issue by samccone** [developit/preact-cli#16]

**Comment by developit** [comment]
What code

**Comment by samccone** [comment]
The CLI 😂

**Comment by NekR** [comment]
Remove offline-plugin from deps, you don't use it anyway 😋

**Comment by developit** [comment]
Gonna add a second copy

**Comment by thangngoc89** [comment]
Please fix this asap. Downloading 6k to node_modules is unacceptable

**Comment by developit** [comment]
Closing for my sanity :P

**Comment by samccone** [comment]
:dancer:
