### ISSUE TITLE
The favicon doesn't automatically update

### ISSUE THREAD

**Issue by swarajd** [developit/preact-cli#167]
I placed a new 16x16 favicon.ico file in the `/src/assets/` directory, but both when running the dev server and running build, the favicon does not update.

I tried emptying the cache and navigating directly to the file but it was taking the file from the `resources/` directory.

**Comment by swarajd** [comment]
edit: updating the cli fixes this.

**Comment by Jonarod** [comment]
Sorry to bother with a closed issue, but I get the same problem using the cli 2.0.0... Anybody get the same problem here ?
