### ISSUE TITLE
Check for dependencies while creating a new project

### ISSUE THREAD

**Issue by reznord** [developit/preact-cli#169]
It would be great to have a dependency check so we can avoid running into issues like #165 

I would love to add the following [code](https://github.com/phenomic/phenomic/blob/fa314107debb6ca1f860b7c7a38dc30b0e2c8b6b/packages/cli/src/check-engine.js) for dependency check.

@rkostrzewski @developit @lukeed any suggestions?

**Comment by reznord** [comment]
For running the check we have two choices:
- when user installs `preact-cli`
- when user creates a new project. i.e. while `preact create my_app`.

In the first case, there might be users who maintain multiple node versions (like me :P) for various projects and that might become a problem

In the second case we can do it as a first step before executing the `create` command

**Comment by lukeed** [comment]
You can run the same check at both points.

```js
{
  "postinstall": "node lib/check.js"
}
```

And

```js
// src/index.js
const check = require('./lib/check');

let isValidNode = check();

if (!isValidNode) {
  return; // already logged
}

installHooks();
// continue...
```
