### ISSUE TITLE
preact watch --https=true, runs http instead of https if cert has been created.

### ISSUE THREAD

**Issue by flea89** [developit/preact-cli#175]
I've tried to run the devserver on https, If the webpack certificate is used the server starts an https server as expected.

If a certificate has been created ( the webpack one isn't used)  the server starts over http instead of https.

I've had a quick look to the source code, and I think the issue is https://github.com/developit/preact-cli/blob/2bd02cb8e5c442c0987d90d6cada3a91516fa790/src/lib/webpack/webpack-client-config.js#L126, ssl is an object and not a boolean.

If I'm not wrong that object is set https://github.com/developit/preact-cli/blob/master/src/commands/watch.js#L47.

Thanks

**Comment by developit** [comment]
The flag is `preact watch --https` - it seems like passing `=true` is killing that conditional.  Can you test without the value?

**Comment by flea89** [comment]
Unfortunately that doesn't solved the problem.
Https option is actually picked but doesn't starts an https server in that case ( it does with the same command if webpack cert is used).

Isn't the problem that getSsl returns an object and webpack-client-config tests for a boolean true ?

**Comment by developit** [comment]
hmm yeah - not sure where that was introduced.

**Comment by flea89** [comment]
Nice I was just sending the pull request but I this has been already fixed.
Nice!

**Comment by reznord** [comment]
Closing this issue, fixed in #176
