### ISSUE TITLE
Prerender error and workarounds

### ISSUE THREAD

**Issue by thangngoc89** [developit/preact-cli#178]
Preact-cli comes with prerender which render your `/` route using server-side rendering technique. So if you run `npm start` successfully but `npm run build` produces some errors, this mean that the prerender is failing because of some code requires DOM to work.

Workarounds:

- Wrap your with this to make sure it won't execute when prerendering. 

```
if (typeof window !== "undefined") {
  // Your code here
}
```

- Turn off preredering by run `npm run build -- --no-prerender`

**Comment by nephix** [comment]
Had the same issue using `HashRouter`. `npm run build -- --prerender=false` didn't work for me but the `window !== "undefined"` check did.

**Comment by thangngoc89** [comment]
@nephix I updated the command. So sorry. `npm run build -- --no-prerender`

**Comment by rkostrzewski** [comment]
@thangngoc89 what's expected outcome of this issue? Friendly error message with steps how to write code which could be used on node side?

I guess we could wrap prerender with try catch block that checks for `TypeErrors` (possibly with some whitelist of variables like `window`, `document`, `location`, `localStorage` and others) and prints user friendly message with steps on how to fix this.

**Comment by nephix** [comment]
IMO the example app that preact-cli creates should show how to handle the issue if DOM is required on `/`

**Comment by thangngoc89** [comment]
@rkostrzewski Yup. A friendly error for user.

**Comment by glegenty** [comment]
Hi ! 

I try to prerender the default template with no extra code but it fails.
i simple use  `npm run build` and i got this :
> Unable to read file: /Users/jorel/Projects/proto/prerender/src/external "preact"
>Error: No valid exports main found for '/Users/jorel/Projects/proto/prerender/node_modules/preact'
method: HteQ
at: /Users/jorel/Projects/proto/prerender/src/external "preact":1:17

I'm on macOS Catalina with node 13.6.0

Did i miss something ?

**Comment by glegenty** [comment]
The issue was coming from node 13.6. I siwtched to 12.6.2 and the prerender is working fine. The only issue that i see now is that the home page seems to not be rendered. I cannot find the html file in the build folder.

**Comment by ForsakenHarmony** [comment]
You might want to update to the latest `preact` version, that should fix the first problem you had
