### ISSUE TITLE
Cannot watch on specific host

### ISSUE THREAD

**Issue by minhchu** [developit/preact-cli#180]
**Problem:**

When I run `preact watch --host "127.0.0.1"` inside a `preact` project created with `preact-cli`, I got this screen:

![preactcli](https://user-images.githubusercontent.com/14136809/27785460-e78b8ce6-6007-11e7-8766-0cc8e745e9fe.JPG)

It seems that `yargs` package overrides the `h` alias option and turns it into a help command.

**How to fix:**

Delete [the alias](https://github.com/developit/preact-cli/blob/master/src/commands/watch.js#L23) of `host` option resolves the issue.

![preactcli2](https://user-images.githubusercontent.com/14136809/27785670-8cba78a8-6008-11e7-98a6-b811b3651237.JPG)

**Comment by reznord** [comment]
@minhchu ah, right !!

yargs defaults `-h` to `help`.

**Comment by lukeed** [comment]
Traditionally, a `--host` flag is aliased to `-H`

**Comment by reznord** [comment]
> Traditionally, a --host flag is aliased to -H

Oh, this can also be done !!

**Comment by reznord** [comment]
fixed in #183
