### ISSUE TITLE
Prerendering set of routes

### ISSUE THREAD

**Issue by framp** [developit/preact-cli#185]
Being able to prerender a set of routes (instead of just the root) would be really useful for building static websites.

It should just be a matter of adding more instances of html-webpack-plugin [here](https://github.com/developit/preact-cli/blob/42a7511f77f5b0a5bad3c6b5296a4bec6588f9ec/src/lib/webpack/webpack-client-config.js#L167)

Is there a plan for this feature or is there good reason not to do this?
Happy to work on a PR

**Comment by lukeed** [comment]
I'm not sure that it's part of "the plan" but it definitely can be done 👍 

> FWIW, I'm also building a (separate) tool right now that includes this as a feature. Finished this part today~ 🎉
