### ISSUE TITLE
Suggestion: add option to disable JS sourcemap generation

### ISSUE THREAD

**Issue by weijiekoh** [developit/preact-cli#186]
`preact build` generates sourcemap files but there's no option to disable this feature. Some users may want to not have sourcemaps in production builds, so a feature to disable sourcemap generation would be helpful. Otherwise, the user has to delete the sourcemap from the build directory by themselves.

**Comment by thangngoc89** [comment]
@weijiekoh you can disable the sourcemap by using `preact.config.js` to alter webpack config. I was the one who requested this feature because I need to upload the source map to some sort of error catching service. And yeah, nobody should leave source map on production server

**Comment by reznord** [comment]
Surprisingly CRA just leaves that option to the user, if he wants to disable, he has to delete the `bundle.js.map` file from the build folder.

**Comment by thangngoc89** [comment]
@reznord Like I said above, use `preact.config.js` to tell webpack not emits a source map

**Comment by weijiekoh** [comment]
Thanks @thangngoc89.

Here's the code I used to disable sourcemap generation in `preact.config.js`:

```js
export default function (config, env, helpers) {
  //...
  for (let i=0; i < config.plugins.length; i++){
    if (config.plugins[i].constructor.name === "UglifyJsPlugin"){
      config.plugins[i].options.sourceMap = false;
      break;
    }
  }
  //...
}
```
This makes `bundle.js.map`  **and** `polyfills.js.map` **not** be generated in the final build.

Hope this snippet helps anyone who wants to tackle the issue by using `preact.config.js`. 

@reznord's method is a good way to further ensure that the sourcemap does not show up on the production server.

**Comment by thangngoc89** [comment]
@weijiekoh actually, you just need to remove the devtool config from webpack to prevent source map emiting.

See this line: https://github.com/developit/preact-cli/blob/e740dd3affbe8ad812be29e5605a43c798ac2098/src/lib/webpack/webpack-base-config.js#L206

I don't work with webpack-blocks so no idea how to alter it, but I think it's a better way. For css sourcemap, it's scattered throughout the config so not sure how to remove it completely (without manually removing the file after build)
