### ISSUE TITLE
preact.config.js snippets

### ISSUE THREAD

**Issue by snc** [developit/preact-cli#188]
As it is now possible to change the configuration via preact.config.js, some useful snippets can be found in several issues: https://github.com/developit/preact-cli/search?q=preact.config.js&type=Issues&utf8=%E2%9C%93

May it be worth to collect (some of) them here in the Github Wiki or in a README? It may be hard to maintain, what do you think about it?

**Comment by weijiekoh** [comment]
Agreed. I think the quickest thing that can be done is to add a short paragraph in the README to tell the user that [WebpackConfigHelpers](https://github.com/developit/preact-cli/blob/master/docs/webpack-helpers.md) is very useful for changing the webpack config. Here's a suggestion of what can be added to the README:

> Use the `helpers` argument to easily modify the `config` object. For example, you can disable the `sourceMaps` option of `UgflifyJsPlugin` like this:
> ```js
> helpers.getPluginsByName(config, "UglifyJsPlugin")[0].plugin.options.sourceMap = false;
> ```

**Comment by thangngoc89** [comment]
Github already has a Wiki section, what do you think @developit ?

**Comment by reznord** [comment]
That would be great !! That makes the README clean too !!

**Comment by developit** [comment]
Just dropping a note here - I think plugins would make this event better.  I'm fine with the wiki, since these are likely too specific and lengthy for the readme itself.

**Comment by developit** [comment]
Wiki space for the above:
https://github.com/developit/preact-cli/wiki/Config-Recipes

**Comment by rkostrzewski** [comment]
Filled with recipes
