### ISSUE TITLE
Installation error `callback() can only be called once.`

### ISSUE THREAD

**Issue by feimosi** [developit/preact-cli#191]
I'm getting the following error when running `sudo npm i -g preact-cli`. I've also tried different node / npm  versions with no luck (I was getting #73).

```
/usr/bin/preact -> /usr/lib/node_modules/preact-cli/lib/index.js

> fsevents@1.1.2 install /usr/lib/node_modules/preact-cli/node_modules/fsevents
> node install


> simplehttp2server@2.0.0 postinstall /usr/lib/node_modules/preact-cli/node_modules/simplehttp2server
> node lib/install.js

/usr/lib/node_modules/preact-cli/node_modules/each-async/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/lib/node_modules/preact-cli/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at /usr/lib/node_modules/preact-cli/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/lib/node_modules/preact-cli/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:110:20)
    at ConcatStream.emit (events.js:207:7)
    at finishMaybe (/usr/lib/node_modules/preact-cli/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at endWritable (/usr/lib/node_modules/preact-cli/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at ConcatStream.Writable.end (/usr/lib/node_modules/preact-cli/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DuplexWrapper.onend (/usr/lib/node_modules/preact-cli/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:314:30)
```

Tested on the latest versions of node (8.1.3) and npm (5.0.4).
I'm running Arch Linux.

**Comment by feimosi** [comment]
It actually belongs to GoogleChrome/simplehttp2server#31, but I'd leave this open for a while, maybe someone has an idea or maybe it's an environment related issue.

**Comment by malaniz** [comment]
I'm having the same problem in Arch Linux too.

**Comment by porfirioribeiro** [comment]
I also had this problem, it's a permissions problem somehow.
So i fixed it by changing my global modules folder to be in my home folder, so do not need to use sudo
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by feimosi** [comment]
I confirm, that resolves the issue :+1:

**Comment by joelchu** [comment]
I run the npm via sudo - the problem still there. 

I am running Ubuntu Mate 17.04

**Comment by calpa** [comment]
@joelchu Try to install without sudo...
Just type `npm i -g preact-cli` is ok.

Env: npm: v5.3.0, node: v8.5.0

**Comment by joelchu** [comment]
witthout sudo it won't even run.
Because I am not changing the folder permission just because of node.js 
so it's stock option. 

Why can't they just do standard stuff. angular react don't have problem with standard cli installation.

**Comment by r21meghashyam** [comment]
Running with sudo gives callback() error
Running without sudo gives EACCES error

**Comment by kevinsheffield** [comment]
Had this issue with WSL on one of my work laptops and Option 2 from https://docs.npmjs.com/getting-started/fixing-npm-permissions fixed it for me.

**Comment by swapu258** [comment]
I had this error and  I simply uninstalled npm and node globally.
Then i installed nvm from [https://github.com/creationix/nvm](url) 
then 

1. nvm install node 
2. npm install preact-cli -g
Voila! everything worked in a single go.

**Comment by zugoripls** [comment]
I still getting errors even I run with `sudo`. When I try running with `sudo -s` and It worked.
