### ISSUE TITLE
window or document is not defined

### ISSUE THREAD

**Issue by Lizhooh** [developit/preact-cli#198]
I want to include some **libraries** and **use cdn**.
Where's **index.html**?
What should I do?

**`npm start is no error, but npm run build error:`**
```js
Template execution failed: ReferenceError: window is not defined
  ReferenceError: window is not defined
Template execution failed: ReferenceError: document is not defined
  ReferenceError: document is not defined
```

**`code 1 (window is not defined):`**
```js
import Swiper from 'swiper';

// .... Swiper using window object
componentDidMount() {
  let { options, swiperIsInitialized } = this.props;      
  //  <div className="swiper-container" ref={r => this.root = r}>
  this.swiper = new Swiper(this.root, options);
  this.props.swiperIsInitialized(this.swiper);
}
```

**`code 2  (document is not defined):`**

```js
import './style';
import App from './components/app';

const head = document.querySelector('html > head');

// add css
head.innerHTML += `
    <link href="https://cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css" rel="stylesheet">
`;

export default App;
```

**Comment by developit** [comment]
There's no need to put those in `<head>`, you can just render them using VDOM.

In `components/app.js`:

```js
class App extends Component {
  render() {
    return (
      <div id="app">
        <link href="//cdn.bootcss.com/material-design-icons/3.0.1/iconfont/material-icons.min.css" rel="stylesheet" />
        <link href="//cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css" rel="stylesheet" />
        <Header />
        <Router onChange={this.handleRoute}>
          <Home path="/" />
          <Profile path="/profile/" user="me" />
          <Profile path="/profile/:user" />
        </Router>
      </div>
    );
  }
}
```

For your `code 1`:

```js
componentDidMount() {
  let { options, swiperIsInitialized } = this.props;      
  //  <div className="swiper-container" ref={r => this.root = r}>
  let Swiper = require('swiper');
  this.swiper = new Swiper(this.root, options);
  this.props.swiperIsInitialized(this.swiper);
}
```

**Comment by hassanbazzi** [comment]
Check out https://www.npmjs.com/package/window-or-global

:)

**Comment by Lizhooh** [comment]
@hassanbazzi  Thank you, but ... 
Swiper.js source  code using `window object`, how to use `window-or-global` to solve the problem ?
Could you give me a demonstration ?

**Comment by thangngoc89** [comment]
@Lizhooh See https://github.com/developit/preact-cli/issues/178

**Comment by Lizhooh** [comment]
@thangngoc89 ok, thank.

**Comment by Lizhooh** [comment]
( ^_^ ), then the solution is:: 
**add npm scripts**:  `"np-build": "preact build --no-prerender"`
**run:** `npm run np-build`

**Comment by simonv3** [comment]
I'm going to put this here because it took me a while to figure out, but it looks like dynamically loading the component that contains the library code that uses leaflet seems to fix this. In my case I use leaflet, which does not support server side rendering, and uses `window` quite extensively. 

In the below example `WhereWeWorkMap` loads leaflet. (using `react-leaflet`). 

```
const WhereWeWorkMap = lazy(() => import("widgets/WhereWeWorkMap"));
...
...
return <Suspense fallback={<Fragment></Fragment>}>
  <WhereWeWorkMap />
</Suspense>
```

Folks might find this useful, or also tell me why they think this is a bad idea.

**Comment by rschristian** [comment]
@simonv3 

[As the docs say](https://github.com/preactjs/preact-cli#pre-rendering), it's probably better and easier to wrap the specific parts that cannot be prerendered in a window check: `if (typeof window !== "undefined") { ... }`

**Comment by simonv3** [comment]
@rschristian It's an external library, so I don't have access to that code, and when I added that if statement around the component it still threw that error.

**Comment by rschristian** [comment]
@simonv3 You should be able to wrap it around the import or whatever. Not sure how you're using that lib, but so long as you don't import it, it can't execute and look for `window`. Still will probably need the dynamic import, (i.e., `import()`) but you can ensure that a), your component isn't unnecessarily lazily loaded and b) can still prerender the rest of your component.
