### ISSUE TITLE
Eject option

### ISSUE THREAD

**Issue by knight-bubble** [developit/preact-cli#199]
Are there any plans of adding "eject" option, similar to https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup?

**Comment by prateekbh** [comment]
Is there an ongoing effort for this? else I am planning to take this up and discuss the approaches we can take for this.

**Comment by developit** [comment]
I'm not really sure we need eject, since it's possible to customize configuration already.  What is the value we get out of providing eject?

**Comment by lukeed** [comment]
I agree ^^ CRA came with `eject` because it started off with a closed door -- you either liked what you got, or you didn't.

**Comment by prateekbh** [comment]
Not sure, I just felt that `eject` would give user land an option to do anything if they're stuck at any corner case. I know the work for keeping `cli` flexible is super awesome, but I am the believer that one solution might never fit all. This is when `eject` makes cli as a boilerplate code.

But yes I do not have a solid use case for now, and may be we can keep this as a P2/P3 for sometime later

**Comment by developit** [comment]
Yup. I think the main blocker here is that we have nicely structured the CLI instead of keeping it as a single monolithic `webpack.config.js`, which means that in order to produce a standalone webpack config we'd have to move back to writing things as a big standalone webpack config (or do crazy codegen magic).

**Comment by prateekbh** [comment]
oh yeah, I guess we can park this for now, until someone comes up with a solid use case

**Comment by lili21** [comment]
what's about the project which use something like `Docker` for building and deploying ? 
without `eject`, I have to install `preact-cli` every time before `building`.

**Comment by thangngoc89** [comment]
@lili21 you can actually include preact-cli as a devDep to avoid that

**Comment by lili21** [comment]
I know I can do that. It just doesn't feel right.
