### ISSUE TITLE
"--install=false" command not working while initialising a project

### ISSUE THREAD

**Issue by knight-bubble** [developit/preact-cli#203]
So the issue is:
```
preact create project-name --install=false
```
or
```
preact create project-name ---no-install
```
just do not work. This is valid for git option too. It gets set to true every time.

**Comment by reznord** [comment]
@knight-bubble the command for this is `preact create project_name --no-install`. You have added an extra '-' ;)

**Comment by knight-bubble** [comment]
@reznord this a typo here definitely☺
But I'll recheck it tomorrow.

**Comment by knight-bubble** [comment]
@reznord you were right:)
