### ISSUE TITLE
Rebuild the application after installing a new package

### ISSUE THREAD

**Issue by reznord** [developit/preact-cli#208]
So, right now when I add a new package to the project, I have to restart the dev build, so that I can use the package that I've added. 

It would be great if we can trigger a rebuild when a new package is added. CRA has this functionality and it is quite useful. 

Any suggestions @developit @lukeed @rkostrzewski

**Comment by knight-bubble** [comment]
@reznord In the CRA it's done by https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/WatchMissingNodeModulesPlugin.js
And called like this https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js#L272

**Comment by reznord** [comment]
@knight-bubble I've seen this. Asking if adding this will get or helpful or not.

**Comment by SaraVieira** [comment]
@reznord how about a postintall script in the package.json that runs preact build? 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by reznord** [comment]
I don't think that will work, since the user may install a package from a new terminal instance. In that case the postinstall script doesn't work.

**Comment by developit** [comment]
The CRA plugin looks neat.

**Comment by reznord** [comment]
Cool, I'll take this on.
