### ISSUE TITLE
Custom project templates plans

### ISSUE THREAD

**Issue by knight-bubble** [developit/preact-cli#209]
Not sure if there is already such issue or a discussion. If there is already something like that, point me to it please.
Are there any plans of allowing as template git repo, as done in vue-cli?
There are also a lot of features related to templates in vue-cli.
I think it can be helpful to use metalsmith for scaffolding of projects.

**Comment by lukeed** [comment]
Hey! Yes, this is a duplicate of #99. Interested in hearing your thoughts & ideas, so please do share over there. 👍 

Closing in favor of that thread.
