### ISSUE TITLE
Error 404 when registering Service Worker in GitHub Pages

### ISSUE THREAD

**Issue by andrevargas** [developit/preact-cli#213]
Hello!

I'm new to this world of PWA's, so I'm trying to use **Preact CLI** as my first _real world_ experience. Therefore, I'm deploying my app to **GitHub Pages**, using [gh-pages](https://www.npmjs.com/package/gh-pages), to get HTTPS domain and stuff.

I'm trying to host my app in a URL like this: [my-username.github.io/my-app-name](http://my-username.github.io/my-app-name). So, I'm getting an 404 error when registering the generated Service Worker.

![404 Not Found sw.js](http://i.imgur.com/W875Ipj.png)
And this makes sense! [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Why_is_my_service_worker_failing_to_register), the path to my service worker file must be written relative to the origin, not my app's root directory.
 
So, the **real** problem here is that I don't have access to the script that registers the service worker, and I can't configure the path to be relative to the origin. The CLI registers the service assuming that it's hosted directly in root ([`/sw.js`](https://github.com/developit/preact-cli/blob/master/src/lib/entry.js#L8)).

**My question is**: Is there a way I can configure the path to register the service worker file? Is there an option (maybe in Webpack config) that I can just override?

I'm really sorry if this question doesn't make sense or was already answered elsewhere, but I didn't find it. :disappointed: By the way, I'm really loving using **Preact CLI**. If there's something I can help in this case (code or docs), let me know. :coffee:

Thank you all for this awesome tool. :heart: :octocat:

**Comment by developit** [comment]
Ah looks like we need to do something to support a base path like that.

**Comment by andrevargas** [comment]
@developit Yeah. This assumption is so true that when I first deployed, I got 404 when fetching the most basic files:

![404 Errors](http://i.imgur.com/kKIxIGn.png)

Of course this can be fixed just by overriding the `template` or some `webpack` config. But for **service worker** files, it's a special case.

Do you think it's relevant to add this option right now? Deploying to GitHub Pages may be a common use case for simple/learning purpose PWA's, since we need HTTPS.

**Comment by thangngoc89** [comment]
@andrevargas I think Github Pages is still the most popular choice for deploying a static sites.

**Comment by jeffposnick** [comment]
FWIW, passing in a relative URL to `navigator.serviceWorker.register()` is sometimes the right approach. The one reason *not* to use a relative URL is if you have subpaths underneath your top-level path. I don't know how common that would be with `preact-cli`-scaffolded web apps, but if there's a chance that navigations might be done to anything other than a single-level path, it's best to continue using absolute URLs.

On the `create-react-app` side of things, [registration](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/src/registerServiceWorker.js#L33) uses absolute URLs, with a previously-defined `process.env.PUBLIC_URL` prefix.

**Comment by reznord** [comment]
in CRA, it will ask you to add a `home_page` URL and it will use that as a the public_path. (IIRC)

**Comment by developit** [comment]
^ I'd be up for adding a `--public-path /root-dir` option to `preact build`, and/or looking for `process.env.PUBLIC_URL`.

**Comment by reznord** [comment]
> I'd be up for adding a --public-path /root-dir option to preact build, and/or looking for process.env.PUBLIC_URL

I wouldn't go for a flag. It looks ugly.

Instead we can add it to the `package.json` and read it from there.

**Comment by developit** [comment]
Only issue there would be if you wanted to build with different output paths (maybe development and production). Perhaps it's best to leave this up to `preact.config.js`.

**Comment by prateekbh** [comment]
@reznord  @developit @rkostrzewski  i am planning a preact cli workbox plugin which will simplify all of this process without a flag, if we can get #85 to merge/review, or even get the discussion started

**Comment by nandubatchu** [comment]
@developit What is the current solution to this problem?

**Comment by TPMinan** [comment]
Still can not find the solution to the problem?

**Comment by helgeh** [comment]
Me too, I tried to host my app on Github Pages but the sw.js was requested from the root so no dice.

**Comment by lhuria94** [comment]
Facing the same issue. :(
