### ISSUE TITLE
git stage all files during initialising a repo?

### ISSUE THREAD

**Issue by reznord** [developit/preact-cli#216]
I wouldn't normally prefer having an automated commit since the user might think it as a "magic".

More over, seeing from a user point of view, I wouldn't really like to commit right after creating a repo.

Leaving this with tagged discussion.

**Comment by prateekbh** [comment]
☝️ in addition to everything @reznord  said, also the the notion of adding everything with `-A` and making a commit might create undesired results for a monolithic repo kind of scenario.

I guess its ok to setup the entire structure and get it running, but what to commit and when to commit should be completely left to the user.

What does everyone think about it?

**Comment by prateekbh** [comment]
will raise a PR after #207 is merged, code is ready in local btw
