### ISSUE TITLE
Error while running `npm run lint` in preact-cli

### ISSUE THREAD

**Issue by reznord** [developit/preact-cli#226]
`npm run lint` is failing with the following error:

<img width="1280" alt="image 2017-07-14 at 12 29 32 pm" src="https://user-images.githubusercontent.com/3415488/28201832-6fb411a2-6890-11e7-976d-32220c02c761.png">

It cannot find `eslint-config-synacor` module. I tried removed the `node_modules` and re-installed again still I am getting the same issue.

Node version: 8.1.3
Npm version: 5.0.1

**Comment by reznord** [comment]
adding `eslint-config-synacor` to deps directly works perfectly fine. 

wondering if this is an issue with `npm dedupe`. I've had this issue with `npm@5.2.0` but not with `npm@5.0.1`.

**Comment by developit** [comment]
Weird...

**Comment by reznord** [comment]
That looks like some `npm dedupe` issues to me. With the latest version it is working perfectly fine.
