### ISSUE TITLE
single build.js

### ISSUE THREAD

**Issue by mehmetkose** [developit/preact-cli#232]
Hi guys,

For some reasons, the end of the day, I need just only one "build.js" file. Like same as preact-boilerplate. Is there any parameter for that?

>>> preact build --param
I want: index.html, style.css, build.js

And then my tasks,
>>> gulp build
will merge into index.html

**Comment by developit** [comment]
Right now you'd have to add a `preact.config.js` to your project with the following:

```js
export default (config, env, helpers) => {
  // get all rules:
  let rules = helpers.getRules(config);
  // find the `async!` rule:
  let asyncRule = rules.filter( ({ rule }) => /async-component-loader/.test(rule.loader) );
  // turn it off:
  asyncRule.test = () => false;
};
```

**Comment by mehmetkose** [comment]
I changed the name of **routes** folder and worked. thanks.
