### ISSUE TITLE
Adding Google Fonts

### ISSUE THREAD

**Issue by timarney** [developit/preact-cli#236]
Is there any way to add to the index file to include Google Fonts?

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">

**Comment by developit** [comment]
Totes - 3 options for this that I'm aware of.

1. Import it from some css:

```js
// index.js
import './style/index.css';
```

```css
/* style/index.css */
@import url('//fonts.googleapis.com/css?family=Open+Sans');
```

2. You can SSR it!

```js
// index.js
export default () => (
  <div class="app">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans" />
    {/* regular app stuff here */}
  </div>
);
```

3. Specify a custom HTML template and make it all your own. I recommend starting from the [internal default HTML template](https://github.com/developit/preact-cli/blob/master/src/resources/template.html).

```sh
preact build --html-template my-template.html
```

The only issue with --html-template is that if preact-cli updates need a new template, you'll still have your custom one.  If you can use VDOM to render the fonts, that'll be better.

**Comment by timarney** [comment]
Nice - thanks for taking time to show the options.  Works great.

**Comment by maciej-gurban** [comment]
Currently, by following 3.1 there will be multiple PostCSS Loader errors being thrown.
