### ISSUE TITLE
Run dev server as https

### ISSUE THREAD

**Issue by nephix** [developit/preact-cli#242]
When I run the dev server via `npm start` I can access my preact app at `http://0.0.0.0:8080`.

When working with `navigator.geolocation` I get the follow console message in Chrome:
```
[Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. 
To use this feature, you should consider switching your application to a secure origin, such as HTTPS. 
See https://goo.gl/rStTGz for more details.
```

My only workaround at the moment is to run `npm run serve` or use Firefox on my Phone to test & develop my app.

Is it possible to run the dev server as https or add that feature in future releases?

**Comment by prateekbh** [comment]
can you try running on localhost:8080 instead?
 i guess localhost is exempted from these

**Comment by nephix** [comment]
Hey @prateekbh,

yes localhost works but it's not solution for tests on mobile devices. Thanks anyway

**Comment by prateekbh** [comment]
ummm you can port forward it from chrome://inspect. no extension, ships with chrome

**Comment by nephix** [comment]
@prateekbh I was not looking for other workarounds when opening the issue. But thanks for pointing both solutions. If we could have https implemented as a feature that'd be great.

**Comment by prateekbh** [comment]
sure, just wanted to unblock you while we discuss and take this ahead 👍

**Comment by reznord** [comment]
@nephix will a flag `--https` do the work in the `npm start` so that you can start the dev server using `https`?

**Comment by reznord** [comment]
or something like an env var like `HTTPS=true npm start`

**Comment by nephix** [comment]
@prateekbh both would be fine. I would prefer a flag.

**Comment by lukeed** [comment]
I haven't done it in a while, but you can already run [`watch`](https://github.com/developit/preact-cli/blob/master/src/commands/watch.js#L43-L57) with the `--https` flag.

**Comment by lukeed** [comment]
If you don't want to modify the `start` definition directly, anything you pass after `--` will be sent to `preact-cli` (instead of `npm` itself).

```sh
$ npm start -- --https
```

**Comment by reznord** [comment]
> $ npm start -- --https

for npm start command we are doing the following: 
```
start: 'if-env NODE_ENV=production && npm run -s serve || npm run -s dev',
```

so, if you want to use https on npm start you have to do the following:

```
$ npm start -- -- --https
```

**Comment by lukeed** [comment]
Oh, forgot 😅 I don't like logic inside a command, so I break apart `start` and `watch` commands.

**Comment by nephix** [comment]
Environment variable a la `HTTPS=true` seems to be much more elegant then instead of 
```
$ npm start -- -- --https
```
:smile:
