### ISSUE TITLE
Template execution failed - build

### ISSUE THREAD

**Issue by timarney** [developit/preact-cli#243]
When running the build command with version 1.4.0 I'm getting the following error 

```
Template execution failed: Error: ENOENT: no such file or directory, open '[this is the path to the project]/src/~/domkit/builtinStyle.js'
  Error: ENOENT: no such file or directory, open '[this is the path to the project]/src/~/domkit/builtinStyle  .js'

  - prerender.js:69 handlePrerenderError
    [this is the project name]/[preact-cli]/lib/lib/webpack/prerender.js:69:33

  - prerender.js:52 prerender
    [this is the project name]/[preact-cli]/lib/lib/webpack/prerender.js:52:3

  - webpack-client-config.js:194 Object.ssr
    [this is the project name]/[preact-cli]/lib/lib/webpack/webpack-client-config.js:194:54

  - template.html:111 EM6I.module.exports
    [this is the project name]/[preact-cli]/lib/resources/template.html:111:37

  - index.js:264
    [this is the project name]/[html-webpack-plugin]/index.js:264:16

  - util.js:16 tryCatcher
    [this is the project name]/[html-webpack-plugin]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [this is the project name]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [this is the project name]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:569:18

  - promise.js:606 Promise._settlePromiseCtx
    [this is the project name]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:606:10

  - async.js:138 Async._drainQueue
    [this is the project name]/[html-webpack-plugin]/[bluebird]/js/release/async.js:138:12

  - async.js:143 Async._drainQueues
    [this is the project name]/[html-webpack-plugin]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [this is the project name]/[html-webpack-plugin]/[bluebird]/js/release/async.js:17:14
```

**Comment by reznord** [comment]
@timarney hey, sorry for the late reply.

Could you please tell me if you are still able to reproduce it. If so can you provide the steps to reproduce it?

And the system requirements too 😄

**Comment by timarney** [comment]
Thinking this might be very specific to my build.  Note: It doesn't happen with the --no-prerender flag.

node 8.2.1
npm 5.3.0

I'll see if I can narrow it down further wasn't sure if this had come up somewhere before.  

Found the error kind of odd:
`no such file or directory, open -> src/~/domkit/builtinStyle.js'`

**Comment by timarney** [comment]
So I haven't been able to track down the source of the issue but wrapping a try catch around this line in prerender.js fixes the issue.

`
_fs2.default.readFileSync(sourcePath, 'utf-8').split('\n');
`
Assuming the CLI uses domkit somewhere ... not sure why it's looking in my source dir for it.

https://github.com/yuanyan/domkit/blob/master/builtinStyle.js

**Comment by timarney** [comment]
Looks like this might be related to https://github.com/developit/preact-cli/issues/310

Looks like this commit will fix.

https://github.com/developit/preact-cli/commit/40778ac5f7c6fd47fef11ab7cb3a9ef8a7c0b28e

**Comment by reznord** [comment]
This happens when you run `preact build` or `npm run build`?

Guess: it might be on `preact build`

**Comment by timarney** [comment]
Via package.json npm scripts (npm run build)

running the npm script
`preact build` //fails

running the npm script (if I add --no-prerender)
`preact build --no-prerender` //success

When it tries to do the prerender I see

Build [==================  ] 91% (17.6s) additional asset

Fails at Template execution failed: Error: ENOENT: no such file or directory, 
src/~/domkit/builtinStyle.js (I don't know why this is trying to find this file in my src)

With the try catch from https://github.com/developit/preact-cli/commit/40778ac5f7c6fd47fef11ab7cb3a9ef8a7c0b28e it will catch the error.

**Comment by reznord** [comment]
Totally related to #310. Seems like domkit uses window somewhere. That is the reason why it is failing.
