### ISSUE TITLE
Importing `create-hmac` causes `process is not defined` error

### ISSUE THREAD

**Issue by rubencodes** [developit/preact-cli#244]
I'm using the `create-hmac` npm package in my `preact-cli` project, and it seems to be causing a runtime error: `Uncaught ReferenceError: process is not defined`. This happens even when building using the `--no-prerender` flag. I also tried changing the import into a `require` and wrapping it in `if(typeof window !== 'undefined')`, but this still caused the same error.

I've created a sample project to reproduce the issue that was generated by using the `preact create [project] --type=simple`, then importing the `create-hmac` package, which can be found [here](https://github.com/rubencodes/createHmacTest).

**Comment by lukeed** [comment]
Not sure how to approach this; but this is why it's happening:

* Set `target: 'node'` [here](https://github.com/developit/preact-cli/blob/master/src/lib/webpack/webpack-server-config.js#L22-L24) for prerendering
* Doing so changes Webpack's [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolve-mainfields) value

I don't think we can/should add "browser" fields when targetting node directly. Would likely be a mess. Also dont think user can customize the `prerender` config.

@rubencodes For now, I would suggest importing the `create-hmac/browser` file directly.

**Comment by rubencodes** [comment]
Thanks for the suggestions! I'll try this out and report back.

**Comment by rubencodes** [comment]
So, the `create-hmac/browser` file imports the `cipher-base` package which is what uses the `process` variable, so I might be outta luck for now. :/

**Comment by developit** [comment]
It's strange though - I think @rubencodes was seeing the error at runtime?

**Comment by lukeed** [comment]
Ah, bummer!

Another thing you can try is modifying your webpack config to add the following:

```js
{
  node: {
    process: 'mock'
  }
}
```

Since we're setting `node` as the target, webpack sets `process:true` by default, which assumes native.

Just a guess, but it's all I can think of.

**Comment by rubencodes** [comment]
@developit Yeah it compiles fine, but (for example) if I put the require within a function, it errors on the execution.

@lukeed That seems to do the trick!!

**Comment by lukeed** [comment]
@rubencodes Do you think this is okay to close?

**Comment by rubencodes** [comment]
Yes, okay to close. 🙂 Thanks for your help!

**Comment by developit** [comment]
@lukeed I wonder what the overhead would be for us to switch to process:mock by default...

**Comment by lukeed** [comment]
@developit I have a screenshot over in https://github.com/developit/preact-compat/issues/403

The browser mock is less than 1kb gzip, but will always be there, regardless of using it or not.

**Comment by developit** [comment]
I think there are a few people running into this. Maybe we should at least drop an empty object into the build as a `process` global?
