### ISSUE TITLE
Interactive `preact create` command

### ISSUE THREAD

**Issue by reznord** [developit/preact-cli#248]
Tagging this issue as discussion so I can get opinion on having an interactive `preact create` for initializing the project using `preact-cli`.

If we want to use interactive `preact create` i.e. `preact init` there will not be any flags. Which in my opinion is awesome. 😄 

All the flags in the current `preact create` command will be prompted as questions to the user.

**Comment by SaraVieira** [comment]
I really like this idea! 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by prateekbh** [comment]
Please still keep `--default` flag, like `npm init -y`

**Comment by reznord** [comment]
Sure, default flag is a must :D
