### ISSUE TITLE
Support something akin to `getInitialProps` on App component

### ISSUE THREAD

**Issue by ajoslin** [developit/preact-cli#249]
Ideally, similar to Next.js, each route could define a function that returns a Promise, which will defer prerendering until it resolves. This allows components to fetch their initial data (eg from a CMS) before prerender happens.

I'd love to open a PR supporting this. I went through the code to see how I would implement it, and I have a couple of questions.

Currently, an ssr function [is defined in the html-webpack-plugin config](https://github.com/developit/preact-cli/blob/364906e707d5df3cbfc45c8ab9e10902f410da77/src/lib/webpack/webpack-client-config.js#L223-L225). The problem with the ssr happening here, as part of the webpack plugin's template step, is that it must be synchronous. Is there any good reason it's defined here? It looks like the `ssr` function does take parameters, but they aren't used in any meaningful way.

Instead, I'd like to do the "SSR" *before* html-webpack-plugin runs so that we can asynchronously render the Preact app, and then just store the SSR result as a string in the html-webpack-plugin config, which the webpack plugin can then spit into its template as a variable.

And then we could do the SSR somewhere else, but I'm not sure where would be best. I'm thinking where the list of prerender urls are defined.

Does my suggestion sound like the correct way to implement this, and if so, do you have any pointers about which part of the prerender lifecycle in which to implement the async SSR step?

**Comment by ajoslin** [comment]
In the long run, it would be best to have `getInitialProps` on each component rendered by the `Router`, but that would require preact-cli to be able to get the component matching the current route. I've heard that this functionality is in the works (?), but that sounds like a later step anyway. We can get basic `getInitialProps` on the App component with async prerendering, that's most of the work done.

**Comment by developit** [comment]
I'd be up for moving ssr out of the template. String rendering is still synchronous though, if we wanted to support something like getInitialProps I think we'd need to switch to something like [preact-render-to-vdom](https://github.com/ezekielchentnik/preact-render-to-vdom) and then have preact-cli inject code into the router to invoke and re-render in response to getInitialProps().

**Comment by ajoslin** [comment]
Sounds way more complicated. Couldn't we technically just do it on the top-level component only (since we already have an instance of that) and let the application handle the orchestration?

**Comment by krokofant** [comment]
This would be awesome. Did this hit a stand-still?
