### ISSUE TITLE
components directory rename - css not rendering

### ISSUE THREAD

**Issue by ekanna** [developit/preact-cli#250]
I have renamed ```components``` directory to ```pods```, only javascript part of component is working. Component css is not rendering.

**Comment by lukeed** [comment]
Hi! We only have `components` and `routes` directories mapped for CSS. You can see that [here](https://github.com/developit/preact-cli/blob/master/src/lib/webpack/webpack-base-config.js#L177-L195).

You'd have to revert the rename, or [customize your webpack](https://github.com/developit/preact-cli#webpack) to include the new name of your directory.

**Comment by yavorski** [comment]
Maybe change to `src('./')` and not limit to specific folders?

**Comment by developit** [comment]
Cant - people use `src/style/foo.css` and expect it to not be CSS modules.  The current setup basically assumes that if you put CSS files in `src/components/*`, you'll want them to be modular - I feel like that's a decent best-guess.  

The custom config option @lukeed suggested seems like the best option here:

```js
// preact.config.js
export default (config, env, helpers) => {
  helpers.getRulesByMatchingFile(config, '*.css').forEach( ({ rule }) => {
    let filter = (rule.include || rule.exclude);
    for (let i=filter.length; i--; ) {
      filter[i] = filter[i].replace('/components/', '/pods/');
    }
  });
};
```

**Comment by ekanna** [comment]
Hi, Thank you all. I posted here as JS part of the component is working and css part is not working. So i thought it may be a bug. Thank you for the prompt response.
