### ISSUE TITLE
How do I modify SW config?

### ISSUE THREAD

**Issue by gidztech** [developit/preact-cli#255]
I created an app using the CLI tool, which is super cool. However, there's a ton of config I cannot access. In my case, I have a link on my website to `/blog` on my server, which is running on a Ghost instance. My Nginx config would normally use `proxy_pass` here. But, when the service worker runs, I cannot get to that server. 

Is there any way to configure this?

**Update:**
There's some discussion [here](https://github.com/GoogleChrome/sw-precache/issues/97) about creating a `staticFileGlobsIgnores` option to `sw-precache`, so perhaps it's not something this team can fix unless someone knows a workaround. I assume I'd be able to configure that library by creating `preact.config.js` to override the `webpack-client-config.js`?

**Comment by prateekbh** [comment]
Hi! I was just about to add this to wiki plugin.md
you can use this plugin to do so

https://github.com/prateekbh/preact-cli-sw-precache

**Comment by prateekbh** [comment]
added https://github.com/developit/preact-cli/wiki/Plugins :)

**Comment by gidztech** [comment]
Thanks for the plugin. Do you know how I would configure it to not fetch using the service worker for a particular URI path? I've not managed to work it out and so far the only way I can do it is to hack the generated `sw.js` file to ignore a path on the `fetch` event.

**Comment by prateekbh** [comment]
@gidztech I guess you can use a `networkOnly` strategy with `runtimeStrategies`.
