### ISSUE TITLE
Issue with npm i -g preact-cli

### ISSUE THREAD

**Issue by rafael-ochoa** [developit/preact-cli#267]
hello,
I apologize for opening an issue, I could not find anything similar. I've been trying to install this package with no success.
Different issues with webpack-blocks. I even have tried to install webpack-blocks and all its blocks independently, building the code but there is always a blocker on webpack-blocks.
I've used npm@5.3.0 and yarn@0.27.5 running on node@8.1.3 Mac OS 10.12.5, Go@1.8.3

**npm error:**
```
npm ERR! code E404
npm ERR! 404 Not Found: @webpack-blocks/css-modules@^0.4.0
```
**yarn error**
```
[1/4] Resolving packages...
error Couldn't find package "@webpack-blocks/css-modules" on the "npm" registry.
```
I also tried cleaning cache for npm and yarn. 
Please let me know.
Thanks in advance

**Comment by SaraVieira** [comment]
@rafael-ochoa I can verify that is true on yarn still trying to figure out why.

About NPM 5.0.3 there have been some problems with it in terms of cache you can see some here : https://github.com/electron-userland/electron-forge/issues/266 and I had this issue yesterday installing a new project and I don't think there is a fix yet

I trully believe this is a npm issue 😢

**Comment by reznord** [comment]
umm....I'm not really sure. I am on the same config as @rafael-ochoa. It works for both `yarn` as well as `npm` for me.

node: 8.1.4
npm: 5.3.0
macOS: 10.12.6
yarn: 0.27.5

**Comment by SaraVieira** [comment]
Yarn never worked for me 😢

**Comment by reznord** [comment]
We have removed from `@webpack-blocks` in favor of `webpack3`. 

You can track it [here](https://github.com/developit/preact-cli/pull/150).

**Comment by reznord** [comment]
whooops! sorry wrong button pressed.

**Comment by reznord** [comment]
In the next version we are moving from webpack-blocks completely and this is an npm issue, so closing this.
