### ISSUE TITLE
migrating create-react-app apps to preact-cli

### ISSUE THREAD

**Issue by jojo05** [developit/preact-cli#270]
With cra, I use the following config in package.json 

proxy: "http://localhost:6300" 
homepage: "/MyPath/" 

The first option allows me to test the app with a local server and  the second option allows me to use a specific server path for my  production build. 

Will these be available in an upcoming release?

**Comment by reznord** [comment]
Regarding `homepage` there is already an issue open. You can refer #218 for that. 

And regarding proxy, there are no plans as of now.

Regarding the title for the issue - I'm not really sure what do you mean by `migrating create-react-app to preact-cli`. Can you explain?

**Comment by reznord** [comment]
Regarding the proxy, you can use `npm run serve` which executes `preact watch` command.

**Comment by jojo05** [comment]
With the title, I meant:
Make it easy to migrate apps started with create-react-app to apps developed with preact-cli

Yes, I had seen issue #218.  I think it's important to keep the same config options as in create-react-app to make it easy to develop with both cra and prect-cli

`npm run serve` lets me pick host and port for the Node server but I am using a separate Go server

**Comment by lukeed** [comment]
Unless I'm mistaken, sounds like just need to add a [`proxy`](https://webpack.js.org/configuration/dev-server/#devserver-proxy) key to webpack config.

**Comment by reznord** [comment]
Yes, when `proxy` is specified,  we need to consider it as a BASE for API calls.

**Comment by developit** [comment]
Yup, this would be very useful.  I'm not sure the behavior of CRA when a String is specified is actually workable - it's kindof a guess and does't combine well with `historyApiFallback` ([here's the source](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/WebpackDevServerUtils.js#L287)).  They do support passing a custom proxy configuration object though, which is just passed directly to WebpackDevServer's `proxy` option.  I'm fine emulating both but recommending the latter.

**Comment by fokusferit** [comment]
If no one is working yet, I'd like to start working on this feature as in the short-term there might be a need for my own application anyway.
