### ISSUE TITLE
optimal setup for web pages

### ISSUE THREAD

**Issue by jojo05** [developit/preact-cli#276]
One area where I find preact could be really useful is for replacing jQuery code in web pages, e.g. autocomplete, image gallery, ...

How can I create a bundle where I omit some preact components  ? 

These components would be included with a script tag, so that the bundle is as small as possible and these components get cached once across the website.

Does this make sense?

**Comment by thangngoc89** [comment]
I never try this but hrer is the ideas:
- You bundle your components as UMD bundle. 
- Tell webpack to load your components (which is avaiable in window scope)

You may want to check ou https://openit.io/preact-habitat 

IMHO: unless you have many websites with the same user base, the effort doesn't worth it

**Comment by jojo05** [comment]
Yes, preact-habitat seems to be one solution.

Can you explain "many websites with the same user base" 

I am saying preact-cli could be a mechanism to replace some jQuery code bundles and optionally future proof the code to a PWA

**Comment by zouhir** [comment]
Hey @jojo05 yes, you can certainly do that. build 1 Preact component, let's say a modal, a login widget or an auto complete and share it across your CMSs or even non-preact websites as plugins.

Please check out the links below for your inspiration and always feel free to ask me anything

- *Simple Login* 🔑 [link](https://preact-habitat-inline.netlify.com/)

- *Youtube Players* ▶️ [link](https://preact-habitat-youtube.netlify.com/)

**Comment by thangngoc89** [comment]
@jojo05 "many websites with the same user base" means
unless your component is as popular as jQuery, the chance of the component is already in cache is very small.

**Comment by jojo05** [comment]
Ok, I understand now. 
The use case I am interested is caching across multiple web pages of a single website, i.e. loading the big components once and using them slightly differently in separate web pages

**Comment by thangngoc89** [comment]
@jojo05 well then, you can use Webpack to automatically do it for you ;). Create a seperate chunk for each "big components".

**Comment by jojo05** [comment]
Not sure I understand. 
Let's say I use a preact autocomplete component and an image gallery, and some pages use page both and some use each separately. Then, I want the two components separately as script tags. 
The logic that drives the components is what I want to understand, and this is what preact-habitat does, isn't it?

**Comment by zouhir** [comment]
If you're building the whole website using a modern JavaScript stack, with ES6 modules and or Preact and etc.. then preact-habitat is *not* my recommendation. I would do what probably @thangngoc89 have advised. Importing the module as an extension ES dependency and webpack will include it in the routes and pages that will use it.

But, if you're working with a Website that has not been built very recently, then you can probably generate scripts with habitats and embed them in your pages as portable components.

I still think there's a missing peace, can you tell us what stack you have and what you exactly aiming to do?

**Comment by jojo05** [comment]
My use case is the second one:

- static html with js scripts
- dynamic html (server generated) with js scripts

I think this stack (or very similar) is used by most large websites today.

**Comment by zouhir** [comment]
that's the case at my employers large Adobe CMS website, so we build widgets in Preact and mount them in the DOM using `preact-habitat` which was the reason of why I built habitat at first place

**Comment by jojo05** [comment]
Then, if this functionality were available in preact-cli, I could be widely useful (b/c most (p)react users pick create-react-app or preact-cli instead of more specific tools

**Comment by zouhir** [comment]
I am more than happy to contribute with such an option to the CLI which would benefit everyone, but not sure it fits within the vision or the goal of this tool.

looping: @developit @lukeed @reznord @rkostrzewski

**Comment by jojo05** [comment]
The PWA vision or goals may be clear, 
but ...
there is a huge installed base of websites using JS that don't have a clear way forward (in terms of using modern JS)  and Preact with preact-cli could fill that role.
This would also make Preact stance vs React a lot more clear. The web tools (jQuery, ...) have always been about optimizing size and Preact delivers on that (very different to cross-platform which has always been nirvana, and reminds me of Java)

Just one opinion!
