### ISSUE TITLE
Issue with openlayers

### ISSUE THREAD

**Issue by otarvainen** [developit/preact-cli#282]
Hi,

I'm having issues using openlayers with preact-cli.

Backgrounds:

Operating system: macOS
node -v v8.2.1
npm -v  5.3.0

When I add the openlayers library with npm
`npm install --save openlayers`

... and try to use it anywhere my application
`import ol from 'openlayers'`

... and start development server with
`preact watch`

Build process just hangs for maybe 30 minutes until it finishes. At the same time node process seems to take 100% of CPU when checking with top.

`Build [==                  ] 10% (0.0s) building modules`

I don't think this is an issue with openlayers library since I'm able to use it with create-react-app, and it builds pretty much instantly. Is there a way to debug the build process with preact-cli?

**Comment by reznord** [comment]
Umm.....I'm not really sure what the issue is, it is taking really long time to install the package and I'm not sure how to debug that as well.

Can you provide a bit more information about this?

**Comment by otarvainen** [comment]
Sorry if it was unclear.

Installing openlayers package is not a problem, but starting the development server seems to take forever.

Steps to reproduce:

`preact create ol-test`
`cd ol-test`
`preact watch`

The development servers starts rather instantly at this point. But after trying to use openlayers.

`npm install --save openlayers`

Then import the openlayers library for example in src/components/app.js

`import ol from 'openlayers';`

...and then start the development server again

`preact watch`

...at this point it is getting stuck. So, I was asking that is there a way to debug this, to see what's taking so long.

**Comment by reznord** [comment]
I'm not really sure what is happening, I tried with DEBUG enabled too, but still no result.

Does `[ol](https://www.npmjs.com/package/ol)` satisfy your needs? It is the minified version of `openlayers`.

**Comment by otarvainen** [comment]
Unfortunately, there seems to be the same issue when trying to use the minified ol version.

**Comment by reznord** [comment]
@otarvainen I tried the same with `ol`, it is working fine for me.

Did you uninstall the `openlayers` and the imports are a bit different: 

```
import Map from 'ol/map';
```

**Comment by otarvainen** [comment]
Thanks for the help.

I can confirm it's working also for me. I setup a new project, installed ol-package and tested the sample setup from [ol](https://www.npmjs.com/package/ol
)

Still wondering why is the default library so slow. I have used it before with create-react-app with no problems.

**Comment by reznord** [comment]
Well, if you observe, it is not just the default library which is super slow, when you build the package with `ol` library also, it takes a noticeable amount of time.
