### ISSUE TITLE
FAQs in the WiKi section?

### ISSUE THREAD

**Issue by reznord** [developit/preact-cli#285]
So, right now there are a lot of basic questions which users have. It would be great to have a wiki page for the FAQs.

Any suggestions?

**Comment by SaraVieira** [comment]
@reznord This sounds great , I can look through the issues and see what issues are the most common and fixable to add there , that sound good ? 😄

**Comment by lukeed** [comment]
First thoughts: Custom Templating, Customizing Webpack

Even though both those are in the README, might want to rip out all "How-Tos" from there & point to this new Wiki section instead, along with the existing Recipes section.

**Comment by reznord** [comment]
@SaraVieira Totally, sounds great.

Another thing, we need to mention that is *Master branch is for development purposes.*

**Comment by lukeed** [comment]
@reznord Agreed, that should go at the top of Readme imo. Seen that pop up 2 or 3 times.

**Comment by joshuataylor** [comment]
Yeah, I am just starting with preact (with basic experience with react, and basic experience with the javascript ecosystem), and have a load of newbie questions, and would love to see something like this added.

I'll be happy to add to it as well, as my experiences would be pretty common, I think.

**Comment by reznord** [comment]
Sure, that would be great.

Go ahead and create a page in Wiki Section :)

**Comment by thangngoc89** [comment]
@joshuataylor that would be great. We can answer but we don't know the question

**Comment by joshuataylor** [comment]
@thangngoc89 I meant more like I would document my experiences and pitfalls I find to help others :).

**Comment by thangngoc89** [comment]
@joshuataylor I create a page for it. And that would even more awesome

**Comment by SaraVieira** [comment]
Hello guys! I'll go through the issues today and send them through slack because I can't edit the wiki pages 🙁

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thangngoc89** [comment]
Hey @developit,

If you have time, could you go to project setting and uncheck **Restrict to collaborators only?** 

![image](https://user-images.githubusercontent.com/3049054/28996534-bf21d4d8-7a2c-11e7-9e11-f91826061b06.png)

**Comment by reznord** [comment]
> If you have time, could you go to project setting and uncheck Restrict to collaborators only

Just sharing my 2 cents tho, We can but that might be a problem in the future since the Wiki is open to public and anyone can come down and write any sort of stuff they want.

**Comment by thangngoc89** [comment]
@reznord If no one can edit the Wiki then we should move Wiki back to the repo and accept editing via PR? Even though wiki is a repo itself, there is no UI for sending PR

**Comment by lukeed** [comment]
We can add a `docs` folder (or its own repo) and modify `preact-www` to serve that on the site under a Preact CLI section.

Pointing to https://github.com/developit/preact-www/issues/152 because it falls inline with this approach.

**Comment by skaraman** [comment]
I have a question that might fall into FAQ - How to set node config in preact.config.js? I have a module that i'm importing that needs `process` and `Buffer` set to `'mock'`

**Comment by lukeed** [comment]
@skaraman You can just modify the webpack config directly inside your `preact.config.js`:

```js
export default (config, env) => {
  config.node = {
    process: 'mock'
  }
}
```

See https://github.com/developit/preact-cli/issues/244#issuecomment-316558813 and [Wiki](https://github.com/developit/preact-cli/wiki/Config-Recipes#setting-proxy-for-dev-server-using-config-directly) for reference.

**Comment by SaraVieira** [comment]
@lukeed @reznord I made a gist with the questions I found that already fixable : https://gist.github.com/SaraVieira/ab76cd4258a1e77c75829c6b38aa2ab1

**Comment by SaraVieira** [comment]
updated the gist so that it's waaaay more readable

**Comment by thangngoc89** [comment]
@SaraVieira 

> The Readme in Github and NPM

It's not right. npm readme is always the up-to-date version of preact-cli. Only Github master README is not released yet.

**Comment by SaraVieira** [comment]
@thangngoc89 True !
Updated the gist:
https://gist.github.com/SaraVieira/ab76cd4258a1e77c75829c6b38aa2ab1

**Comment by reznord** [comment]
Regarding #309 it would be great to add a snippet on how one can extend the webpack config using `preact.config.js` for classnames support in various folders (other than `routes` & `components`).

**Comment by skaraman** [comment]
more on config, how can one configure a custom loader like https://github.com/kossnocorp/defile#configuration

**Comment by developit** [comment]
You can install or define your own loaders same as any webpack project:

```js
// preact.config.js
import path from 'path';

export default (config) => {
  let myCustomLoader = path.resolve(__dirname, 'path/to/my-custom-loader.js');

  // introduce the loader:
  config.resolveLoader.alias['my-custom-loader'] = myCustomLoader;
};
```

Then use it like so:

```js
import foo from 'my-custom-loader!./foo';
```

**Comment by reznord** [comment]
Added the FAQs in the wiki, please feel free to drop any other common questions that needs to be answered.

A huge thanks to @SaraVieira
