### ISSUE TITLE
Error: Exited with status  4294963241

### ISSUE THREAD

**Issue by Biarity** [developit/preact-cli#287]
I keep getting the error (3 times in a row now!):
```
| Installing dev dependenciesError: Exited with status 4294963241
```

Not sure why. Might be somehow related to #202.

**Comment by thangngoc89** [comment]
@Biarity Hey could you tell us how to reproduce this issue? Also your node, npm/yarn version and OS?

**Comment by Biarity** [comment]
I just get this after installing preact via npm then running `preact create example`.
OS: Windows 10 1703.
npm version: 3.10.8.
node version: v6.9.1.
Sorry I don't have more information!

**Comment by reznord** [comment]
Can you give this a try and see if it works? https://github.com/developit/preact-cli/issues/304#issuecomment-321979782
