### ISSUE TITLE
Feature Requests for CLI?

### ISSUE THREAD

**Issue by reznord** [developit/preact-cli#289]
This is a list of features which we thought of having in `cli`.

- [x] Custom templating
- [ ] Tests
- [ ] Complete SSR Support
- [x] CORS Support

Feel free to add any more features which you want to see in `preact-cli`

**Comment by guido4000** [comment]
How about redux and typescript as optional features?

**Comment by reznord** [comment]
Typescript is available as a plugin. You can check out https://github.com/developit/preact-cli/wiki/Plugins for the available plugins.

Coming to redux, it would be more like forcing the user. That can't be called a feature :P

**Comment by SaraVieira** [comment]
Hello @guido4000 .

As for typescript there is a plugin for that  https://github.com/wub/preact-cli-plugin-typescript thanks to @wub 🎉

For redux I think that should be up to you to decide, in my case I perfer mobx and I think adding redux integration would cause a lot of these preference issues. 
What do you think @reznord? 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by reznord** [comment]
> in my case I perfer mobx and I think adding redux integration would cause a lot of these preference issues.

totally.

**Comment by SaraVieira** [comment]
Can I work on a PR for tests? Using jest and snapshots? @reznord 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by guido4000** [comment]
@reznord @SaraVieira 
Great, I did not see the Typescript plugin before.

**Comment by reznord** [comment]
We thought of going with plugins since we just want to keep the cli as minimal and clean.

And the advantage with plugins is, you can add any no of plugins you want.

**Comment by developit** [comment]
Another one: option to disable automatic clearing of console on successful builds (from developit/preact#805). /cc @HadrienPierart

**Comment by reznord** [comment]
too many flags! lol

**Comment by developit** [comment]
Could be a config option, plugin or recipe. Maybe the latter.

**Comment by reznord** [comment]
It is just a clearConsole function that does this. If you remove that, you are good to go 😄

**Comment by lukeed** [comment]
Re: Clearing Console~

My `console-clear` has a [`keepHistory` option](https://github.com/lukeed/console-clear#clearkeephistory) that will "soft clear" the console. The new content will appear at the top, as if it's been wiped, but the history is still preserved & accessible via scrolling.

Perhaps we should use that by default? Best of both worlds, and no need for conditional logic.

**Comment by nerijusgood** [comment]
This is minor, but maybe we could add [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) ? This adds really nice overview over a bunch of things.

**Comment by fokusferit** [comment]
As I'm not sure if people see the PR reference:

Based on a Gist I shared in another Issue I've created a PR for Tests https://github.com/preactjs-templates/default/pull/10 , it is about some Jest configuration + as an example using preact-render-spy.

**Comment by developit** [comment]
For dashboard we could have a `--dashboard` flag that attempts to use webpack-dashboard but doesn't auto-install it.
