### ISSUE TITLE
Require in lib/entry.js causes ModuleConcatenation bailout

### ISSUE THREAD

**Issue by kurtextrem** [developit/preact-cli#290]
When using webpacks `webpack.optimize.ModuleConcatenationPlugin()`, the cjs require in https://github.com/developit/preact-cli/blob/master/src/lib/entry.js#L20 https://github.com/developit/preact-cli/blob/master/src/lib/entry.js#L14 causes a bailout of the plugin, with the reason "(referenced with cjs require)".
I'm unsure why that require is needed? (I'm also unsure why `interopDefault` is needed, it seems to work for me without)

Webpacks HMR hot-reloads `import`ed scripts without re-requiring them. So the following lines work:
```javascript
import App from './components/App'
import Preact, { h, options, render } from 'preact'

options.syncComponentUpdates = false

let root = document.body.firstChild

const init = app => (root = render(h(app), document.body, root))

if (module.hot) {
	require('preact/devtools')
	const { whyDidYouUpdate } = require('why-did-you-update')
	whyDidYouUpdate(Preact)

	module.hot.accept('./components/App', () =>
		requestAnimationFrame(() => {
			init(App)
		})
	)
}

init(App)
```

See also here: https://webpack.js.org/guides/hot-module-replacement/#enabling-hmr (index.js)

If wanted I can do a PR to adjust `entry.js`, just wanting to discuss here first if I'm overlooking something.

**Comment by kurtextrem** [comment]
By the way, the win isn't too big (at least for me), but "why not":
Before:
![luzqivb7s7inueefzkadhq](https://user-images.githubusercontent.com/502146/29001636-14be32fc-7a90-11e7-94fa-8382e768a810.png)

After:
![l1jz1d3psumgwktehegfgq](https://user-images.githubusercontent.com/502146/29001637-20b12c04-7a90-11e7-8674-a30337bfeb97.png)

**Comment by reznord** [comment]
I think this is fixed in the next version of preact-cli

/cc @lukeed

**Comment by developit** [comment]
Heads up - that modification would break HMR. The require needs to be re-invoked within the `module.hot.accept()` callback.

**Comment by kurtextrem** [comment]
@developit According to the webpack docs it doesn't need to. Webpack's HMR auto-rerequires it seems (see https://webpack.js.org/guides/hot-module-replacement/#enabling-hmr index.js)
