### ISSUE TITLE
Replace progress-bar-webpack-plugin with webpack-simple-progress-plugin

### ISSUE THREAD

**Issue by kurtextrem** [developit/preact-cli#291]
`webpack-simple-progress-plugin` has slightly more up to date deps and is almost half the gzipped size.
Apart from that they're practically the same.

See: 
https://cost-of-modules.herokuapp.com/?p=webpack-simple-progress-plugin@0.0.2
https://cost-of-modules.herokuapp.com/?p=progress-bar-webpack-plugin@1.10.0

(I can do a PR if wanted)

**Comment by thangngoc89** [comment]
@kurtextrem I'm not sure why are you obsessed with the size of it plugin? It's run on Node so the size doesn't matter that much. 

For your first point, the deps between the two of them is extractly them same considering semver

```
"dependencies": {
    "chalk": "^1.1.1",
    "object.assign": "^4.0.1",
    "progress": "^1.1.8"
  },
  "peerDependencies": {
    "webpack": "^1.3.0 || ^2 || ^3"
  }
```

Vs:

```
"dependencies": {
    "chalk": "^1.1.3",
    "object-assign": "^4.1.0",
    "progress": "^1.1.8"
  },
  "peerDependencies": {
    "webpack": "^1.3.0 || ^2.1.0-beta || ^3.0.0"
  }
```

**Comment by kurtextrem** [comment]
Well, what would be the counter arguments? webpack-simple-progress-plugin just seems superior (and there are people that install preact-cli on a plane - they surely appreciate less download time :P).

**Comment by developit** [comment]
I kinda like the progress bar of webpack-simple-progress-plugin better. Anyone feel the same?

**Comment by kurtextrem** [comment]
Doesn't preact-cli use its own template for the bar? Both support templates

Am 21.08.2017 20:12 schrieb "Jason Miller" <notifications@github.com>:

**Comment by reznord** [comment]
when did I close this issue? damn! my bad

**Comment by reznord** [comment]
@kurtextrem please open a PR. Happy to merge this one 😄
