### ISSUE TITLE
Disable PWA option?

### ISSUE THREAD

**Issue by jacobhummel** [developit/preact-cli#293]
Very impressed with preact-cli. Looking for the right way that I could disable the service worker generation? 

I am using this to build a very minimal UI component that can be dropped in to other apps, so I don't want to force them to require support for it.

Thanks for any info.

**Comment by reznord** [comment]
This defies the whole purpose of `preact-cli`. 

If you really want to create minimal UI components, I'd recommend using [nwb](https://github.com/insin/nwb).

**Comment by jacobhummel** [comment]
@reznord Sounds good. Thanks for the insight!

**Comment by reznord** [comment]
You can create `preact` apps too using nwb :smile:
