### ISSUE TITLE
Minimum requirements in README?

### ISSUE THREAD

**Issue by reznord** [developit/preact-cli#294]
We don't specify the minimum requirements required for `preact-cli` anywhere in the `README`. 

Right now, the only way a user can come to know is, after installing `node_modules` when the `check.js` gets triggered.

Will it be worth adding the requirements to the `README` (probably on the top) 
or
Find a badge which can specify the minimum `node version`?

**Comment by lukeed** [comment]
Don't think we need to. It's declared in our `engines` and in `.travis.yml` ...  and we throw early via your `check.js`.

**Comment by reznord** [comment]
I feel that we have to move the check.js from `postinstall` script to `preinstall` script. What do you think?

**Comment by thangngoc89** [comment]
@reznord How about we run the check everytime user run the cli? And exit immediately if the requirements don't pass. Since the cost of the operation is very small, it doesn't matter

**Comment by reznord** [comment]
We are currently! [here](https://github.com/developit/preact-cli/blob/master/src/index.js#L16)

**Comment by reznord** [comment]
Since we are using `chalk` we can't do it in `postinstall` script.
