### ISSUE TITLE
Styled Components & Preact CLI appears to drop styles

### ISSUE THREAD

**Issue by BTheunissen** [developit/preact-cli#296]
Hi all, 

I'm currently working on a small project with the CLI and was curious if I could get [styled components](https://github.com/styled-components/styled-components) in without pulling teeth. My current CLI config includes LESS and it appears that the styles are not being directly attached to my elements when I build and serve the dev server.

Keen to look into this when I get more time, has anyone else had much luck/trouble trying to use styled components?

**Comment by SaraVieira** [comment]
Hello @BTheunissen,

I use the cli with styled-components and it has worked great.
You can see my setup here: https://github.com/SaraVieira/styled-loaders/tree/master/packages/styled-loaders-preact

**Comment by SaraVieira** [comment]
Can you explain the issue ?

**Comment by BTheunissen** [comment]
Thanks for the quick response @SaraVieira! I had a quick play around and in my sleep deprived state I didn't realise I was starting all of my component names in my example with lower case letters. As such the elements appeared to render fine but were effectively just empty divs 😓

Awesome job to the Preact and CLI team as I wasn't expecting integrating styled components to be so simple!

**Comment by SaraVieira** [comment]
No problem @BTheunissen !

It's actually dead easy , I was pretty suprised too 😄
