### ISSUE TITLE
socks-js errors on fresh install

### ISSUE THREAD

**Issue by skaraman** [developit/preact-cli#297]
<img width="1920" alt="screen shot 2017-08-08 at 10 01 43 am" src="https://user-images.githubusercontent.com/2840020/29084403-ba60bafe-7c20-11e7-8385-00efb1ba9dfe.png">

I'm getting tons of errors after a fresh install just doing `preact create my-project`

**Comment by reznord** [comment]
@skaraman can you give us more info on how to reproduce this issue?

It would be great if you can provide your `node version` too.

**Comment by skaraman** [comment]
I just installed preact-cli `npm i -g preact-cli`
then create a new project `preact create anything`
then cd and `npm start`
`npm version` output:
{ anything: '1.0.0',
  npm: '5.3.0',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.2',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.98',
  zlib: '1.2.11' }

**Comment by skaraman** [comment]
i tried node 8.2.1 and it produces the same results, also as a side note -
the preact-boilerplate has the same issues with the latest code
i have an older version of the boilerplate (I don't know which one) that does not have this issue, i'm currently developing in there while this problem persists

**Comment by reznord** [comment]
I tried with `node 6.10.2`, `node 8.4` and it was working fine for me without any problem. Not sure where the error was from.

Will see if I am able to reproduce this issue.

**Comment by thangngoc89** [comment]
Hey guys, If you're noticing, the hot - loading adress is `http://localhost:8080//...` (double slashes). It should be the issue. 

@skaraman could you try and access the URL in console message ? I mean after fixing the double slashes

**Comment by skaraman** [comment]
@thangngoc89 sorry but I don't know how to change that or what you mean by access the URL in console message...

but the number of slashes shouldn't matter, you can have many slashes as long as there are no spaces and it resolves to `/` ->  you can try it on any website 
<img width="605" alt="screen shot 2017-08-08 at 12 54 06 pm" src="https://user-images.githubusercontent.com/2840020/29091792-e705e7e2-7c38-11e7-82ca-ad187082d0e8.png">

**Comment by skaraman** [comment]
@thangngoc89 i just realized what you meant - I navigated to the URLs without the double entry slashes and here's what i see:

<img width="1920" alt="screen shot 2017-08-08 at 7 44 00 pm" src="https://user-images.githubusercontent.com/2840020/29103012-0028b7fc-7c72-11e7-9ce5-6dedfa8e3ce8.png">
<img width="1920" alt="screen shot 2017-08-08 at 7 43 37 pm" src="https://user-images.githubusercontent.com/2840020/29103013-002a7f38-7c72-11e7-86e0-e41af8baf551.png">
<img width="1920" alt="screen shot 2017-08-08 at 7 42 17 pm" src="https://user-images.githubusercontent.com/2840020/29103014-002d7864-7c72-11e7-9822-bcfc3161d7e6.png">



so the double slashes are definitely the problem

**Comment by reznord** [comment]
I am still not able to reproduce this issue: Not really sure what is happening in your case though:

<img width="1280" alt="screen shot 2017-08-09 at 11 00 58 am" src="https://user-images.githubusercontent.com/3415488/29106338-23ad09aa-7cf2-11e7-8220-30c2e84b9f65.png">

**Comment by skaraman** [comment]
I uninstalled preact-cli `npm uninstall -g preact-cli` 
and then tried to install it with sudo `sudo npm i -g preact-cli`
and i got this error
![screen shot 2017-08-09 at 9 34 56 am](https://user-images.githubusercontent.com/2840020/29132890-85c8acd6-7ce6-11e7-9fe1-fb7f123dc8e2.jpg)

**Comment by skaraman** [comment]
I uninstalled and reinstalled preact-cli, seems to have fixed it...

**Comment by thangngoc89** [comment]
@skaraman 6.10.x is official supported and tested with every commits, still not sure what caused it
