### ISSUE TITLE
preact build fails without --no-prerender

### ISSUE THREAD

**Issue by RajeshBatth** [developit/preact-cli#299]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
preact build fails with following error

> 
> $ preact build
> Build [================== ] 91% (3.7s) additional asset processing
> Total precache size is about 193 kB for 17 resources.
> Template execution failed: Error: ENOENT: no such file or directory, open '/Users/Rajesh/rajesh/samples/bus-pwa-preact/src/~/invariant/invariant.js'
> Error: ENOENT: no such file or directory, open '/Users/Rajesh/rajesh/samples/bus-pwa-preact/src/~/invariant/invariant.js'
> 
> Error
> 
> prerender.js:69 handlePrerenderError
> [bus-pwa-preact]/[preact-cli]/lib/lib/webpack/prerender.js:69:33
> 
> prerender.js:52 prerender
> [bus-pwa-preact]/[preact-cli]/lib/lib/webpack/prerender.js:52:3
> 
> webpack-client-config.js:194 Object.ssr
> [bus-pwa-preact]/[preact-cli]/lib/lib/webpack/webpack-client-config.js:194:54
> 
> template.html:111 EM6I.module.exports
> [bus-pwa-preact]/[preact-cli]/lib/resources/template.html:111:37
> 
> index.js:264
> [bus-pwa-preact]/[html-webpack-plugin]/index.js:264:16
> 
> util.js:16 tryCatcher
> [bus-pwa-preact]/[html-webpack-plugin]/[bluebird]/js/release/util.js:16:23
> 
> promise.js:512 Promise._settlePromiseFromHandler
> [bus-pwa-preact]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:512:31
> 
> promise.js:569 Promise._settlePromise
> [bus-pwa-preact]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:569:18
> 
> promise.js:606 Promise._settlePromiseCtx
> [bus-pwa-preact]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:606:10
> 
> async.js:138 Async._drainQueue
> [bus-pwa-preact]/[html-webpack-plugin]/[bluebird]/js/release/async.js:138:12
> 
> async.js:143 Async._drainQueues
> [bus-pwa-preact]/[html-webpack-plugin]/[bluebird]/js/release/async.js:143:10
> 
> async.js:17 Immediate.Async.drainQueues
> [bus-pwa-preact]/[html-webpack-plugin]/[bluebird]/js/release/async.js:17:14
> 
> Build failed!
> error Command failed with exit code 1.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version : v6.10.2
- npm version: 3.10.10
- Operating system: macOS seirra 10.12.6 (16G29)

package.json: https://gist.github.com/RajeshBatth/4e619f17a5d3a3fe12f4559f301bf7d0

**Comment by reznord** [comment]
How can I reproduce this issue?

**Comment by RajeshBatth** [comment]
This was working before and I think it stopped working after I added react-router and redux.
Please give me some time, I'll create a project to verify the issue and will share it with you.

**Comment by thangngoc89** [comment]
@RajeshBatth if you added react-router, that's should be the problem. Because you're probably using BrowserHistory so it fails in Node enviroment

**Comment by reznord** [comment]
@RajeshBatth you have to use `preact-router`. `react-router` is not compatible with `preact-cli`.

**Comment by RajeshBatth** [comment]
Is there a official/recommened redux support library for preact-router ?

**Comment by reznord** [comment]
There shouldn't be much of a difference on how to use `preact-router` & `redux`.

**Comment by RajeshBatth** [comment]
Thanks @reznord , will try this

**Comment by RajeshBatth** [comment]
@reznord react-router support is in the roadmap of preact-cli ?

**Comment by reznord** [comment]
React router is specific to react and `preact-router` is specific to `preact`.

If you want to use router in `preact-cli`, you can use `preact-router`.

**Comment by RajeshBatth** [comment]
But the preact-router documentation says as long as the alias is present, react-router should be compatible
[Link](https://github.com/developit/preact-router#preact-router)

**Comment by thangngoc89** [comment]
@RajeshBatth yes, it works great with preact-compat. But preact-cli is built around preact-router and currently, there is no easy way to get prerender works with react-router without forking preact-cli itself. If you're interesting in making a PR to help it happens, I'll be more happy to guide/review/merge it

**Comment by RajeshBatth** [comment]
@thangngoc89 I'm only have intermediate skills in front-end dev, but still I would like to give it a try.
Can you briefly explain me what is the challenge in supporting react-router and prerender?

**Comment by thangngoc89** [comment]
@RajeshBatth you need to implement Static Router (https://reacttraining.com/react-router/core/api/StaticRouter) into prerender logic https://github.com/developit/preact-cli/blob/master/src/lib/webpack/prerender.js 

But I'm think about some kinds of abstraction that can let user write there own prerender logic.

**Comment by RajeshBatth** [comment]
thanks @thangngoc89, I'll take a dive into the src code.

**Comment by thangngoc89** [comment]
as you can see on this line https://github.com/developit/preact-cli/blob/2631fd7dee92b9147e196229c7568c04c7e6ab7d/src/lib/webpack/prerender.js#L13-L14

Preact-router is really simple, it only need history with href and pathname property available in global scope to work.

**Comment by rubencodes** [comment]
Any other packages that are known not to work with `preact-cli`? I don't use `react-router` but I'm getting a very similar error (identical stacktrace) when using `--prerender`.
