### ISSUE TITLE
Consider using .less files instead of .css files for default

### ISSUE THREAD

**Issue by scottmas** [developit/preact-cli#3]
Nice work! It gives me shivers of happiness to see that 20kb download size for a fully functional app. 

However, I just barely ran `preact create my-test-app` and it doesn't come with built in LESS support, just boring old .css files. Or is there a config to use LESS? Do you need to bump the NPM version? Since I see in your examples folder that LESS should be supported.

**Comment by scottmas** [comment]
My mistake. LESS files build just fine if you just change the extension. 

May be worth considering generating .less files by default though.

Although I know there is quite a bit of precedent for doing CSS files by default (React Create App, Angular CLI), I think that's the wrong decision. Lots of developers won't even know the CLI supports a CSS preprocessor, and rather than figure out that they can use a preprocessor, they just forge onward with raw css. This has actually happened to me before in an Angular CLI project I inherited. 

Less is pretty widely understood, and I just can't imagine any developer in their right mind wanting to write raw css.

**Comment by developit** [comment]
FWIW I'm a less user as well, but I don't want to push it on anyone. I can't remember if we have it in yet, but there is supposed to be a --less option in `create` that sets less up as the default. Same for sass.

**Comment by scottmas** [comment]
Good point. Documenting the flags on `create` probably is a better option. Is a better forward path for supporting sass or postcss.
