### ISSUE TITLE
401 when installing via npm

### ISSUE THREAD

**Issue by makenai** [developit/preact-cli#300]
```
~ ᐅ npm i -g preact-cli
npm ERR! code E401
npm ERR! 401 Unauthorized: @webpack-blocks/extract-text2@^0.4.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pawel/.npm/_logs/2017-08-09T18_00_36_754Z-debug.log
~ ᐅ npm --version     
5.3.0
~ ᐅ node --version     
v8.2.1
~ ᐅ uname -a
Darwin makenai.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by reznord** [comment]
@makenai Are you using npm with root privileges? I guess that is why you are getting the 401 error

**Comment by makenai** [comment]
@reznord Nope - I'm using it as my local user, but it's scoped to my home directory via nvm. I can install other stuff globally in the same shell with no issues:

```
~ ᐅ ws
zsh: command not found: ws
~ ᐅ npm install -g local-web-server
/Users/pawel/.nvm/versions/node/v8.2.1/bin/ws -> /Users/pawel/.nvm/versions/node/v8.2.1/lib/node_modules/local-web-server/bin/cli.js
+ local-web-server@2.2.3
added 171 packages in 10.254s
~ ᐅ ws
Serving at http://makenai.local:8000, http://127.0.0.1:8000, http://192.168.1.2:8000
```
It looks to me like the scoped npm repo for @webpack-blocks went private or something?

**Comment by makenai** [comment]
Not sure what the actual issue was, but I was able to get it to install by moving '~/.nvmrc' that contained my email address and auth info. Possibly it was using some older format or there was an actual block on my specifically ('ouch!' if true). 'npm logout' did not work.
