### ISSUE TITLE
Wiki: Config Recipes example code error

### ISSUE THREAD

**Issue by molily** [developit/preact-cli#302]
Hi there, thanks for this great project!

I believe this section’s example code has a tiny error:

https://github.com/developit/preact-cli/wiki/Config-Recipes#customising-babel-options-using-loader-helpers

```js
let { rule } = helpers.getLoadersByName(config, 'babel-loader');
```

getLoader**s**ByName (plural) returns an array, so the first (and only) loader needs to be obtained with:

```js
let { rule } = helpers.getLoadersByName(config, 'babel-loader')[0];
```

(or similar)

The subsequent getLoadersByName example uses `[0]` as well:

https://github.com/developit/preact-cli/wiki/Config-Recipes#disabling-source-maps-using-plugin-helpers

Thanks!

**Comment by reznord** [comment]
Hey,

Thanks for pointing the issue in the wiki. you are right it returns an array and I've changed it. 

Reference: https://github.com/developit/preact-cli/wiki/Config-Recipes#customising-babel-options-using-loader-helpers
