### ISSUE TITLE
preact init command not working

### ISSUE THREAD

**Issue by anubhav7495** [developit/preact-cli#307]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`preact init` command doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
step 1: npm install preact-cli -g
step 2: preact init
```

**What is the expected behavior?**
preact init command should interactively ask for app initialization options.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version `v6.10.0`
- npm version `v5.3.0`
- Operating system `Ubuntu 16.04LTS`

**Comment by reznord** [comment]
@anubhav7495 `master` branch is for development purposes. Please go through the `readme`. 

`preact init` command will be available in the next release.

**Comment by anubhav7495** [comment]
Ah! My bad. 
Awesome turnaround time man.
Cheers.
