### ISSUE TITLE
Classnames not generated on other filestructure

### ISSUE THREAD

**Issue by rijkvanzanten** [developit/preact-cli#309]
**Do you want to request a *feature* or report a *bug*?**
A bug (or missing documentation if this is expected)

**What is the current behavior?**
If I create a component that is not in the "default" folders (`component`/`routes`) Webpack won't generate a classname on import of a sass file.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a new Preact app with `preact create testProject --sass`
2. Move the `header` component from `/src/components/header` to `/src/header` and change the reference in the app component*
3. The styling is broken as there isn't any classname generated

*You could also create a custom components directory and move it there. Something like `/src/sections/header` instead of the regular `/src/components/header`

**What is the expected behavior?**
It should import the style and create the classname no matter where the component is located as long as the reference to the file is correct.

**Please mention other relevant information.**
- node version: 8.2.1
- npm version: 5.3.0
- Operating system: MacOS Sierra 10.12.6

**Comment by rijkvanzanten** [comment]
I'm trying to achieve a setup like this: 
```
.    
├── assets/
├── components 
│   └── header                 
│       ├── index.js            < Here it works as expected
│       └── style.scss               
├── sections                                            
│   └── testimonials       
│       ├── index.js            < Here it doesn't
│       └── style.scss        
├── index.js   
├── manifest.json              
├── routes     
│   └── home   
│       ├── index.js           
│       └── style.scss         
└── template.html    
```

The `home` component in `routes` imports and renders the two correctly and I don't get any errors whatsoever. The classname isn't generated however, so the styles don't get applied.

**Comment by reznord** [comment]
Hi @rijkvanzanten as of now we are [watching over the two folders (components/routes)](https://github.com/developit/preact-cli/blob/master/src/lib/webpack/webpack-base-config.js#L192-L195).

We still have to decide on whether or not to restrict the folders or not.

**Comment by lukeed** [comment]
Yup, but you can use a custom config & modify/overwrite those values.

**Comment by reznord** [comment]
IMO, it would be better to watch `src` folder.

**Comment by rijkvanzanten** [comment]
Ahh that explains. I agree about watching the `src` folder.

But if these are the only folders being watched for style files, how come that an `index.scss` file directly in the `src` folder works as expected?

**Comment by rijkvanzanten** [comment]
@lukeed How would I extend the config to include the whole `src` folder? Adding `config.module.loaders[4].exclude = ['src'];` to `preach.config.js` unfortunately didn't work 🙃

**Comment by developit** [comment]
We cant enable CSS modules for all of `src`, because that would make global CSS impossible. Maybe it would work to invert the precedence though: global CSS only within `src/style/**`, modules everywhere else.

I think something like this could work:

```js
config.module.loaders[3].include = ['src'];
config.module.loaders[4].exclude = ['src'];
```

**Comment by reznord** [comment]
Just a random thought, can we use a different notation for global css something like `some_name.global.css`.

**Comment by developit** [comment]
maybe yeah, but then we're back to things being specific to preact-cli :(

**Comment by rijkvanzanten** [comment]
I'll close this as it is possible to watch additional folders by modifying the config. I couldn't get it to watch everything in `src` though. However, that's probably for the better as @lukeed mentioned in https://github.com/developit/preact-cli/pull/312.

For future reference, I was able to get my extra `sections` folder working by adding the following to `preact.config.js`:

```javascript
config.module.loaders[4].include = [
  path.resolve(__dirname, 'src', 'routes'),
  path.resolve(__dirname, 'src', 'components'),
  path.resolve(__dirname, 'src', 'sections')
];

config.module.loaders[5].exclude = [
  path.resolve(__dirname, 'src', 'routes'),
  path.resolve(__dirname, 'src', 'components'),
  path.resolve(__dirname, 'src', 'sections')
];
```
