### ISSUE TITLE
Build can't find node_module ending in .js or starting with @

### ISSUE THREAD

**Issue by rijkvanzanten** [developit/preact-cli#310]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Trying to production build an app which uses a Node module which ends in `.js` (like [`headroom.js`](https://npmjs.com/headroom.js)) results in a `ENOENT` error

**If the current behavior is a bug, please provide the steps to reproduce.**
Import a Node module ending in `.js` into your Preact app

**What is the expected behavior?**
It should require the module from `node_modules/headroom.js`

**Please mention other relevant information.**
- node version: 8.2.1
- npm version: 5.3.0
- Operating system: MacOS Sierra 10.12.6

**Comment by thangngoc89** [comment]
How do you import your module? Could you generate a simply reproduce repo so I can clone and play with it?

**Comment by rijkvanzanten** [comment]
Hi @thangngoc89 

I import it the "regular" way:
`import Headroom from 'headroom.js';`

I just now noticed it also fails when I import an organization package like
`import Player from '@vimeo/player';`

I'll create a repo for you. I'll post a comment here with a link when it's done 🙂

**Comment by thangngoc89** [comment]
that's weird. I'll take a look. btw, I usually use https://github.com/KyleAMathews/react-headroom . it's super  small with declarative API

**Comment by rijkvanzanten** [comment]
Yeah I just changed to that one (it misses some of the options however) 🙂 

I've uploaded a small demo on https://github.com/rijkvanzanten/preact-cli-import-demo

It is the default `preact create` app, with the import added to the home component https://github.com/rijkvanzanten/preact-cli-import-demo/blob/master/src/routes/home/index.js

**Comment by thangngoc89** [comment]
This looks like a bug in ours' implementation. Investigating it

**Comment by reznord** [comment]
@rijkvanzanten does it work fine when you pass a flag `--no-prerender` ?

**Comment by thangngoc89** [comment]
@reznord it doesn't work in dev mode too.

**Comment by rijkvanzanten** [comment]
@reznord the no prerender flag doesn’t change anything

**Comment by hassanbazzi** [comment]
no pre-render does fix it for me btw. Having this issue with `import player from 'player.js'`

**Comment by developit** [comment]
I'm seeing it work without prerendering, so this makes me thinks it's related to our use of `target:'node'`.

**Comment by reznord** [comment]
It failed for me when I tried with `preact build --no-prerender`

**Comment by developit** [comment]
ah it might just be dev vs prod.  dev build (watch) worked for me

**Comment by jeffutter** [comment]
I just wanted to mention that this happens for me too. If you are trying to add `--no-prerender` when doing `yarn run` you have to run it as such: `yarn run -- --no-prerender`  or it thinks the argument applies to yarn, not preact.

**Comment by reznord** [comment]
As @developit mentioned earlier, it is because of the SSR build that we are shipping by default. 

We will be providing a better error stack trace when it fails on this in the future.
