### ISSUE TITLE
preact init doesn't work

### ISSUE THREAD

**Issue by blakelapierre** [developit/preact-cli#311]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`preact init` gives a help output

![2017-08-13-023442_649x385_scrot](https://user-images.githubusercontent.com/777467/29246678-f95c400e-7fcf-11e7-9eee-f55deef40558.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
run `preact init` on command line 

**What is the expected behavior?**
interactive creation

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version
v7.1.0
- npm version
3.10.9
- Operating system
4.11.6-101.fc24.x86_64 GNU/Linux

**Comment by reznord** [comment]
`master` branch is used for development. `preact init` will be available in the next version of `preact-cli`

Please go through the `README`.
