### ISSUE TITLE
Stats file only includes `index.html`

### ISSUE THREAD

**Issue by ForsakenHarmony** [developit/preact-cli#316]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
stats file only includes `index.html`

**If the current behavior is a bug, please provide the steps to reproduce.**
`preact build --json`

**What is the expected behavior?**
stats should include the whole bundle

**Please mention other relevant information.**
- node version
  **8.3.0**
- npm version
  **5.3.0**
- Operating system
  **Windows**
- preact cli
  **1.4.1**

**Comment by touchstoneis** [comment]
I experienced the same behavior as well. I don't have an answer, but if you are in a bind and need the stats, editing the following lines in 'node_modules/preact-cli/lib/lib/webpack/run-webpack.js'  'writeJsonStats' method worked for me:

..
	//jsonStats = jsonStats.children && jsonStats.children[0] || jsonStats;

	//jsonStats.modules.forEach(stripBabelLoaderFromModuleNames);
	//jsonStats.chunks.forEach(c => c.modules.forEach(stripBabelLoaderFromModuleNames));
...

Hope that helps

**Comment by ForsakenHarmony** [comment]
yup that works, thx
