### ISSUE TITLE
The CopyWebpackPlugin is undefined

### ISSUE THREAD

**Issue by robinvdvleuten** [developit/preact-cli#331]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When I call the `getPlugins` helper, an array of all used plugins is returned. But it doesn't seem to contain the `CopyWebpackPlugin`.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
export default function (config, env, helpers) {
  console.log(helpers.getPluginsByName(config, 'CopyWebpackPlugin'));
}
```

**What is the expected behavior?**

I expect an array containing the `CopyWebpackPlugin`.

**Please mention other relevant information.**
- node version: v8.1.1
- npm version: v5.2.0
- Operating system: osx

**Comment by SaraVieira** [comment]
Hi @robinvdvleuten ,

The preact cli does not use that webpack plugin , if you need it you may need to add it by pushing into the `config.plugins` array in your preact-config.js

Here you can see the CLI's webpack : https://github.com/developit/preact-cli/blob/master/src/lib/webpack/webpack-base-config.js

**Comment by robinvdvleuten** [comment]
@SaraVieira but there is one in https://github.com/developit/preact-cli/blob/master/src/lib/webpack/webpack-client-config.js#L76 Aren't these merged when building with webpack?

**Comment by developit** [comment]
Ah - custom config is actually run twice - once against the SSR/prerender configuration, and once against the client configuration.  CopyWebpackPlugin is only in the client configuration, so you'll want to existence-test for it when trying to pull it out of the config:

```js
export default function (config, env, helpers) {
  let copyPlugin = helpers.getPluginsByName(config, 'CopyWebpackPlugin');
  if (copyPlugin) {
    // ..
  }
}
```

**Comment by robinvdvleuten** [comment]
I also managed to solve it by just adding the plugin myself within a custom config file 👍
