### ISSUE TITLE
Disable ssr prerender ? Just build spa app ? 

### ISSUE THREAD

**Issue by cuduy197** [developit/preact-cli#332]
Note: The code generator has deoptimised the styling of "E:/preact/hello/build/ssr-build/ssr-bundle.js" as it exceeds the max of "500KB"? 

How to disable prerender when build ?

**Comment by reznord** [comment]
`npm run build -- --prerender false` should do the work.

**Comment by terencechow** [comment]
For future users arriving here since its number 1 result from google: flag is now `--no-prerender`
