### ISSUE TITLE
How to using async/await with mobx ? [SLOVED :tada: ]

### ISSUE THREAD

**Issue by cuduy197** [developit/preact-cli#333]
I'm using mobx and i want to using async/await .
When i build it show error 
![capture](https://user-images.githubusercontent.com/25724956/29549443-8d506f24-8732-11e7-9546-a28b29ae483c.PNG)

This is my async fn 

![captur2e](https://user-images.githubusercontent.com/25724956/29549459-a854f132-8732-11e7-9cb5-057f85c9fcf1.PNG)

**Comment by reznord** [comment]
This doesn't seem like an issue with `preact/preact-cli`. Probably it is an error in your `userStore.js`

**Comment by cuduy197** [comment]
@reznord i'm run in dev mode it work normal, but error when i build ? 
Do i need config babel ?

**Comment by reznord** [comment]
Can you try running `npm run build -- --no-prerender` ?

Next time while opening an issue please follow the template.

**Comment by cuduy197** [comment]
Yes, but it still error 
It only work on development . 😕

**Comment by cuduy197** [comment]
🎉  Yeah , i sloved this problem . 😄 
Frist add  `yarn add babel-plugin-transform-runtime --dev ` 
then config "preact.config.js" 
```javascript
 let Plugin = helpers.getLoadersByName(config, "babel-loader")[0].rule.options.plugins;
  //Enable async
  Plugin.push("transform-regenerator");
  Plugin.push([
    "transform-runtime",
    {
      helpers: false,
      polyfill: false,
      regenerator: true
    }
  ]);```
Plz close this issue 🛩

**Comment by HadrienPierart** [comment]
Man, this issue and its solution should definitely be somewhere in the docs... I've been pulling my hair off on this error : "regeneratorruntime is not defined" for the last couple hours and couldnt find a way to fix that with preact...
And now it seems to work fine again !
Thanks a lot cuduy197 (and the maintainers of preact too !)
