### ISSUE TITLE
There is no gzip for js bundles

### ISSUE THREAD

**Issue by KatSick** [developit/preact-cli#334]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
No gzip on js files

**If the current behavior is a bug, please provide the steps to reproduce.**
Setup project with preact-cli 1.4.1. Open localhost:8080 and check the network tab in Chrome

**What is the expected behavior?**
Gzip enabled

**Please mention other relevant information.**
- node version (8.2.1)
- npm version (5.3.0)
- Operating system (Mac OS 10.12.6)

**Comment by reznord** [comment]
As of now we are not compressing the js bundle. Probably we add an option to the build command so the use can choose if he wants gzipping or not.

/cc @kristoferbaxter @developit

**Comment by developit** [comment]
inb4 we should also do brotli

**Comment by reznord** [comment]
We have the option of using [Zopfli](https://github.com/google/zopfli) as well. @kristoferbaxter can give more insights on this.

**Comment by thangngoc89** [comment]
My 2 cents:

- Need to compress the output at build step: messing with native dependencies, probably means lots of new issues.
- We need to change simplehttp2server /superstatic to something production ready so that users can run `npm run serve`

**Comment by developit** [comment]
I don't think there's an h2 alternative for simplehttp2server, but we could use `serve` instead of superstatic.  I think they might be looking into supporting the same config format?

**Comment by reznord** [comment]
We can go with `zopfli` + `brotli` for this.

**Comment by thangngoc89** [comment]
COnsider using wasm version (if any) instead of the native C version. It would everyone a tons of time

**Comment by kristoferbaxter** [comment]
Makes sense @thangngoc89, consider:
https://github.com/dfrankland/wasm-brotli
https://github.com/dfrankland/wasm-zopfli
