### ISSUE TITLE
what is recommended way to install preact-cli dev version?

### ISSUE THREAD

**Issue by jojo05** [developit/preact-cli#335]
Does anybody recommend also having both version (latest release and dev version), so that new projects are created with either one ?

**Comment by reznord** [comment]
What do you mean? Can you clarify or elaborate more on what you want?

**Comment by jojo05** [comment]
I am using 1.4.1. I want to test the homepage PR, preact init, ... which are in the dev version ?
What do I do?

**Comment by developit** [comment]
```
git clone git@github.com:developit/preact-cli.git
cd preact-cli
npm install

cd ../my-project
npm link ../preact-cli
npm start
```

**Comment by jojo05** [comment]
Great! thanks
I'll wait a bit more and then close the issue

**Comment by thangngoc89** [comment]
Yarn version:


```
git clone git@github.com:developit/preact-cli.git
cd preact-cli 
yarn install 
yarn link

cd ../my-project
yarn link preact-cli 
yarn start
```

Preact-cli folder can be anywhere with yarn
