### ISSUE TITLE
bundle splitting 

### ISSUE THREAD

**Issue by jojo05** [developit/preact-cli#336]
Is there a preact.config.js snippet for splitting the bundle in two parts, dependencies and app ? 

The use case would be for updating only the app.min.js in the actual PWA production updates

**Comment by developit** [comment]
Something that installs CommonsChunkPlugin with a setup to do async commons would be good.

**Comment by jojo05** [comment]
Having a broad set of preact.config.js snippets that change webpack configuration should help new users not to have to dig deep into webpack (learning webpack myself currently)
https://medium.com/webpack/webpack-bits-getting-the-most-out-of-the-commonschunkplugin-ab389e5f318

**Comment by developit** [comment]
Yup - that's what we're using plugins for:
https://github.com/developit/preact-cli/wiki/Plugins
