### ISSUE TITLE
preact-cli-plugin-graphql

### ISSUE THREAD

**Issue by robinvdvleuten** [developit/preact-cli#337]
I've created a GraphQL plugin which can be worth mentioning on the wiki page. It preprocess any "GraphQL query files" when imported. You can see the plugin [here](https://github.com/robinvdvleuten/preact-cli-plugin-graphql).

**Comment by reznord** [comment]
@robinvdvleuten can you paste a snippet as an example on how to extend the `preact.config.js`?

This might be worth adding.

**Comment by reznord** [comment]
Added: https://github.com/developit/preact-cli/wiki/Plugins#list-of-plugins 😄

**Comment by reznord** [comment]
Oh nvm, you have added it in the [README](https://github.com/robinvdvleuten/preact-cli-plugin-graphql/blob/master/README.md).
