### ISSUE TITLE
eslint also lints build directory

### ISSUE THREAD

**Issue by robinvdvleuten** [developit/preact-cli#338]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When I run `npm test`, it runs eslint which lints the build directory by default.

**If the current behavior is a bug, please provide the steps to reproduce.**

`npm test`

**What is the expected behavior?**

I expect that only my source files are linted

**Comment by developit** [comment]
Hmm - looks like it is bound only to `src`: https://github.com/developit/preact-cli/blob/80a77acc3df6ec7acbf4b11c7e13dd5ee2e64a6e/src/lib/setup.js#L53

Maybe an older scaffolded project?

Might be good to have it scaffold an eslintrc.

**Comment by robinvdvleuten** [comment]
@developit ah my bad! I am using version v1.4.1 which doesn't have this change. Maybe it would be nice to automatically let the CLI generate an eslint config.

**Comment by lukeed** [comment]
@robinvdvleuten That _is_ from v1.4.1 🤔

**Comment by developit** [comment]
I wish it was possible to define ignored/included directories in `eslintConfig` in the package.json :(

**Comment by reznord** [comment]
It is possible and I did in one of the PRs. But since we thought of going with templates, I closed that issue.

**Comment by reznord** [comment]
@developit, added in the templates

**Comment by reznord** [comment]
@robinvdvleuten you can add `"eslintIgnore": ["build/*"]` to your package.json, that will ignore the build folder while linting.

**Comment by robinvdvleuten** [comment]
@reznord I did by adding an `.eslintignore` file, thanks for all the help!
