### ISSUE TITLE
Plugin to handle env vars a la CRA

### ISSUE THREAD

**Issue by robinvdvleuten** [developit/preact-cli#341]
I've extracted another plugin from my created Preact SPA. It is a plugin to have support for environment variables a la CRA. Any env var prefixed with `PREACT_APP_` can be used in your code as `const secret = process.env.PREACT_APP_SUPER_SECRET` for example. It would be nice if it can be added to the wiki :) You can see the plugin here => https://github.com/robinvdvleuten/preact-cli-plugin-env-vars

**Comment by thangngoc89** [comment]
Hey thank you for making this plugin. But I want to add my 2 cents here. Webpack will replace each process.env.PREACT_APP with the actual value. If you use this at many places, this could resolved in a huge bundle. This only make sense for NODE_ENV where replacing the value will help uglify removing dead code. If you're using this a lot, consider moving them to a normal js file with const

**Comment by robinvdvleuten** [comment]
@thangngoc89 I get what you mean! I would only recommend it for using things that need to be configured easily like Auth0 tokens, API urls, etc. It is very handy to use it in products like Netlify where you can define env vars for the build process.

**Comment by DevanB** [comment]
Is NODE_ENV or any other env (to identify production) available in a preact-cli project? If not, this seems like a no brainer plugin to use.

@thangngoc89 @robinvdvleuten

**Comment by developit** [comment]
NODE_ENV is supported by default, yes.
