### ISSUE TITLE
Question: Is it possible to do SSR + dynamic routing now?

### ISSUE THREAD

**Issue by pronevich** [developit/preact-cli#347]
What is missing in `preact-cli` for SSR and dynamic routing with code splitting? Maybe exists examples or boilerplate with this functionality.

**Comment by dolebas** [comment]
+1

**Comment by lukeed** [comment]
Yes. Here's an example using Express: https://github.com/lukeed/preact-cli-ssr

It's a mixture of pre-rendering & `preact-render-to-string`, all orchestrated by Express.
