### ISSUE TITLE
Multiple watch folders?

### ISSUE THREAD

**Issue by nygdjs** [developit/preact-cli#348]
How is it possible to specify more than one (by default `/src`) watch folder for the dev server (`npm start`)?

The reason is that I'm developing an app, which has some npm dependencies, which I'm also developing, and they are scoped/private packages, so will reside in something like `/node_modules/@scope/`, so watching this folder and linking those dependencies there would be awesome.
Is it possible somehow? (Of course `/src` needs to be watched too.) 

`npm link` would solve the issue ofc., but has a long and troubled history with webpack, because of symlinks, so my current solution is that I copy the dependencies on change with [wml](https://github.com/wix/wml) to the apps node_modules folder, but  it won't cause a live reload on the dev server.

Thanks for the answer!

**Comment by lukeed** [comment]
I don't think it's possible to watch multiple "src"-type directories in Webpack -- at least, not without running multiple compilers.

You can continue to play with symlinks, as you've suggested, or you can play with the [`watchOptions`](https://webpack.js.org/configuration/watch/#watchoptions). Our [included config](https://github.com/developit/preact-cli/blob/81c7bb23e9c00ba96da1c4b9caec0350570b8929/src/lib/webpack/webpack-client-config.js#L177-L182) ignores all `node_modules` by default for apparent reasons.

Going to close, but I hope that helped in some way 😬 Sorry for the delay -- this was just brought to my attention. 🌴

**Comment by nygdjs** [comment]
> Sorry for the delay -- this was just brought to my attention. 🌴
Thanks anyway. 🎉

In the meanwhile started to experiment with a [yarn-workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) based monorepo, and it seems to solve a lot of problems with symlinks so far.

**Comment by lukeed** [comment]
Cool! I'll look into it sometime.
