### ISSUE TITLE
production option for the build command not working?

### ISSUE THREAD

**Issue by ospatil** [developit/preact-cli#360]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The `--production` option to the `build` command doesn't seem to work. It creates a minified build even if I pass `false` as a value for it.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a new project with empty template - `preact create my-app --type empty`
2. Build the application with production option turned off - `preact build --production false`

**What is the expected behavior?**
It should create non-minified files in the `build` folder.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version - **v8.4.0**
- npm version - **v5.4.0**
- Operating system - **macOS Sierra 10.12.6**
- Preact-cli version - **v1.4.1**

**Comment by lukeed** [comment]
You would have to do `--no-production` because yargs isn't smart enough to infer boolean types.
