### ISSUE TITLE
Add option to create stand-alone component template from the CLI.

### ISSUE THREAD

**Issue by variable-content** [developit/preact-cli#363]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
As a component author I'd like to use the CLI to create easily shareable components that other developers can consume in preact apps, or ideally in a format that allows them to be used in react/vue/angular/etc. applications (web components?). See this SO post for a similar request: https://stackoverflow.com/questions/45199474/create-pluggable-component-in-preact

**If this is a feature request, what is motivation or use case for changing the behavior?**
As it's so lightweight Preact seems perfect as a base for component development - if the CLI supported this with a template to help component authors get started that would make our lives much easier!

**Comment by developit** [comment]
You're likely to find [preact-habitat](https://github.com/zouhir/preact-habitat) or [preact-custom-element](https://github.com/bspaulding/preact-custom-element) provide what you're looking for. Both of them wrap up your exported Preact component in a renderer layer - preact-habitat with its imperative and DOM declarative APIs, and preact-custom-element exporting to a Web Component.

In preact-cli, if you export your root component (eg: from `src/index.js`), it will be wrapped in a `render(component, body)` call.  However, if you omit that export, you're given control over how it gets defined.

**Comment by variable-content** [comment]
Thanks @developit, that's useful to know.

I'm using preact-habitat in my index.js file, which builds the js file but results in a number of errors during the build process:

```
Template execution failed: ReferenceError: document is not defined
  ReferenceError: document is not defined

  - ssr-bundle.js:8384 getExecutedScript
    c:/Git/WebWidgets/Prototype-Preact/build/ssr-build/ssr-bundle.js:8384:10

  - ssr-bundle.js:8461 widgetDOMHostElements
    c:/Git/WebWidgets/Prototype-Preact/build/ssr-build/ssr-bundle.js:8461:23

  - ssr-bundle.js:8512 Object.render
    c:/Git/WebWidgets/Prototype-Preact/build/ssr-build/ssr-bundle.js:8512:20

  - ssr-bundle.js:7977 init
    c:/Git/WebWidgets/Prototype-Preact/build/ssr-build/ssr-bundle.js:7977:13

  - ssr-bundle.js:8009 Object.JkW7
    c:/Git/WebWidgets/Prototype-Preact/build/ssr-build/ssr-bundle.js:8009:1

  - ssr-bundle.js:21 __webpack_require__
    c:/Git/WebWidgets/Prototype-Preact/build/ssr-build/ssr-bundle.js:21:30

  - ssr-bundle.js:136 Object._
    c:/Git/WebWidgets/Prototype-Preact/build/ssr-build/ssr-bundle.js:136:18

  - ssr-bundle.js:21 __webpack_require__
    c:/Git/WebWidgets/Prototype-Preact/build/ssr-build/ssr-bundle.js:21:30

  - ssr-bundle.js:67
    c:/Git/WebWidgets/Prototype-Preact/build/ssr-build/ssr-bundle.js:67:18

  - ssr-bundle.js:2 Object.<anonymous>
    c:/Git/WebWidgets/Prototype-Preact/build/ssr-build/ssr-bundle.js:2:10

  - node.js:144 loader
    [Prototype-Preact]/[babel-register]/lib/node.js:144:5

  - node.js:154 Object.require.extensions.(anonymous function) [as .js]
    [Prototype-Preact]/[babel-register]/lib/node.js:154:7

  - module.js:20 require
    internal/module.js:20:19

  - prerender.js:34 prerender
    [Prototype-Preact]/[preact-cli]/lib/lib/webpack/prerender.js:34:11

  - webpack-client-config.js:194 Object.ssr
    [Prototype-Preact]/[preact-cli]/lib/lib/webpack/webpack-client-config.js:194:54

  - template.html:111 EM6I.module.exports
    [Prototype-Preact]/[preact-cli]/lib/resources/template.html:111:37

  - index.js:264
    [Prototype-Preact]/[html-webpack-plugin]/index.js:264:16


Build failed!
```

Seems like it messes with SSR - which I try to disable by building with this command:
`preact build -- --prerender false`

but that results in another error
`multi ./index.js
Module not found: Error: Can't resolve 'c:\Git\WebWidgets\Prototype-Preact\index.js' in 'c:\Git\WebWidgets\Prototype-Preact'
 @ multi ./index.js
Build failed!`

Any pointers?

**Comment by variable-content** [comment]
Ignore my comment above.

Was able to disable SSR using the correct flag for `preact build`: --no-prerender
I was using the `preact watch` flag which is subtly different: --prerender false
