### ISSUE TITLE
Upgrade to Webpack 3

### ISSUE THREAD

**Issue by lukeed** [developit/preact-cli#367]
And remove/replace `webpack-blocks` in the process? 
  _We _currently_ have to since it only supports `1.x` and `2.x`_

**Comment by reznord** [comment]
We should, that reduces the bundle size as well (I remember from the previous PR)

Since now that templates are in, we can totally ignore the last PR and create a whole new PR or totally start fresh. 

@lukeed would you like to take it? Since you have already sth similar to that
