### ISSUE TITLE
Error: Couldn't find preset "latest" relative to directory

### ISSUE THREAD

**Issue by khalibloo** [developit/preact-cli#368]
Yes, latest as of today

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I get the following error when I run npm start.
`Error: Couldn't find preset "latest" relative to directory "C:\\blah\\blah"`

**If the current behavior is a bug, please provide the steps to reproduce.**
I simply installed preact-cli as instructed in the readme. Then I installed preact-cli-plugin-typescript. Renamed the js files to tsx and ran npm start. The issue is very similar to #9 
In fact, I solved it by deleting a .babelrc in a parent directory. I'm only reporting this to bring the error to your attention.

The configs are all default.

**What is the expected behavior?**
I expected it to run without any errors :D

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version
6.11.2
- npm version
3.10.10
- Operating system
Windows 10

**Comment by lukeed** [comment]
Hi @khalibloo, sorry for the delay.

Is this still happening for you? We've reworked the Babel config since this, and curious if you're still encountering the issue.

Thanks!
