### ISSUE TITLE
Newly created app fails ESlint checks and fails to call test target on preact CLI

### ISSUE THREAD

**Issue by lambrospetrou** [developit/preact-cli#369]
**Do you want to request a *feature* or report a *bug*?**
**Bug**

**What is the current behavior?**
When I run ```yarn test``` in a newly created preact app it fails with 2 errors and 2 eslint warnings.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Created a new preact app using ```preact create app-name --yarn``` 
2. Run ```yarn test```

**What is the expected behavior?**
The project should conform to all defined ESLint rules.

**Please mention other relevant information.**
- preact cli
 preact-cli 1.4.1

- node version
node v7.4.0
yarn v1.0.1

- npm version
npm v4.0.5

- Operating system
```uname -a```: Linux thinkmint 3.13.0-24-generic #47-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**Output**

```
yarn test
yarn test v1.0.1
$ eslint src && preact test

/path/to/app/lvb-events/lvb-events/src/components/app.js
  11:2  error  Expected line before comment  lines-around-comment

/path/to/app/lvb-events/lvb-events/src/components/header/index.js
  5:16  warning  Component should be written as a pure function  react/prefer-stateless-function

/path/to/app/lvb-events/lvb-events/src/routes/home/index.js
  4:16  warning  Component should be written as a pure function  react/prefer-stateless-function

/path/to/app/lvb-events/lvb-events/src/routes/profile/index.js
  22:2  error  updateTime should be placed before componentDidMount  react/sort-comp

✖ 4 problems (2 errors, 2 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.
```

**Comment by lambrospetrou** [comment]
Also, once you fix the eslint warnings and the build succeeds you get the following failure cause preact CLI does not have a ```test``` argument.

```
yarn test
yarn test v1.0.1
$ eslint src && preact test
         ▄▄
     ▄▄▓▓▓▓▓▓▄▄
  ▄█▀▀█▓▓▓▓▓▓▓▀▀█▄▄
▐▓▌▐▓▓▓▒▄ ▀▄▄▓▓▓▌▐▓▌ 
▐▓▓▄▀▓▀ ▄▓▓▄▄▀▓▓ ▓▓▌ 
▐▓▓▓▌ ▒▓▌  ▐▓▓  ▓▓▓▌ preact-cli 1.4.1
▐▓▓ ▒▓▄▄▀▓▓▀ ▄▓▓ ▓▓▌
▐▓▌▐▓▓▓▀▀▄▄▀▀▓▓▓▌▐▓▌
  ▀█▄▄▒▓▓▓▓▓▓▒▄▄▒▀
      ▀▓▓▓▓▓▓▀▀
         ▀▀
For help with a specific command, enter:
  preact help [command]

Commands:
  create <name> [dest]  Create a new application.
  build [src] [dest]    Create a production build in build/
  watch [src]           Start a development live-reload server.
  serve [dir]           Start an HTTP2 static fileserver.

Options:
  --cwd       A directory to use instead of $PWD.                   [default: .]
  -h, --help  Show help                                                [boolean]

Unknown argument: test
error Command failed with exit code 1.
```

**Comment by lambrospetrou** [comment]
I spend some time investigating to see how the target ```test: "eslint src && preact test"``` is added and I realised that the code adding that was removed in this commit https://github.com/developit/preact-cli/commit/f1891fe70a9c81920fe236ba1c0d1c793df96bb5#diff-3a91220e73b4c8574727374e6c42763e

I don't know if it is removed on purpose since it failed or if it was just left out on error during the refactoring but preact does not have a test argument, so this should not be here anyway.

I made a PR that fixes the ESlint warnings and errors in case you want to just keep ```test: eslint src``` as a target in the generated app.

https://github.com/developit/preact-cli/pull/370

**Comment by reznord** [comment]
We are moving to custom templates in the next version of the preact-cli, so the examples in preact-cli is gonna be removed.

Regarding the test command, We are going to leave that in the user land so, the user can go ahead and use either Jest/Mocha/Chai/Enzyme and configure the app according to it.

Regarding the ESLint issue, we are planning to move to a new preset instead of using the [current one](https://github.com/synacor/eslint-config-synacor).

So, in the next version all these problems will be tackled gracefully. 😄

**Comment by lambrospetrou** [comment]
OK good to know. It's just bad first experience of the framework when creating a new app with the recommended CLI and then failing to build;p 
Looking forward to trying the next version then.

Thanks
