### ISSUE TITLE
[Question] - Hey guys, how can i achieve this with simple global state with preact?

### ISSUE THREAD

**Issue by talvasconcelos** [developit/preact-cli#376]
Hey guys how can one do this kind of redux hack in preact? 

[You Probably Don’t Need Redux](https://medium.com/@blairanderson/you-probably-dont-need-redux-1b404204a07f)

I'm using preact-cli and the index.js file just exports the App component. 

```
import './style';
import App from './components/app';

export default App;
```
Where would i wrapp with AppState component?

**Comment by lukeed** [comment]
Hey, this is a little more appropriate for our [Slack](https://preact.slack.com) (imo), but to answer your question, you have two options:

1. Import your `<AppState />` into your `components/app/index.js` file, then export the "wrapped" version of `<App/>`

2. Import `<App/>` and `<AppState/>` into the main `index.js` file & export a functional component of the two:

    ```js
    import AppState from './components/appstate';
    import App from './components/app';

    export default _ => (
      <AppState>
        <App />
      </AppState>
    );
    ```

Hope that helps! There's almost always in the Slack room if you need more 👍

**Comment by talvasconcelos** [comment]
Ok, thanks and sorry about posting here.

**Comment by lukeed** [comment]
No worries!
