### ISSUE TITLE
https termination at nginx reverse proxy

### ISSUE THREAD

**Issue by dav-is** [developit/preact-cli#378]
**Do you want to request a *feature* or report a *bug*?** feature

**What is the current behavior?**
Forced http2 and https

**What is the expected behavior?**
Add parameter to run in production using http only. Node will be behind load balancer and reverse proxy where https will be appended. The browser will still receive a tls connection, there's just no need for tls in internal networks.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Hosting inside a cluster

Appologies if this is already possible.

**Comment by dav-is** [comment]
I was under the assumption that this package used SSR, but since it doens't there's no need to run node at all :man_shrugging:

**Comment by dav-is** [comment]
So apparently it prerenders, but doesn't output any html files... only seemingly arbitrary json files?

**Comment by lukeed** [comment]
Hey, by default we only prerender the `index.html` (`/`) route. If you want to do multiple, you have to [specify the routes](https://github.com/developit/preact-cli#prerender-multiple-routes).

**Comment by lukeed** [comment]
Just to clarify: It _does_ output multiple HTML files, they're just placed within `build/*`. Similarly, nested routes' files are placed in sub-directories to easily accommodate static servers.

Lastly, here's an [example using Preact CLI & Express](https://github.com/lukeed/preact-cli-ssr) for a runtime SSR solution.
