### ISSUE TITLE
Try and get `create-preact-app` package on NPM

### ISSUE THREAD

**Issue by wayneashleyberry** [developit/preact-cli#38]
Looks like @alexkuz owns the `create-preact-app` package on NPM.

It'd be amazing if he would be willing to transfer it in order to enable the [new yarn create workflow](https://yarnpkg.com/blog/2017/05/12/introducing-yarn/).

```
yarn create preact-app
```

**Comment by alexkuz** [comment]
Sure, it's all yours :) Just give me instructions, I'll do that.

**Comment by wayneashleyberry** [comment]
@developit what do you think?

**Comment by developit** [comment]
Hmm - I'm open to anything here, but I actually feel like `create-preact-app` should continue to be a fork of `create-react-app`.  Perhaps we create a new package called `create-preact-cli-app`?

**Comment by thangngoc89** [comment]
`create-preact-cli-app` feels like creating a CLI app with preact, not a web app 

p/s IMHO

**Comment by wayneashleyberry** [comment]
I see your point @developit, I think either would be okay though

**Comment by developit** [comment]
Yup, just there's probably a use-case for both, and `create-preact-app` feels like a fork of `create-react-app`.  Maybe even `create-preact-cli`?  Weird name but it would allow `yarn create preact-cli`.

**Comment by wayneashleyberry** [comment]
`create-preact-pwa` sounds awesome...

```
yarn create preact-pwa
```

Love it @developit

**Comment by thangngoc89** [comment]
Love `create-preact-pwa`

**Comment by alexkuz** [comment]
Either way, while we are here - since I don't actually support `create-preact-app` repo (I really like preact, but I don't use it right now), I would gladly transfer it to someone who's willing to take care of it, as well as npm package.

**Comment by ericclemmons** [comment]
I got bored last night & made https://www.npmjs.com/package/create-preact-pwa.

`yarn create preact-pwa my-pwa` 👍 .

**Comment by developit** [comment]
you rock @ericclemmons

**Comment by wayneashleyberry** [comment]
Awesome! Thank you @ericclemmons, @developit and everyone else :)
