### ISSUE TITLE
404 Errors are Actually 200?!

### ISSUE THREAD

**Issue by dav-is** [developit/preact-cli#380]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
No 404 pages, and even on the preact home page, 404 pages are actually showing 200!!
**If the current behavior is a bug, please provide the steps to reproduce.**
Go to http://localhost:8080/randomstringthatisntroute
Open chrome network panel
See that it responds with 200

**What is the expected behavior?**
Throw an actual 404 error, make it easy to define error pages inside preact-cli

**If this is a feature request, what is motivation or use case for changing the behavior?**
Obviously this is horrible for SEO

**Comment by lukeed** [comment]
There's no server included -- that's where the status codes come from.

The `Router` included will act as a catch-all _if and only if_ you choose to redirect all paths to the index. This _is_ the included configuration, but only if you use our config on your server.

**Comment by dav-is** [comment]
I thought this package included some server side rendering?

**Comment by lukeed** [comment]
There's _pre_rendering, which produces populated HTML files for static hosting.

**Comment by dav-is** [comment]
Oh ok that makes sense. The README references server side rendering (which I wouldn't say is the same thing as prerendering) and it confused me
