### ISSUE TITLE
`devServer.public` property is ignored by the WebpackDevServer

### ISSUE THREAD

**Issue by cohesively** [developit/preact-cli#381]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I have port `8080` reverse proxied to the `/` route.

With the following `preact.config.js`, the WebpackDevServer (/w HMR) is disconnecting shortly after page load because it tries to make requests to `https://abc.com:8080/sockjs-node/info?t=1506134504647` instead of `https://abc.com/sockjs-node/...`.

```
export default function (config, env, helpers) {
        config.devServer = {
                "public": "abc.com",
                stats: "minimal",
        };
}
```

The server is started with `preact watch` without any parameters/flags.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've encountered this problem before when directly using `webpack` and the `webpack-dev-server` and was able to solve it by setting the `devServer.public` property to the domain name without the port. However, setting it through the `preact.config.js` doesn't seem to have any effect on where the WDS requests are directed.

https://webpack.js.org/configuration/dev-server/#devserver-public

I notice that the documentation mentions starting the WDS in inline mode. Is that what's happening with `preact watch`?

**What is the expected behavior?**

With the `devServer.public` property set, I expect the WebpackDevServer web-socket requests to be sent to the address provided by that property.

**Please mention other relevant information.**
- node version: **8.5.0**
- npm version: **5.3.0**
- Operating system: **Ubuntu 16.04.3 LTS**
- preact-cli: **1.4.1**

**Comment by lukeed** [comment]
Sorry it took us so long to get to you!

I _think_ the issue is that you're overwriting the entire `config.devServer` with your object.

I would try:

```js
// preact.config.js
export default function (config, env, helpers) {
  if (!env.production) {
    config.devServer.public = 'abc.com';
    config.devServer.stats = 'minimal';
  }
}
```

Please let us know how it goes 🙏

**Comment by developit** [comment]
Absolutely - that'd cause a lot of issues.  Using @lukeed's suggestion, or `Object.assign(config.devServer, {  ...  })` would work.
