### ISSUE TITLE
Watch script is not `watch` and instead is `dev`

### ISSUE THREAD

**Issue by wescoder** [developit/preact-cli#385]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
README shows script for starting dev server as `yarn watch` but in `package.json` we have
```js
"scripts": { //...
    "dev": "preact watch"  //...
},
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Install `preact-cli` create a new project with `preact create --yarn test-app test`

**What is the expected behavior?**
Either in the docs we should have `yarn dev` or in the `package.json` we should have `"watch": "preact watch",`

**Please mention other relevant information.**
- node version: v8.5.0
- npm version: 5.3.0
- yarn version: 1.1.0
- Operating system: Ubuntu 16.04.3 LTS

**Comment by reznord** [comment]
I think you got confused somewhere:

[Here](https://github.com/developit/preact-cli#using-yarn) it shows `yarn start` for running dev server.

**Comment by lukeed** [comment]
@reznord: @wescoder is correct for the 1.4.1 release. We have `yarn watch` written in the README but all examples ship `dev` command.

@wescoder: Sorry for the inconvenience, but this is no longer applicable moving forward. We appreciate you taking the time to submit this, though!

**Comment by reznord** [comment]
@wescoder Oh my bad. Sorry for the inconvenience.

Just for further clarification on scripts:

`npm run start` or `yarn start`: Runs serve or dev, depending on NODE_ENV value. Defaults to dev server
`npm run dev` or `yarn dev`: Run a development, HMR server
`npm run serve` or `yarn serve`: Run a production-like server
`npm run build` or `yarn build`: Production-ready build

**Comment by wescoder** [comment]
Oh I see it is correct in master branch indeed, thanks.
I'm closing this.
