### ISSUE TITLE
Disabling Prefixes

### ISSUE THREAD

**Issue by mehmetkose** [developit/preact-cli#386]
Hello, I just want to ask quick question, I'll use http2 features at the backend and I need to know exact file names (js, map, css etc). So how can I disable version prefixing?
Thanks.

- node version
8.5.0
- npm version
5.4.2
- Operating system
Mac OS

**Comment by developit** [comment]
hmm - you mean the filename hashing?  I'm not sure we can, since route names aren't unique.

**Comment by lukeed** [comment]
@developit Is correct in that it makes it more likely for you to have a filename clash. If you're careful with your naming, you "should" be okay.

If you still want to do this, you can with: 

```js
// preact.config.js
export default function (config, env, helpers) {
  if (!env.ssr) {
    config.output.filename = '[name].js';
    // maybe you want 'chunkFilename' too?
  }
}
```

Instead I would recommend something like [`webpack-manifest-plugin`](https://github.com/danethurber/webpack-manifest-plugin) to generate a map that points the "naked" filename to the hashed/versioned filename. Your HTTP2 server can use that. (I do this.)
