### ISSUE TITLE
Newly generated code does not conform to eslint settings

### ISSUE THREAD

**Issue by NateRadebaugh** [developit/preact-cli#389]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `yarn test` on a newly generated project yields 2 errors and 2 warnings for eslint.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a new project using preact-cli
2. Attempt to run tests:

```
yarn test
yarn test v0.27.5
$ eslint src && preact test

.\src\components\app.js
  11:2  error  Expected line before comment  lines-around-comment

.\src\components\header\index.js
  5:16  warning  Component should be written as a pure function  react/prefer-stateless-function

.\src\routes\home\index.js
  4:16  warning  Component should be written as a pure function  react/prefer-stateless-function

.\src\routes\profile\index.js
  22:2  error  updateTime should be placed before componentDidMount  react/sort-comp

? 4 problems (2 errors, 2 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.
```

**What is the expected behavior?**
A newly created project should conform to default eslint settings.

**If this is a feature request, what is motivation or use case for changing the behavior?**
This project should act as a pristine starting point for creating a new preact project.

**Please mention other relevant information.**
- node version: v6.11.3
- npm version: 5.4.2
- Windows 10

**Comment by reznord** [comment]
Hey, right now we don't have support for tests and it just runs lint on the `src` folder.

In the upcoming versions we are moving to [templates](https://github.com/preactjs-templates) where the user can clone and use it. This way the user can use any tests which he wants.
