### ISSUE TITLE
preact serve without https

### ISSUE THREAD

**Issue by conradob** [developit/preact-cli#390]
Is there a way to run `preact serve` without https?
In my server I'm already proxying the requests from `443` to my `PORT` environment variable

`preact serve` command does not allow `--https false` option.

Thanks.

**Comment by developit** [comment]
Hi there - the server we spawn (simplehttp2server) only supports HTTPS. However, you can instead spawn [superstatic](https://github.com/firebase/superstatic), which is HTTP:

```js
npm install --save superstatic
preact serve --server superstatic
```

**Comment by mrdulin** [comment]
@developit thanks. it works.
