### ISSUE TITLE
preact-cli-foo not found.

### ISSUE THREAD

**Issue by mrdulin** [developit/preact-cli#392]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```bash
~/workspace/potsdam(master ✗) npm install --save-dev preact-cli-foo
npm ERR! code E404
npm ERR! 404 Not Found: preact-cli-foo@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elsa/.npm/_logs/2017-10-09T10_10_20_576Z-debug.log
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I follow this wiki - https://github.com/developit/preact-cli/wiki/Plugins
`preact-cli-foo` is not exist.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version 8.4.0
- npm version 5.3.0
- Operating system OSX

**Comment by reznord** [comment]
Hi, in that context `preact-cli-foo` represents any of the plugins which are listed here in the [wiki](https://github.com/developit/preact-cli/wiki/Plugins#list-of-plugins).

**Comment by mrdulin** [comment]
@reznord  -_ -, I got it. thx
