### ISSUE TITLE
Make `preact serve` always use default config OR remove `preact serve`

### ISSUE THREAD

**Issue by scottmas** [developit/preact-cli#4]
After executing `preact build` and then running `preact serve` in the build directory, I'm always getting 404's. It works fine when I do a http server. And it even works when I use [local-web-server ](https://www.npmjs.com/package/local-web-server) with their `--https` option. But nada with `preact serve`. 

On a related note, `preact serve` also seems to break http connections to localhost, since they always get redirected to https. I had to use this [SO answer](http://stackoverflow.com/a/33139466/1027138) to fix it.

**Comment by scottmas** [comment]
Okay, obvs - the issue goes away once you point simplehttp2server at the default configuration file. This is a bit clunky though, since I have to run do `npm run serve -- --server config`, copy the output to a file, and then run `preact serve -- -config saved-config.json`. 

So I think we should either remove `preact serve` (what's it there for anyways - to test prod builds?). Or we should just have `preact serve` default to using the default configuration. 

Or, as a third option, we could always write `static-app.json` to the new preact-cli project with the name `http2-config.json` or the like, and then have `preact serve` look for a `http2-config.json` file when serving.

**Comment by developit** [comment]
Hmm - the default behaviour should use the configuration exactly like your workaround does. Might be worth checking again without the config flag?

**Comment by scottmas** [comment]
Yea, it does still blow up for me. Steps to reproduce:

```bash
preact create test-app
cd test-app
preact build
cd build
preact serve
```
Then load https://localhost:8080 and I get a 404. It may have worked once briefly as I recall, but then it blew up and it was also buggy. The error I get now in my console when trying to request pages is

```
http2: server: error reading preface from client [::1]:57380: read tcp [::1]:8080->[::1]:57380: read: connection reset by peer
```

**Comment by scottmas** [comment]
What are your thoughts on the third option though, irrespective? I find myself liking that one the best. For the Preact app to work regardless, they're going to _need_ a server that supports http 2 with the configuration described. Obviously this configuration will look different depending on the platform (nginx, etc) but there's just no way around needing the correct configuration. 

If we always write an `http2-config.json` file, it becomes pretty obvious to users that they need to have an http2 server that supports the configuration described. Eventually we could even have templates for nginx configurations, etc.

**Comment by developit** [comment]
Definitely don't need an http2 server - it just gives you another 500ms of headroom for your app's main bundle. I'd actually like to have `preact build` emit `build/static-app.json`, it's odd to shim it into serve.

**Comment by rkostrzewski** [comment]
@scottmas `preact serve` internally looks for `./build` folder and serves files from there. So the workflow should be like this:
```
preact create test-app
cd test-app
preact build
preact serve
```
or
```
preact create test-app
cd test-app
npm run build
npm run serve
```

**Comment by developit** [comment]
Ahh - yes sorry `preact build` should be run in your repo root, not in `./build` - it's meant to be run in your package.json scripts, rather than being a CWD static fileserver.
