### ISSUE TITLE
We are using preact-cli

### ISSUE THREAD

**Issue by reznord** [developit/preact-cli#402]
Thought it would be better to list all projects using preact-cli for their applications in production, which can be added to the wiki page.

**Comment by developit** [comment]
One I found while crawling the web:  it looks like pretty much the entire [gatorade.com](https://gatorade.com) site is built with Preact CLI!

**Comment by clemtrek** [comment]
Consent for using their site name mmust be thought upon.............

**Comment by developit** [comment]
Yup! That's why it hasn't been listed. Their use of the CLI is public knowledge though, I was able to detect it using BigQuery.

**Comment by fokusferit** [comment]
Maybe instead of pointing to a specific Homepage / Product, offering companies to highlight that they are using it ? We are using it for two internal applications and I know of some more teams :-)

**Comment by prateekbh** [comment]
@fokusferit i guess just organization name should be fine

**Comment by developit** [comment]
Yes - organization names are ideal actually - I think the goal here is to collect a list of logos we can then show on the homepage once it's created.
