### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by tkbremnes** [developit/preact-cli#41]
Some APIs require HTTPS for them to function (such as geolocation, getUserMedia). Being able to start a server with HTTPS (with or without supplied (self signed) certs) would help testing on devices.

**Comment by lukeed** [comment]
Hi! If you run `npm run serve`, you should be able to get a HTTPS node server running. However, some users are experiencing a faulty cert. Looking into it, but might as well give it a try first 👍

**Comment by tkbremnes** [comment]
You are absolutely right! I was using the `npm start` command (muscle memory I guess). Thanks! 😸

**Comment by lukeed** [comment]
Cool! Yeah, `serve` boots a production-like server for prod-testing. The others are a much simpler/faster dev server.

**Comment by developit** [comment]
Hmm - that's an interesting point.  `webpack-dev-server` allows an `--https` flag to spawn an HTTPS server - we should do the same! Perhaps not by default but certainly as an option.
