### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'postcss' of null

### ISSUE THREAD

**Issue by brielov** [developit/preact-cli#410]
Hi, I'm trying to use css modules composition but I keep getting this error.

This is what I have:

`
/* container.css */
.container {
  width: 100%;
  max-width: 1200px;
}
`

`
/* somemodule.css */
.inner {
  composes: container from "../../style/container.css";
}
`

And this is what I get:

```
✖ ERROR ./src/style/container.css
Module build failed: TypeError: Cannot read property 'postcss' of null
    at Processor.normalize (/Users/brielov/Projects/Grupo Jolivet/website/node_modules/postcss/lib/processor.js:136:13)
    at new Processor (/Users/brielov/Projects/Grupo Jolivet/website/node_modules/postcss/lib/processor.js:51:25)
    at postcss (/Users/brielov/Projects/Grupo Jolivet/website/node_modules/postcss/lib/postcss.js:73:10)
    at Promise.resolve.then.then (/Users/brielov/Projects/Grupo Jolivet./node_modules/postcss-loader/lib?{"sourceMap":false,"plugins":[null]}!./src/components/header/style.css 3:10-288 11:28-306
 @ ./src/components/header/style.css
 @ ./src/components/header/index.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ ./node_modules/preact-cli/lib/lib/entry.js
```

**Comment by SaraVieira** [comment]
Hello !

Can you please share your preact.config ?

**Comment by brielov** [comment]
Hi, I have no preact.config, it's a default `preact create default myApp`

**Comment by reznord** [comment]
@brielov hey, in the earlier versions we forgot the `sourcemaps` for `postcss`, you were getting this error because of that. Please do update the `preact-cli` to the latest version (i.e. `v2.0.2`) and can you please tell me if you are still facing the same issue.

**Comment by brielov** [comment]
@reznord I just did that, and still no luck :/

**Comment by reznord** [comment]
Is there a repo somewhere I can take a look at? It will be a lot easier in that case. 😄

**Comment by tiagoinacio** [comment]
I've also come across this error. After some research i found [this issue in PostCSS Loader](https://github.com/postcss/postcss-loader/issues/287). Apparently, it's missing an `ident` property. I've added that to the `preact-cli/lib/lib/webpack/webpack-base-config.js` on the postcss-loader options and it's working.
