### ISSUE TITLE
Cannot find module 'less-loader'

### ISSUE THREAD

**Issue by guillaumebreux** [developit/preact-cli#413]
Hey, I have this strange bug with the new version of the preact-cli :s 

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`Module build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'less-loader'`

**If the current behavior is a bug, please provide the steps to reproduce.**
- I have the preact-cli 2.0.1 as a devDependencies
- `npm install` works fine
-  I have a npm script that run: `preact build && preact serve --port=9090`
- Then i have a lot of error like: `Module build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'less-loader'` and the build fail

Everything works fine if i go back to 1.4.1

**What is the expected behavior?**
No error and build succeed? :D

**Please mention other relevant information.**
- node version: 6.9.5
- npm version: 3.10.10
- Operating system: Mac osX

**Comment by lukeed** [comment]
Hey there,

If you're upgrading a project from 1.x to 2.x, you have to manually install `less` and `less-loader` and they are no longer shipped by default across all installations. The same applies for any CSS pre-processing tool.

**Comment by guillaumebreux** [comment]
How ok then it works, i guess i missed something in the doc :D

Thanks :)

**Comment by lukeed** [comment]
No worries, thanks for the thoroughness!
