### ISSUE TITLE
Issues in post css, mixed sorucemaps settings

### ISSUE THREAD

**Issue by zouhir** [developit/preact-cli#416]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
![screen shot 2017-10-21 at 22 31 25](https://user-images.githubusercontent.com/5052316/31851422-fd097894-b6b0-11e7-9198-339c15858e1d.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
empty project with a component using `.scss` Sass loader.

**What is the expected behavior?**
not see the post css warnings & continue to compile correctly & see the page.

**Please mention other relevant information.**
- node version: 7.9.0
- npm version: 5.5.1
- Operating system: Mac

I have fixed this on my local via consistent sourcemap options but would like to understand this change: https://github.com/developit/preact-cli/pull/407 which seem to have caused this behaviour 😶

**Comment by reznord** [comment]
Change #407 is not released to npm yet but having the sourcemaps enabled should fix it.

Will do a minor patch release tonight.

**Comment by zouhir** [comment]
I tested against current master -- hope am wrong.. can we please verify & be careful? I can also share a my code with @lukeed and work with him when I wake up if he needs anything.

**Comment by lukeed** [comment]
Just saw this. You shouldn't be getting the warning in `2.0.2`. It's gone in all mine now.

Please try it @zouhir & lemme know. Can always DM~

**Comment by zouhir** [comment]
no more issues - 2.0.2 is looking great!

**Comment by lukeed** [comment]
Cool! 🎉
