### ISSUE TITLE
SugarSS

### ISSUE THREAD

**Issue by calebeby** [developit/preact-cli#422]
**Feature Request**: I want to use [SugarSS](https://github.com/postcss/sugarss). 

How do I configure `preact-cli` to use the `sugarss` parser? I want to put my css code in `.sss` files, and I want them to be parsed by `SugarSS`

**What is motivation or use case for changing the behavior?**
I want to use SugarSS. I want to use `preact-cli`. I do not know how.

**Comment by calebeby** [comment]
Using the following config I was able to use SugarSS in every file *except* for `src/style/index.css`. I'm not sure why only that file errored, and the rest were fine. However, I still had to name everything `.css` instead of `.sss`.

```js
import sugarss from "sugarss";

export default (config, env, helpers) => {
  helpers.getLoadersByName(
    config,
    "postcss-loader"
  )[0].loader.options = { parser: sugarss };
};
```

**Comment by fokusferit** [comment]
@calebeby for having the option to create a new project with sugarss support, maybe creating your own template repository might be helpful ? 

You would be able to set up .sss files and could add your preact.config.js script into it.

**Comment by developit** [comment]
Hi there - there are actually two PostCSS loaders you need to apply your modification to:

```js
import sugarss from "sugarss";

export default (config, env, helpers) => {
  helpers.getLoadersByName(
    config,
    "postcss-loader"
  ).forEach( rule => {
    rule.loader.options = { parser: sugarss };
  });
};
```
