### ISSUE TITLE
Error: callback() can only be called once. on install

### ISSUE THREAD

**Issue by joshuataylor** [developit/preact-cli#424]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Can't install.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ sudo npm install -g preact-cli
/usr/bin/preact -> /usr/lib/node_modules/preact-cli/lib/index.js

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/lib/node_modules/preact-cli/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> preact@8.2.6 postinstall /usr/lib/node_modules/preact-cli/node_modules/preact
> node -e "console.log('\u001b[35m\u001b[1mLove Preact? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/preact/donate\u001b[0m')"

Love Preact? You can now donate to our open collective:
 > https://opencollective.com/preact/donate

> simplehttp2server@2.0.0 postinstall /usr/lib/node_modules/preact-cli/node_modules/simplehttp2server
> node lib/install.js

/usr/lib/node_modules/preact-cli/node_modules/each-async/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/lib/node_modules/preact-cli/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at /usr/lib/node_modules/preact-cli/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/lib/node_modules/preact-cli/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/usr/lib/node_modules/preact-cli/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at endWritable (/usr/lib/node_modules/preact-cli/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at ConcatStream.Writable.end (/usr/lib/node_modules/preact-cli/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DuplexWrapper.onend (/usr/lib/node_modules/preact-cli/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:313:30)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/preact-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simplehttp2server@2.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simplehttp2server@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/josh/.npm/_logs/2017-11-04T09_39_06_331Z-debug.log
```

Debug log: https://gist.github.com/joshuataylor/da0521458d5e0e63f5f46d7d0dc291ed

**What is the expected behavior?**
Can install

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version
8.9.0
- npm version
5.5.1
- Operating system
Ubuntu 17.10

**Comment by robertcasanova** [comment]
It's a permission issue related to simplehttp2server. 
Please follow this guide: https://docs.npmjs.com/getting-started/fixing-npm-permissions

Quick fix:

` sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`
and
`npm i -g preact-cli`

**Comment by Snazzyham** [comment]
This fix didn't seem to work for me, I even tried changing npm permissions for the specific `/node_modules/` folder for my project directory, switching to an older version of node and using both yarn and npm.

I noticed that the folder does show up in my `/node_modules/` and I can use the package, it just doesn't add it to `package.json`.

**Comment by robertcasanova** [comment]
@Snazzyham If you install it globally (-g option) it will be added to your global node_modules folder not inside your project directory.

If install succeed and running `preact` doesn't find the executable probably the directory /bin with preact is not in your $PATH.

This should be the output:

`ls $(npm config get prefix)/bin | grep preact` returns `preact`
`echo $PATH | grep $(npm config get prefix)/bin` highlight the directory in your $PATH variable

If the second doesn't work you need to edit `~/.bash_rc` or `~/.zsh_rc` or whenever shell you use file to match that path.

For example add :

`PATH=$(npm config get prefix)/bin:$PATH`

Hope this helps.

R*

**Comment by joshuataylor** [comment]
DO NOT RUN THE ABOVE COMMAND, IT WILL BRICK SUDO.

`npm config get prefix` is `/usr/`, so this bricked my system.

**Comment by robertcasanova** [comment]
Not understand, what happens?

**Comment by joshuataylor** [comment]
It overwrites sudo with the current user, so can't sudo until you go into recovery mode, and change the permissions back to root. Not sure what other commands are broken.

**Comment by robertcasanova** [comment]
I've removed that part from comment. Sorry!

**Comment by digitalica** [comment]
the fix (https://docs.npmjs.com/getting-started/fixing-npm-permissions) worked for me.

Ubuntu 16.04, npm 5.6.0, node 8.7.0.

**Comment by 1beb** [comment]
To those people that brick their sudo: 

https://askubuntu.com/a/471503/2638

**Comment by mindplay-dk** [comment]
Finally managed to install it, after [fixing npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-two-change-npms-default-directory) as explained by @digitalica.

I've never had this problem with any package - `simplehttpserver2` apparently is pretty finicky.

@_developit would you perhaps consider switching to something a little less exotic like `express`, if that's possible? Is it important which server is used? It's just for development. Also ~230 fewer deps 🙄

**Comment by mindplay-dk** [comment]
> It's been removed for future versions

😄🎉
