### ISSUE TITLE
preact build error

### ISSUE THREAD

**Issue by nikhilbelchada** [developit/preact-cli#43]
Hello,
Getting SyntaxError on `preact build` while `npm start` works properly

```
Build [==================  ] 91% (1.9s) additional asset processing
  Total precache size is about 180 kB for 15 resources.

Template execution failed: SyntaxError: Unexpected token {
  SyntaxError: Unexpected token {
  
  - node.js:152 Object.require.extensions.(anonymous function) [as .js]
    [lib]/[preact-cli]/[babel-register]/lib/node.js:152:7
  
  - module.js:12 require
    internal/module.js:12:17
  
  - index.js:3 Object.<anonymous>
    [lib]/[preact-cli]/[postcss-modules-resolve-imports]/index.js:3:18
  
  - node.js:152 Object.require.extensions.(anonymous function) [as .js]
    [lib]/[preact-cli]/[babel-register]/lib/node.js:152:7
  
  - module.js:12 require
    internal/module.js:12:17
  
  - index.js:24 Object.<anonymous>
    [lib]/[preact-cli]/[css-modules-require-hook]/lib/index.js:24:22
  
  - node.js:152 Object.require.extensions.(anonymous function) [as .js]
    [lib]/[preact-cli]/[babel-register]/lib/node.js:152:7
```

**Comment by developit** [comment]
@nikhilbelchada You can circumvent this using `preact build --no-prerender`, but I'd like to figure out why that's happening. Are you using less or sass?

**Comment by juanpasolano** [comment]
I'm having the same issue. No less or sass but my error is 
```
bundle.js from UglifyJs
Unexpected token: punc ()) [bundle.js:5084,22]
```

`preact build --no-prerender` does not work either

```
$ node -v
v4.1.0
$ npm -v
4.4.1
```

**Comment by nikhilbelchada** [comment]
@developit I am not using less or sass, just trying to run the default app.

Steps I followed:
preact create my-great-app
cd my-great-app/
npm start
npm run build [error..]

**Comment by tiansijie** [comment]
seems like using the same node version of your preact-cli installed will solve the problem

**Comment by developit** [comment]
@nikhilbelchada are you also running Node v4?  I think most of our testing has been done on 6+.

**Comment by nikhilbelchada** [comment]
@developit yes i was on v4, now i updated to v6 and its working, so issue is specific to v4.

**Comment by lukeed** [comment]
We can run a pre/post-install hook & notify on version mismatch. Recent push in node CLI community to bite the bullet and enforce 6+ anyway since [4.x is no longer active LTS](https://github.com/nodejs/LTS#lts-schedule1).

**Comment by developit** [comment]
ahh brilliant - at least knowing it's a 4.x issue we can debug.

I'm actually thinking this is happening because Babel was never being run on those files - in Node 6 that didn't matter because it supports a decent amount of ES2015.  In node 4 it bails though.  It's like this gotcha:
https://github.com/babel/babel/tree/master/packages/babel-register#ignores-node_modules-by-default

**Comment by ds82** [comment]
@lukeed As long as a node LTS version is in maintenance it should be supported by libs & tools. That's the spirit of LTS anyway ..

**Comment by developit** [comment]
This will be fixed by switching SSR to use a webpack bundle.

**Comment by SaraVieira** [comment]
@rkostrzewski This can be closed too right ?

**Comment by reznord** [comment]
Ah! Here it is. Thought no one reported this issue. 

@lukeed do you remember the discussion between us regarding an error in `preact build`?

This is the one!
