### ISSUE TITLE
Build fails when uglifying material component script

### ISSUE THREAD

**Issue by ecirish** [developit/preact-cli#446]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**

`yarn start` works without error. `yarn build` and `yarn serve` fail with this same error.

**If the current behavior is a bug, please provide the steps to reproduce.**

It doesn't happen with out of the box configurations, but since it's dealing with a material design component, it feels like it could be related to the project:

on `yarn build`:
```
yarn run v1.3.2
$ preact build
Build [==                  ] 10% (0.1s) building modules(node:46019) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
✖ ERROR bundle.09240.js from UglifyJs
Unexpected token: name (MDCFoundation) [../node_modules/@material/base/foundation.js:21,6][bundle.09240.js:926,4]
Build failed!
error Command failed with exit code 1.
```

**Please mention other relevant information.**
- node version - `8.4.0`
- yarn version - `1.3.2`
- Operating system - OSX Sierrra.

**Comment by sydev** [comment]
I got a similar error:

`
✖ ERROR route-home.chunk.3d3d6.js from UglifyJs
Unexpected token: name (Card) [../node_modules/preact-material-components/Card/index.js:8,6][route-home.chunk.3d3d6.js:38,4]
✖ ERROR route-profile.chunk.75226.js from UglifyJs
Unexpected token: name (Profile) [./routes/profile/index.js:6,21][route-profile.chunk.75226.js:37,4]
✖ ERROR bundle.cc43e.js from UglifyJs
Unexpected token: operator (>) [../node_modules/preact-material-components/themeUtils/generateThemeClass.js:1,15][bundle.cc43e.js:166,61]
Build failed! null
`

`preact watch` doesn´t throw any errors, but `preact build` does

- node version: 9.7.1
- yarn version: 1.3.2
- OS: OSX Sierra

**Comment by mindrage** [comment]
@sydev The unexpected token: name (...) seems to go away to giving them the .jsx extension on default configurations. however, im yet to resolve the operator >
Might be that the template for preact-cli  "material" is wrongly configured for build?

**Comment by prateekbh** [comment]
looking into it

**Comment by prateekbh** [comment]
`operator >` is a bug on `preact-material-components` side, publishing a patch ASAP. upgrade to 1.3.9

**Comment by vijaybritto** [comment]
Same issue in my setup as well. Cannot play around the webpack config as there is no ```eject``` command in the cli.
Unexpected token errors keep coming up in various parts of the codebase. How to circumvent this error? Running with ```--no-prerender``` doesn't work too.

**Comment by prateekbh** [comment]
☝️ should fix this

**Comment by vijaybritto** [comment]
` ERROR route-home.chunk.df78c.js from UglifyJs
Unexpected token: name (ContentTypes) [../node_modules/msexcel-builder/lib/msexcel-builder.js:43,0][route-home.chunk.df78c.js:19724,23]`

This is the error I get. And the code where it fails is just this 
```javascript
ContentTypes = class ContentTypes {
```

**Comment by prateekbh** [comment]
@vijaybritto that is something that will not be fixed with it 😆 
looks like it comes from `msexcel-builder`

**Comment by vijaybritto** [comment]
It does not happen in dev build and the same file is being loaded there as well. This has something to do with the uglifyJs config in the prod build.

**Comment by prateekbh** [comment]
yeah, may be pmc is being used inside this or something. let me just publish the update in a day or two.

**Comment by prateekbh** [comment]
in case its not super blocking!

**Comment by prateekbh** [comment]
btw if it is super urgent, just use 

```import {Button,....} from 'preact-material-components'```

till then, its a full es5 export

**Comment by vijaybritto** [comment]
I'm not using pmc anywhere in my app. I'm taking out the webpack config into the project root folder and attempting to play with it!

**Comment by prateekbh** [comment]
are you using material template of `preact-cli` or some other one?

**Comment by vijaybritto** [comment]
preact-cli's 'default' template

**Comment by vijaybritto** [comment]
I fixed it by temporarily commenting out `exclude: '/node_modules/',` in the `webpack`-base-config.js file

**Comment by prateekbh** [comment]
to others please upgrade to pmc 1.4.1 in your `package.json`

**Comment by reznord** [comment]
@vijaybritto that is from a package which you are using as a dependency.
