### ISSUE TITLE
localhost being redirected to https

### ISSUE THREAD

**Issue by drKnoxy** [developit/preact-cli#451]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
1. Open Chrome
1. Run `yarn serve` click on the link to the https server.
1. Stop the server
1. Run `yarn dev`
1. You can't access the http server because you keep getting upgraded to https

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Not sure, i had to empty cache and reload the page per these instructions
https://stackoverflow.com/questions/25277457/google-chrome-redirecting-localhost-to-https

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version
- npm version
- Operating system: OSX

**Comment by developit** [comment]
I don't think there's anything we can do about this, it's just how redirects are cached.

**Comment by reznord** [comment]
Maybe, we can un-register the service-worker in `dev` mode?

Which means we need to check and un-register if there are any present before we start the dev server.

Any thoughts? /cc @ForsakenHarmony @lukeed @developit

**Comment by reznord** [comment]
> I don't think there's anything we can do about this, it's just how redirects are cached

can we check for the service-worker while running `preact watch` and if it is present, we can un-register the SW and delete it). 

What do you think @lukeed @developit ?

**Comment by ForsakenHarmony** [comment]
serve is gone in next anyways
