### ISSUE TITLE
Async routes cause warning when using `preact/debug`

### ISSUE THREAD

**Issue by jgierer12** [developit/preact-cli#456]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using `preact/debug` as recommmended in the [Preact readme](https://github.com/developit/preact#debug-mode), async routes cause the following warning to appear in the browser console:

```
Undefined component passed to preact.h()
<undefined path="/" url="/" matches="[object Object]" /> debug.js:17
```

The routes still work perfectly fine, but the warning is misleading and confusing.

I'm not sure if this is a bug in preact-cli's async loading strategy or preact itself, but I suspect the former.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `preact create default test`
2. `cd test`, `npm install`
3. Edit `src/components/app.js` as follows:
```diff
 import { Router } from 'preact-router';
 
+if (module.hot) {
+	require('preact/debug');
+}
+
 import Header from './header';
```
4. `npm run start`, open http://localhost:8080, open console with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd> (or your OS and browser's equivalent)
5. The above warning will appear in the console

**What is the expected behavior?**
No warning should be shown since everything works as expected

**Please mention other relevant information.**
- node version 8.9.1
- npm version 5.6.0
- Operating system Windows 10 1709

**Comment by alvis** [comment]
I also received the warning `Undefined component passed to preact.h()`, and therfore I am here. I'm not sure if the message is misleading, as there is indeed an undefined component. However, it appears to be a bug to begin with and should be properly handled.

**Comment by dsky1990** [comment]
same problem 
`Undefined component passed to preact.h()
<undefined path="/" url="/" matches="[object Object]" />`
`debug.js?834f:17 `

**Comment by dsky1990** [comment]
also happen in router changed

**Comment by divyanshutomar** [comment]
I am facing the same issue even if the route is not async.

**Comment by jgierer12** [comment]
@divyanshutomar I think all routes are async by default

**Comment by XavierLeTohic** [comment]
+1

**Comment by ForsakenHarmony** [comment]
That was not intentional, sorry

But yes all routes in `src/routes` are async by default

**Comment by joaocunha** [comment]
I still get this error if I run `preact watch` but not if I run `npm run start`.

**Comment by lukeed** [comment]
@joaocunha are you sure that both your local and global installations (if any) are up to date?

**Comment by joaocunha** [comment]
I am. Can't properly replicate, tho - it's intermitent. I'll try more and update this issue.
