### ISSUE TITLE
Invalid package name.

### ISSUE THREAD

**Issue by milesthedisch** [developit/preact-cli#466]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behaviour?**

Given a invalid package name preact is creating a package.json file with the an invalid package name.

**If the current behaviour is a bug, please provide the steps to reproduce.**

`preact create simple ./a-name-mistaken-for-a-path`
`cd ./a-name-mistaken-for-a-path`
`npm start`

```
npm ERR! Invalid name: "./a-name-mistaken-for-a-path"
```

**What is the expected behaviour?**

Preact should validate the name before generating files.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

This is a feature request, it kind of bugs me... thats really the only motivation.

**Please mention other relevant information.**
- node 8.9.3
- npm 5.5.1
- macOS Sierra, 10.12.6
- preact-cli 2.1.1

**Comment by ForsakenHarmony** [comment]
It's pretty easy to fix by just changing the name, but we could do that

**Comment by milesthedisch** [comment]
Im working on a PR now. @ForsakenHarmony, cant seem to get the tests suites to pass though. Happy to contribute :)

**Comment by reznord** [comment]
Hmm...tests aren't passing? 🤔 What's the error that you are getting?

**Comment by milesthedisch** [comment]
I did a fresh `rm -rf node_modules` and a  `yarn install`, and I'm getting this. @reznord 

![Uploading Screen Shot 2018-01-18 at 6.08.55 PM.png…]()

**Comment by reznord** [comment]
Aha! Can you please try it running once more? That is because of node-tar which we use for unzipping the template.

**Comment by milesthedisch** [comment]
@reznord Thanks! They are passing now. The tests are estimated to take `790s` to finish running!! Thats incredible 😆 ...

**Comment by reznord** [comment]
@lukeed is working on a PR where he is reworking on the tests. (available in `rework` branch)

**Comment by milesthedisch** [comment]
@reznord Still getting errors different ones though.

![screen shot 2018-01-18 at 6 35 27 pm](https://user-images.githubusercontent.com/6229386/35093829-6d604484-fc7e-11e7-8657-4b2ec771f2f9.png)

**Comment by lukeed** [comment]
Closed in #468
