### ISSUE TITLE
preact build --json fails with `TypeError: c.getModules is not a function`

### ISSUE THREAD

**Issue by jeberly** [developit/preact-cli#467]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
`preact build --json` fails with `TypeError: c.getModules is not a function`

**If the current behaviour is a bug, please provide the steps to reproduce.**
I made sure I have latest preact-cli and webpack, etc.  I created a new preact-cli app with `preact create default my-project` ran `preact build --json` got error.

**What is the expected behaviour?**
to actually output build stats json file

**Please mention other relevant information.**
- Node version
v9.4.0
- npm version
5.6.0
- Operating system
MacOS 10.13.2 (17C205)
- webpack version
3.10.0
- CLI version
preact-cli 2.1.1
- Browser

**Comment by PedroEsperanca** [comment]
I'm also getting this

**Comment by louisremi** [comment]
This looks a lot like a regression that occurred between 2.1.0 and 2.1.1
Today I realized my website wouldn't build on Netlify's CI while it was building fine locally. I was running react-cli 2.1.0 locally while Netlify was installing react-cli 2.1.1
I tried updating my local react-cli to 2.1.1 and the `TypeError: c.getModules` appeared. I downgraded immediatly after back to 2.1.0 and build worked as expected, both locally and on Netlify.

*Current workaround*: downgrade to react-cli 2.1.0

**Comment by ForsakenHarmony** [comment]
Yup, seems like `c.getModules` doesn't exist anymore, it's just `c.modules` now

**Comment by lukeed** [comment]
Anyone welcome to PR it! 😄 https://github.com/developit/preact-cli/blob/9a7dddef289c41d213e9aa6ba2cca20126a03ae0/src/lib/webpack/run-webpack.js#L139

**Comment by ForsakenHarmony** [comment]
Guessing you'd just remove the whole ternary operator and just replace it with `c.modules`

**Comment by reznord** [comment]
`mapModules` is still usable,  only `getModules` is deprecated. So I guess ternary is safe.
