### ISSUE TITLE
Lighthouse 2.80

### ISSUE THREAD

**Issue by mcaple** [developit/preact-cli#471]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behaviour?**

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version
- npm version
- Operating system
- CLI version
- Browser

Hi,
  You state that lighthouse returns 100% compatible. Just wanted to let you know that that does not appear to be the case with Lighthouse 2.80. Is it your intention to keep this percentage.

Thanks
Mark

**Comment by lukeed** [comment]
Thanks! We'll look into it since it's been a while. Lighthouse criteria changes every so often.

**Comment by reznord** [comment]
Hi @mcaple I ran a lighthouse test on https://clidemo.preactjs.com/ and I get a 💯PWA score. 

<img width="1680" alt="screen shot 2018-03-28 at 9 26 35 am" src="https://user-images.githubusercontent.com/3415488/38008041-213d77ee-326a-11e8-8951-1d9f7cf382c7.png">

Note: Run the lighthouse audit in incognito window for apt results, or else your extensions might effect the lighthouse scores
