### ISSUE TITLE
Request for supersimple template

### ISSUE THREAD

**Issue by bestwestern** [developit/preact-cli#478]
Is it possible to get a supersimple template with the absolute basic (no service worker, icons etc)

I tried the simple, build it and deployed it to 
https://build-hdqxfhiann.now.sh/ 77kb transferred:
![image](https://user-images.githubusercontent.com/3617433/35736425-5145defc-0828-11e8-8212-89db28c0db37.png)

**Comment by developit** [comment]
Service Worker is something preact-cli does unrelated to the template. You can turn it off via the `--no-serviceworker` flag.  

You might find it worthwhile to skip using `preact create` if you're looking for something really simple:

```sh
mkdir demo && cd $_   // create folder
git init && npm init -y   // initialize git & npm
npm i -D preact-cli     // install the CLI
echo "export default () => (<h1>Hello, World</h1>)" > index.js
$(npm bin)/preact watch
```

**Comment by bestwestern** [comment]
Thank you very much. That was dumb of me not to try that from the readme file :-/

i tried setting the --no-serviceworker flag and it got much better,
but how come it uses 4.5 kb? (preact is about 3kb)

![image](https://user-images.githubusercontent.com/3617433/35780673-5f3b2f0e-09df-11e8-9027-374dbf0253a9.png)

**Comment by lukeed** [comment]
There's `preact-router` in there & some extra logic to handle async/fetching routes once your app starts growing.

**Comment by bestwestern** [comment]
I see! I didn't think it would be included when it wasn't imported. 

In that case - is it possible to avoid including the router?

**Comment by ForsakenHarmony** [comment]
I think it might actually be `preact-compat`?

**Comment by developit** [comment]
Hmm - when I follow the steps, I get a 3.8kb app. That makes sense, you have 3.3kb of Preact and then around 500b of app code + webpack (for things like setting up module boundaries and split point loading).

**Comment by bestwestern** [comment]
Very strange.
I am sorry, I am having trouble with those flags. 
Could you please write your last step:
- preact create simple app
- cd app
- ?

**Comment by bestwestern** [comment]
Argh - what tricked me is that when building with no service-worker the sw file is still created, it is just not used.
These worked:
- npm run build -- --service-worker false
- preact build --service-worker false

But my build folder looks like this 
![image](https://user-images.githubusercontent.com/3617433/35916237-0ae7d358-0c0a-11e8-91a9-73570f293285.png)

Is that the same as yours @developit ? (If so, the 3.8 kb you're getting is a deployment/gzipping thing?)
@lukeed I don't think the router is included? (remember this is the simple template)

PS: Thank you very much for taking the time for answering questions. I would like to add a few lines of example commands to the readme file, to (literally) foolproof it, so other dumbasses like me don't take up your time (You must be busy now at Google (congrats on that) ;-)

**Comment by ForsakenHarmony** [comment]
Yes, the 3.8kb are gzipped

**Comment by bestwestern** [comment]
@ForsakenHarmony thank you - how do you see the size before deploying it?

**Comment by developit** [comment]
Sorry for missing this thread @bestwestern! I definitely see the need for some readme explanations here, and we can probably address some of the confusing bits with tweaked defaults.

For anyone finding this - A nice quick way to see the gzipped size of a file on disk is [gzip-size-cli](https://npm.im/gzip-size-cli):

```js
npm i -g gzip-size-cli

gzip-size dist/bundle.2b3ef.js
```

**Comment by bestwestern** [comment]
Awesome - thanks @developit .
