### ISSUE TITLE
Installing dependenciesError: Exited with status 181

### ISSUE THREAD

**Issue by bringmethecode** [developit/preact-cli#480]
I'm trying to create a new project using the Linux Subsystem for Windows 10, but I get this error:

> Installing dependenciesError: Exited with status 181

What does that error means? I believe there is a bug present in WSL when using NPM in a mounted drive, the workaround is to install npm packages with the option `--no-bin-links`, if the error is related to that, is there a way to pass that argument into preact create process?

**Comment by ForsakenHarmony** [comment]
Do you have a fix, or why did you close it?

**Comment by bringmethecode** [comment]
Hello ForsakenHarmony, sorry for the late reply... Well I found out even in spite of getting that error files are keep in the project folder, inside I can do npm i --no-bin-links and everything is fine! I also thought this is more of a Subsystem issue (that has several months?).

**Comment by ForsakenHarmony** [comment]
Oh, alright, I'm not sure about that I don't use the subsystem much

**Comment by bringmethecode** [comment]
I was getting too many issues with node so I stopped using it, I haven't had a single issue with preact since then :D
