### ISSUE TITLE
Yarn workspaces

### ISSUE THREAD

**Issue by vvo** [developit/preact-cli#482]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
When preact-cli used inside a Yarn workspace project like:

```
project/
  - src/
    - preact-cli-project/
    - some-lib/
```

Then dependencies are installed at `project/node_modules` while the [webpack-base-config](https://github.com/developit/preact-cli/blob/741922b82697c7e33597e104453bbd1536c21f3a/src/lib/webpack/webpack-base-config.js) will only look for dependencies in project/src/preact-cli-project/node_modules/preact-cli/node_modules or project/src/preact-cli-project/node_modules.

**What is the expected behaviour?**

When stored inside a yarn workspace, it should work.
 
One way to solve this is to create `project/src/preact-cli-project/preact.config.js` with this content:

```js
const path = require('path');

module.exports = function(config) {
  config.resolveLoader.modules.push(
    path.join(__dirname, '..', '..', 'node_modules')
  );
};
```

Ultimately we could solve it automatically with https://github.com/square/find-yarn-workspace-root

WDYT?

**Comment by marvinhagemeister** [comment]
As a workaround installing with yarn via the `nohoist` option should do the trick. See https://yarnpkg.com/blog/2018/02/15/nohoist/ . Although I'd be nice if this would work out-of-the-box, I'm not sure if it's a good idea to add code specific to package managers. We're likely not the only one hitting this issue and implementing a fix or different strategy in yarn would be more beneficial.

**Comment by ForsakenHarmony** [comment]
fixes in next
