### ISSUE TITLE
build problem with sass/scss

### ISSUE THREAD

**Issue by stasusov** [developit/preact-cli#49]
Hello. 
It is just not working.
I've tried .scss, .sass files, but builder fails with error message

`Template execution failed: Error: Cannot find module './style' ...`

.less files with (and without) -l option is working fine

Am I doing something wrong?

**Comment by developit** [comment]
Hmm - there were some folks working on a scss template, I wonder if they ran into this as well?

**Comment by rkostrzewski** [comment]
@stasusov do you have ```style/index.scss``` file (or .sass)? If so you can just change your import from ```import style from './style'``` to ```import style from './style/index.scss'```

Keep in mind that prerendering won't work currently with SASS and you'll have to run build like so: ```preact build --no-prerender``` or ```npm run build -- --no-prerender```

**Comment by stasusov** [comment]
@rkostrzewski I have faced with the same issues as described in #59, so this issue can be closed as duplicate.

**Comment by lukeed** [comment]
Thanks @stasusov ! We appreciate the report anyway 😄
