### ISSUE TITLE
Console error after creating project from default template.

### ISSUE THREAD

**Issue by raulchedrese** [developit/preact-cli#492]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
A freshly created project has console errors.

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. Create a new project `preact create default my-project`
2. Run `npm start` in the project directory.
3. Access `http://localhost:8080` in a web browser.

The following error appears in the browser dev tools console:
`Undefined component passed to preact.h()
<undefined path="/" url="/" matches="[object Object]" />`

**What is the expected behaviour?**
No console errors

**Please mention other relevant information.**
- Node version
**9.5.0**
- npm version
**5.6.0**
- Operating system
**macOS 10.13**
- CLI version
**2.1.1**
- Browser
**Chrome and Safari**

**Comment by lukeed** [comment]
This was addressed in #484 & I believe it solves this error too. The patch hasn't gone out yet, but if you could verify for us that this fixes your error, that'd be great! Thanks!

**Comment by reznord** [comment]
I guess it is fixed in v2.1.3 (latest patch release)

**Comment by DiegoGLagash** [comment]
Have updated and still same issue with 2.1.3.

**Comment by lukeed** [comment]
@DiegoGLagash I would clear cache and install everything again. Make sure you're updating global install if you have it too.

**Comment by DiegoGLagash** [comment]
Confimed. It works after upgrading global installation. Thanks !
