### ISSUE TITLE
`preact build --prerender` blows up with nvm?

### ISSUE THREAD

**Issue by scottmas** [developit/preact-cli#5]
I use [nvm](https://github.com/creationix/nvm) and `preact build --prerender` blows and does not build to the build directory. I get this error:
```
/Users/sashton/.nvm/versions/node/v7.8.0/lib/~/preact-cli/lib/lib/entry.js
Module not found: Error: Can't resolve 'preact' in '/Users/sashton/.nvm/versions/node/v7.8.0/lib/node_modules/preact-cli/lib/lib'
```
Plus lots of other output. Is the app directory resolution breaking somehow? Somehow it's trying to fetch the version of Preact installed for the global `preact-cli` instead of the local application `preact'

**Comment by developit** [comment]
Ah looks like we are missing some parameters to module-alias. Good catch.

**Comment by rkostrzewski** [comment]
@scottmas do you still experience the problem? I'm using `preact build` in nvm without any problems. If there are any #133 should take care of them.

**Comment by reznord** [comment]
It is working fine for me.

**Comment by scottmas** [comment]
Yep, success! Thanks all
