### ISSUE TITLE
[QUESTION(s)] How to await for fetch/http request before render?

### ISSUE THREAD

**Issue by johhansantana** [developit/preact-cli#502]
I come from using NextJS and I'm not sure if there's a different method here or how it works but I was assuming if you used `async componentWillMount()` you could await for http requests and what not but this is not the case since it will fail to build when you run `preact build` #17 

What is the workarounds for this?
Best practices?
Does it affect SEO, for example, a blog post title, image and description will not be fetched until the http request returns data.
How does this compare vs how NextJS works?

Any info I'll appreciate. Thanks!

**Comment by ForsakenHarmony** [comment]
it's generally recommended to be able to render without data and to use `componentDidMount`

react is deprecating `componentWillMount`, because it will be executed before render which could error and then never call `componentWillUnmount`

**Comment by johhansantana** [comment]
I see, so this would only prerender the links. Thanks, I think I have a better understanding of what to use preact-cli for.
