### ISSUE TITLE
How to use CSSTransition?

### ISSUE THREAD

**Issue by bringmethecode** [developit/preact-cli#505]
If I'm right, the default template already comes with preact-compat and the webpack aliases for 'react' and 'react-dom'. That means the library should without modifying anything?

This is my component:

``` 
import { CSSTransition } from 'react-transition-group'

...

  return(
    <CSSTransition
        classNames={{
          enter: `${style.enterAnimation}`,
	  enterActive: `${style.enterActiveAnimation}`,
	  leave: `${style.leaveAnimation}`,
	  leaveActive: `${style.leaveActiveAnimation}`
	}}
	in={trans}		
        timeout={500}
    >
     {children}
    </CSSTransition>
)
```

styles:
```
.enterAnimation {
	padding-top: 400px;
}
.enterActiveAnimation {
	padding-top: 200px;
}
.leaveAnimation {
	padding-top: 400px;
}
.leaveActiveAnimation {
	padding-top: 200px;
}
```
And this is the rendered component in React dev tools:

![screenshot from 2018-02-22 12-29-26](https://user-images.githubusercontent.com/13294924/36557152-0c30d2fe-17cd-11e8-86d5-d399a82591e6.png)

But the animation doesn't seems to work, am I doing something wrong? thanks~

**Comment by developit** [comment]
You need to define the `transition` property in CSS in order to use CSSTransition:

```js
.enterAnimation, .leaveAnimation {
  transition: padding-top 500ms ease;
}
```

**Comment by bringmethecode** [comment]
Hello, thanks for taking the time to help. Unfortunately adding that property doesn't change anything. I think it has something to do with the way the component is been rendered.

https://github.com/bringmethecode/preact-csstransition-test

I have created a test repo with the simple template, the transition has a timeout of 5 seconds, but you can see almost immediately that the children is assigned with the **rect-test-entered** class (class is assigned by 'rect-test-${status}').
