### ISSUE TITLE
Devcert cannot be found

### ISSUE THREAD

**Issue by jollyalvin** [developit/preact-cli#506]
Hi,

I am still messing around with preact-cli and I somehow deleted the preact-cli devcert in the windows certificates. With that every time I run "yarn serve" it displays this in the bash terminal and my chrome now cannot find the certificate.

```
$ yarn serve
yarn run v1.3.2
$ preact build && preact serve
Build [==================  ] 91% (1.4s) additional chunk assets processing
  Total precache size is about 143 kB for 14 resources.
Setting up SSL certificate (may require sudo)...
  Listening on https://localhost:8080...
  Processing rewrites failed: Invalid hosting.header extglob **/*.chunk.*.js: error parsing regexp: missing closing ]: `[^\]*\.chunk\.[^\]*\.js$`
  Processing rewrites failed: Invalid hosting.header extglob **/*.chunk.*.js: error parsing regexp: missing closing ]: `[^\]*\.chunk\.[^\]*\.js$`
  Processing rewrites failed: Invalid hosting.header extglob **/*.chunk.*.js: error parsing regexp: missing closing ]: `[^\]*\.chunk\.[^\]*\.js$`
  Processing rewrites failed: Invalid hosting.header extglob **/*.chunk.*.js: error parsing regexp: missing closing ]: `[^\]*\.chunk\.[^\]*\.js$`
  Processing rewrites failed: Invalid hosting.header extglob **/*.chunk.*.js: error parsing regexp: missing closing ]: `[^\]*\.chunk\.[^\]*\.js$`
  Processing rewrites failed: Invalid hosting.header extglob **/*.chunk.*.js: error parsing regexp: missing closing ]: `[^\]*\.chunk\.[^\]*\.js$`
  Processing rewrites failed: Invalid hosting.header extglob **/*.chunk.*.js: error parsing regexp: missing closing ]: `[^\]*\.chunk\.[^\]*\.js$`
```

This is what it looks now on my browser

![image](https://user-images.githubusercontent.com/9584631/36619442-cd240744-1929-11e8-9643-d0a8b49ce78d.png)
This is the preact app sample I created just now to check if this will affect on other "preact create" project and it did.

**Question**: How I can regenerate the cert key again and install it on my local machine just like how it automatically installed when I first run "yarn serve"? I think this will fix the issue :|

I know this is my fault for deleting the cert key but I was just curious if I setup the cert correctly when firefox automatically opens and prompted me about it. I assumed that if the certificate was deleted I will somehow see the firefox cert installation again.

**Comment by developit** [comment]
Delete the certificates from `%LOCALAPPDATA%/devcert`

**Comment by reznord** [comment]
Another thing worth mentioning here is: the auto generated devcert is not secure and it will be creating issues while running `serve` command and testing lighthouse scores locally

**Comment by jollyalvin** [comment]
> Delete the certificates from `%LOCALAPPDATA%/devcert`, then run `yarn serve`
