### ISSUE TITLE
NPM ERROR

### ISSUE THREAD

**Issue by hui55** [developit/preact-cli#507]
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
---
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0

**Comment by hui55** [comment]
When I execute npm list -g --depth=0 this error is listed twice:
> npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0

**Comment by bboydflo** [comment]
I got the same error

**Comment by bboydflo** [comment]
I have tried the same in windows and it works without any problems.

**Comment by developit** [comment]
See this issue:
https://github.com/epoberezkin/ajv-keywords/issues/56

**Comment by bboydflo** [comment]
somebody pointed that that might be an npm issue. try to update `sudo npm install -g npm` might help.

**Comment by reznord** [comment]
It is generally not recommend to use npm with sudo

**Comment by lucaseverett** [comment]
Just a note for anyone else having this problem: Using "yarn global add preact-cli" installs without this error.

**Comment by luxcium** [comment]
Is this issue include the problem I have in (https://github.com/developit/preact-cli/issues/74) and repeated in (https://github.com/developit/preact-cli/issues/56) about the circular problem of :

`installing ajv@^6.0.0 gives this error -> ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0`

and 

`installing ajv@^5.0.0 gives this error -> ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0`

using a mac with `npm -v  = 6.4.1`

@babel/cli = v. 7.1.2
@babel/core =  v. 7.1.0
webpack = v. 4.19.1
typescript-eslint-parser = v. 20.1.1

**Comment by pldg** [comment]
I've the same problem.

`npm install -g preact-cli` prompt some warnings:

```sh
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/preact-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

If I run `npm list -g --depth=0` print two errors:

```sh
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.1
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.1
```

Any solution (without using yarn)?

**Comment by ForsakenHarmony** [comment]
https://github.com/epoberezkin/ajv/issues/708#issuecomment-373881888

Still an npm issue?
