### ISSUE TITLE
What does this '(0, _path.resolve)(env.src, position.source)' means?

### ISSUE THREAD

**Issue by ccontreras** [developit/preact-cli#508]
Hi @developit, I have been digging into the code of the project and I've came across with this statement:

`(0, _path.resolve)(env.src, position.source)`

Could you explain what are the pros of this?

Thank in advance.

**Comment by ForsakenHarmony** [comment]
it's from babel

**Comment by lukeed** [comment]
Yup yup. I think what you're looking at is originally [this line](https://github.com/developit/preact-cli/blob/ae50aaddd18797db4cc9e7d3e281b8b812dac0ad/src/lib/webpack/prerender.js#L61)

Babel + Webpack compilation uglies it a bit in order to safely handle import statements & whatnot. 😄
