### ISSUE TITLE
Trying use @babel/plugin-syntax-optional-chaining

### ISSUE THREAD

**Issue by feliperohdee** [developit/preact-cli#510]
Hey there,

I'm trying to include @babel/plugin-syntax-optional-chaining in my project, after install it, I've added to preact.config.js:

```
const babelLoader = helpers.getLoadersByName(config, 'babel-loader')[0];

babelLoader.rule.options.plugins.unshift(require.resolve('@babel/plugin-syntax-optional-chaining'));
```

and tested with the following code:

```
export default function() {
	const a = {
		b: 1
	};

	return (
		<h1>{a?.b}</h1>
	);
}
```

the expected babel behaviour is convert:

`a?.b -> a && a.b`

but the following error has been returning:

```
✖ ERROR ./src/components/App.js
Module build failed: SyntaxError: Unexpected token (7:9)

   5 |
   6 | 	return (
>  7 | 		<h1>{a?.b}</h1>
     | 		       ^
   8 | 	);
   9 | }
  10 |
```

Someone can help me? Thanks

**Comment by ForsakenHarmony** [comment]
you might want https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-optional-chaining

**Comment by feliperohdee** [comment]
that package looks to have support only for babel 7 and after, preact-cli need to be updated to newest versions, I'm keep using lodash/get , closing for now!

**Comment by reznord** [comment]
> that package looks to have support only for babel 7

yes, optional chaining support is available from babel 7 onwards only.

> preact-cli need to be updated to newest versions

we are waiting for the stable version release. Once that comes out, we will be updating it 😄

**Comment by feliperohdee** [comment]
good to know! thank u
