### ISSUE TITLE
Enable module/nomodule support

### ISSUE THREAD

**Issue by prateekbh** [developit/preact-cli#511]
__Feature request__

With babel 7 comes the support of babel-env support of modules.

This automatically produce bundles with ESM. Also, browsers support `<script type=module`

`preact-cli` should add support for this and babel 7 out of box, as this will help reduce bundle sizes even further down and amazing lighthouse scores.

[Quick reference](https://jakearchibald.com/2017/es-modules-in-browsers/)

**Comment by John0x** [comment]
Is there currently a way to hack preact-cli into using Babel 7?

**Comment by prateekbh** [comment]
It'll need a lot of internal changes so I am not sure. More word from @lukeed  @reznord

**Comment by prateekbh** [comment]
Added in next version
