### ISSUE TITLE
Error when using material template

### ISSUE THREAD

**Issue by tschnoelzer** [developit/preact-cli#513]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
when creating a new material template project with preact-cli, the web app produces error when running on http server.

**If the current behaviour is a bug, please provide the steps to reproduce.**
- preact create material demo
- cd demo
- yarn
- npm run build
- cd build
- http-server  (npm install http-server -g)
- call web app on 127.0.0.1:8081

error:
Uncaught Error: mdc-drawer--temporary class required in root element.
    at e.init (foundation.js:72)
    at e.init (foundation.js:54)
    at e.t (component.js:49)
    at new e (index.js:24)
    at Function.e.attachTo (index.js:26)
    at e.componentDidMount (index.js:34)
    at _ (preact.min.js:1)
    at m (preact.min.js:1)
    at R (preact.min.js:1)
    at a (entry.js:20)

**What is the expected behaviour?**
no error like when running in npm run dev or npm run start

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version 9.5.0
- npm version 5.6.0
- Operating system MacOS
- CLI version 2.2.1
- Browser chrome

**Comment by prateekbh** [comment]
@tschnoelzer so sorry you are facing this with preact-material-components 1.3.6. 
please install version 1.3.5 of preact-material-components, we will release 1.3.7 in a day or two which should fix this
