### ISSUE TITLE
Analytics in our cli commands

### ISSUE THREAD

**Issue by prateekbh** [developit/preact-cli#514]
It might be a good idea to put node-google-analytics in our commands. 

It'll give us good insights on the cli usage and other things, what kind of config ppl are using, pain points, insights into templates etc.

**Comment by ForsakenHarmony** [comment]
as long as we use something that doesn't have 100 sub dependencies

**Comment by vutran** [comment]
This should be an opt-in only features as I'm there's a large group of people using this tool internally and would rather keep their usage private.

**Comment by lukeed** [comment]
+1 to both points~!

If we were to go this route, something like this:

```js
const http = require('http');
const UA = 'UA-XXX...';

function track(command, result, label) {
  // argv from somewhere else
  if (argv.private || OFFLINE) {
    return; // aka, --private or no outbound
  }
  let k, opts = { aip:1, ec:command, ea:result, el:label };
  let url = `https://www.google-analytics.com/collect?v=1&tid=${UA}&t=event`;
  for (k in opts) {
    !!opts[k] && (url += `&${k}=${encodeURIComponent(opts[k)}`);
  }
  return http.get(url);
}
```

**Comment by addyosmani** [comment]
Back when we created Yeoman, we published https://github.com/yeoman/insight as a way to gather opt-in anonymous usage stats from your CLI users. Plumbs back to Google Analytics and works well with existing events dashboards pretty okay:

![image](https://user-images.githubusercontent.com/110953/36957193-98fb1e02-1fe7-11e8-8cda-4d57b15fcac6.png)

Just another option as you're evaluating :)

**Comment by reznord** [comment]
Adding this for commands would be a lot helpful. Will probably give this a try today and see how it goes.

Thanks Addy 😄

**Comment by developit** [comment]
Definitely interested in this. I can set us up a shared GA account.
