### ISSUE TITLE
Expose commands and node modules

### ISSUE THREAD

**Issue by prateekbh** [developit/preact-cli#515]
A lot of testing tools need to spin up servers, build code in travis like sandboxes etc.

It might be helpful to expose our commands as node modules so they can be required and executed from inside `js` files.

example usecase

- Visual diff testing with pupeteer

**Comment by developit** [comment]
strawman:

```

import { build, watch } from 'preact-cli';

build(dir, options).then( ... )

watch(dir, { ...options, onBuild }).then( ... )
```
