### ISSUE TITLE
Docs for new users: where is the HTML template?

### ISSUE THREAD

**Issue by dandv** [developit/preact-cli#516]
I'm new to Preact and preact-cli and can't seem to find out how (where) to add a `<script>` to use a CDN-hosted library. Where's the `<body>` section of the HTML?

I ran `preact create material myapp`, but can't see where `style/index.css` or `manifest.js` are loaded from. The latter is visible if I *View source* while running the dev server, but I don't see how the stylesheet is loaded.

After (IMO too) much digging, it seems the underlying issue is #428. Until that's solved, can we document how to change the HTML template? Or is this an issue with @prateekbh's [`preact-material-boilerplate`](https://github.com/preactjs-templates/material) rather?

**Comment by prateekbh** [comment]
oh yes, you can copy paste this in your project for now: https://github.com/developit/preact-cli/blob/52e9843bdd0218d563df756391c6414fabf8c2c3/src/resources/template.html

then, use --template flag to point to the pasted file

e.g.: https://github.com/prateekbh/preact-material-components/blob/master/docs/package.json#L8

**Comment by dandv** [comment]
Any updates on making the HTML template more easily accessible? Seems like a pretty common requirement, e.g. to add `meta` tags to the HTML; or is there a better practice for that sort of thing?

**Comment by prateekbh** [comment]
@developit @lukeed @reznord  for more visibility

**Comment by lukeed** [comment]
Honestly I can't remember if the next version has it included yet or not, but we can easily do it.

For now you can just do something like this:

```sh
# copy the template into "src/template.html"
$ cp node_modules/preact-cli/lib/resources/template.html src/.
```

Then update both `watch` and `build` commands with a `--template src/template.html` as @prateekbh mentioned above.

**Comment by ForsakenHarmony** [comment]
#705
