### ISSUE TITLE
Template with markdown pages

### ISSUE THREAD

**Issue by bronze** [developit/preact-cli#517]
Hi there.
Im trying to learn react/preact and starting with the templates and examples but trying to follow preact-www is proving a bit too much with the plethora of dependencies.
Ive imported the modules and packages from the preact-www example but some things got me stumped still (importing css with ~ doesnt work, and now ive got a cannot GET /content/index.md).
BTW, this is what i got so far (a lot of loose ends, please be kind) https://github.com/bronze/preact-markdown

**What is the expected behaviour?**
A beginner template to pull content from /content/*.md files.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
Easing people into preact from static files.

Thank you for your attention.

**Comment by developit** [comment]
I wonder if a "blog template" powered by markdown would be worthwhile?

**Comment by reznord** [comment]
Not really sure till what extent that would help! Instead we can make an series of FAQ page which can address these kids of things.

**Comment by bronze** [comment]
@developit i would certainly be happy with it! pulling md content and making child pages (like /about/theteam) were the things i was trying to understand how better to do with react/preact

**Comment by proob** [comment]
Hey, 
is there any FAQ/instruction or minimal example on how to prerender markdown files to routes and pages using Preact? (ideally creating routes basing just on `content` folder, with internationalization)

I've been strugling with this problem for many days now, googling and trying and still couldn't find a clear way.
preact-www is really very stuffed with many features which may seem a bit complex for new commers (like me). Minimal instructions, example or template would be really useful.

If you have some other source which a bit explains it please provide a link.

**Comment by prateekbh** [comment]
btw https://github.com/preactjs-templates/netlify is one such template
