### ISSUE TITLE
Prerender on Chrome duplicates and orphans <embed> elements instead of replacing

### ISSUE THREAD

**Issue by jennydaman** [developit/preact-cli#518]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behaviour?**

I have a full demonstration here: [jennydaman/preact-cli-pdf](https://github.com/jennydaman/preact-cli-pdf/blob/master/index.js)

The code explains itself. Basically, I have `<embed type="application/pdf">` which displays `state.fname`. `state.fname` can be changed by buttons. If you alternate between the buttons twice, instead of re-rendering `<embed>`, **a new element is created and appended to the document.**

**If the current behaviour is a bug, please provide the steps to reproduce.**

```bash
# 1. create project
preact create simple preact-pdf --git --yarn
# 2. add code
# 3. build
preact build --dest docs --production --prerender
```

The demo is served from the docs folder by Github Pages. https://jennydaman.github.io/preact-cli-pdf/
I modified the output `index.html` so that it uses relative file names instead of absolute paths. This was necessary because Github Pages for projects does not serve files from `/`.

**What is the expected behaviour?**

`<embed>` should be replaced whenever a button is clicked, and no new `<embed>` elements should ever be created.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

| program | version |
|----------|---------|
| node  | 9.7.1 | 
| npm | 5.7.1 |
| yarn | 1.3.2 |
| Operating system | Arch Linux 4.15.6-1-zen |
| preact-cli | 2.2.1 |
| browser | Chromium 64.0.3282.186 |

**Comment by jennydaman** [comment]
This bug seems to be specific to Chromium (on the desktop), works fine on Firefox 58.0.2

**Comment by jennydaman** [comment]
More testing: not an issue with React nor Preact without preact-cli).

**Comment by jennydaman** [comment]
I found a pretty good workaround for myself. Chrome is confused by prerender, so the problem is avoided by preventing prerendering of `<embed>` elements (that will change). 

```jsx
render() {
  return (
    <div>
      {state.fname ? <embed src={state.fname} type="application/pdf" height="600" width="100%" /> : ''}
    </div>  
  )
}
```

**Comment by developit** [comment]
I think we might have a bug in `preact-render-to-string` - if you notice in the pre-rendered HTML, the `<embed>` tag is never closed :o

**Comment by ForsakenHarmony** [comment]
but not in `preact-cli`?

**Comment by jonk83** [comment]
6442515
