### ISSUE TITLE
Clicking preact router link to page from nav displays blank page until browser is refreshed (prod only)

### ISSUE THREAD

**Issue by RikuVan** [developit/preact-cli#519]
**Do you want to request a *feature* or report a *bug*?**
Seeking advice how to address this difficult bug, and perhaps document this issue for other users who encounter the same. Not sure if this should be posted in preact-router.

**What is the current behaviour?**
This issue is has only shown up in the production build hosted on firebase (https://www.webdevandsausages.org/). Occasionally a user clicks a nav link and the page is blank, only rendering after a refresh. Might this indicate that the service worker is involved in the problem (built with no-prerender flag)? Just disabled the sw.js in firebase but is still active here: https://tasteless-drug.surge.sh/. 

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. arrive at the main page in firebase. 
2. click a preact router link in the nav to another page ('about' or 'registration')
3. url changes but page is blank
4. refresh and page renders
(there has also been one report of arriving at a blank page)
I have tried to reproduce the exact conditions but so far have been unsuccessful. As mentioned, it does not occur in the development environment. I disabled the service worker this week and have not heard new bug reports yet.

**What is the expected behaviour?**
Pages renders normally with preact router with a service worker active.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
Seeking advice

**Please mention other relevant information.**
- Operating system: at least mac and windows
- CLI version: latest
- Browser: the issue has occurred in chrome and firefox

**Comment by RikuVan** [comment]
I was able to reproduce this once by adding the service worker back, letting it register, then pushing new code with an updated service worker and the navigating to a new page with the nav. So it seems to be something to do with the registering and unregistering. Perhaps I can add a notification of new content, asking the user to hard refresh. But this seems only a partial fix as they could ignore the notification.

**Comment by developit** [comment]
@RikuVan are you still having this issue?  I couldn't seem to reproduce it on your site.

**Comment by RikuVan** [comment]
I just removed the service worker from the prod build, which seems to eliminate the bug. I think it was happening when the service worker was updated but I couldn't figure out more. Of course i would prefer to keep the sw.js there. Anyways, feel free to close at this point since I don't have a good demo of the bug.
