### ISSUE TITLE
Adding webpack loader results in typeerror, because module.rules is undefined

### ISSUE THREAD

**Issue by NicolaiSchmid** [developit/preact-cli#528]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behaviour?**
I'm trying to integrate a new loader into the webpack rules chain, with this snippet inside `preact.config.js`
```javascript
config.module.rules.push({
    test: /\.html$/,
    use: [
        { loader: 'babel-loader' },
        { loader: 'polymer-webpack-loader' }
    ],
});
```
Running `npm start` or `yarn start` results in the following error:  
`TypeError: Cannot read property 'push' of undefined`  
Inside the default function of the configFile the `config.module.rules` array appears to be undefined but setting the object directly (`config.module.rules = [...]`) results in a lot of other webpack errors, because I'm replacing the preconfigured loaders.
**If the current behaviour is a bug, please provide the steps to reproduce.**
Just install `polymer-webpack-loader` and use this `preact.config.js`:
```javascript
export default function (config, env, helper) {
    config.module.rules.push({
        test: /\.html$/,
        use: [
            { loader: 'babel-loader' },
            { loader: 'polymer-webpack-loader' }
        ],
    });
}
```
BTW, using NPM or yarn results in the same error
**What is the expected behaviour?**
I hope it would just add the new loader for HTML files
**Please mention other relevant information.**
- Node version: 9.4.0
- npm version 5.6.0
- yarn version 1.5.1
- Operating system Ubuntu 17.10
- CLI version 2.2.1
- Browser Chrome v65

**Comment by lukeed** [comment]
We're using the [old(er) syntax](https://github.com/developit/preact-cli/blob/master/src/lib/webpack/webpack-base-config.js#L73) still, so you have to use `module.loaders` instead of `module.rules`.

This will be updated in the next major release, as we'll likely be moving to Webpack 4!

**Comment by NicolaiSchmid** [comment]
Awesome! Thanks!

**Comment by lukeed** [comment]
You bet!
