### ISSUE TITLE
'Empty cache and hard reload' in Chrome crashes demo site

### ISSUE THREAD

**Issue by bestwestern** [developit/preact-cli#53]
https://cli-demo.preactjs.com/profile/john 
I don't know if this is an issue/bug I am curious why it happens (I know think it is a bug because if I just opens this link in private mode it crashes):
(in Chrome, have the developer tools open and then right click on the reload button)
![image](https://cloud.githubusercontent.com/assets/3617433/26389504/8cae0762-405a-11e7-89cf-e95522ebc569.png)

**Comment by prateekbh** [comment]
I guess its mostly because there is no server side router to handle any other route than `/`.

Please try the same on home page, should work fine

**Comment by bestwestern** [comment]
I would think it should be possible to send 'deep links' to others, that have not visited the site.
If I would show Johns profile to someone who hasn't seen the site before, sending him this should work (but doesn't)
https://cli-demo.preactjs.com/profile/john

**Comment by snc** [comment]
Looks like a configuration issue on the web hosting, this should be rewritten internally to `index.html` then it should work.

**Comment by prateekbh** [comment]
my knowledge about hosting infra ends here, handing this one over to @developit

**Comment by prateekbh** [comment]
@developit just to give you in a gist, can we re-route all the routes like `/profile` `/profile/*` to index.html with the hosted website?

**Comment by thangngoc89** [comment]
@prateekbh @developit before deploy the site to surge.sh, run this command: `cp build/index.html build/200.html && surge` . This will help :) 

Details: https://surge.sh/help/adding-a-200-page-for-client-side-routing

**Comment by developit** [comment]
Confirmed, I borked the surge deploy 😜

**Comment by bestwestern** [comment]
It's not working :( 
Try this in incognito https://cli-demo.preactjs.com/profile/john 
I tried creating a new project with the cli, build it and deployed to zeit:
https://build-wzqulflivm.now.sh/profile/john but this doesn't work either.

**Comment by developit** [comment]
@bestwestern You need to set up a route on your static host of choice that serves up `index.html` for all unmatched file requests. You've deployed static files to now.sh, but there's only one routable file, "index.html" (you can view your deploy here: https://zeit.co/hrronnie/build/wzqulflivm/source?redirect=1).

That being said, `now.sh` simply doesn't support this feature in their static deploys.  Instead, you'll have to add a package.json to your `build` directory (as explained [here](https://github.com/zeit/now-cli/issues/726#issuecomment-319771256)):

**build/package.json**:

```js
{
  "name": "my-great-app",
  "scripts": {
    "start": "serve --single"
  },
  "dependencies": {
    "serve": "latest"
  }
}
```

This is nearly identical to what `now` does for static deploys, except for the addition of the `--single` flag, which fixes index.html routing for single page applications.
