### ISSUE TITLE
🤕 Build breaks after creating `src` directory

### ISSUE THREAD

**Issue by mattwoodnyc** [developit/preact-cli#532]
🤔 _possibly related to #491_

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behaviour?**

```
Build failed!

✖ ERROR /Users/USER_NAME/.nvm/versions/node/v9.3.0/lib/node_modules/preact-cli/lib/lib/entry.js
Module not found: Error: Can't resolve 'preact-cli-entrypoint' in '/Users/USER_NAME/.nvm/versions/node/v9.3.0/lib/node_modules/preact-cli/lib/lib'
 @ /Users/USER_NAME/.nvm/versions/node/v9.3.0/lib/node_modules/preact-cli/lib/lib/entry.js 15:25-57 21:27-59 25:17-65
 @ multi /Users/USER_NAME/.nvm/versions/node/v9.3.0/lib/node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

```
preact create simple foo
cd foo
mkdir src
preact watch
```

**What is the expected behaviour?**

```
Compiled successfully!

You can view the application in browser.

Local:            http://localhost:8080
On Your Network:  http://192.168.0.11:8080
```

**Please mention other relevant information.**
- Node version - **8.10.0**
- npm version - **5.6.0**
- Operating system - **macOS, 10.13.3**
- CLI version - **2.2.1**
- Browser - **Chrome, 65.0.3325.181

**Comment by lukeed** [comment]
Do you have an `index.js` file inside the new `src` directory?

**Comment by mattwoodnyc** [comment]
So, I originally had a `./index.js` importing the app from `src/App.js`.

As soon as I added the `src/index.js` file, the build worked 😀.

**Comment by lukeed** [comment]
Haha, great! That works as expected then. The CLI is expecting to resolve `src/index.js` as soon as it finds that `src` exists.
