### ISSUE TITLE
HMR falls over when using <Route>

### ISSUE THREAD

**Issue by jliebrand** [developit/preact-cli#538]
I've noticed that if my component uses <Route>, then it can fall over when HMR replaces the component as part of dev. 

The error I get is this:
![image](https://user-images.githubusercontent.com/23407884/38353653-fd7b3882-38ae-11e8-9910-ab55ece7470f.png)

Which I think is related to a timing issue where the Route returns null in it's render function. 

Doing a normal refresh works fine.

**Comment by jliebrand** [comment]
Is there a way to replace the HMR with LiveReload in the preact.config.js ?

**Comment by jliebrand** [comment]
doh.. should have tried it first before asking, but in case anyone else is wondering, a simple:
```
config.devServer.hot = false;
```

works around any HMR issues... as it turns it off and gives you live reload instead.

**Comment by developit** [comment]
This was reported at developit/preact-router#198 and fixed in developit/preact#988, but is awaiting a preact release.
