### ISSUE TITLE
Serviceworker slows down first page load (Download cache before crucial files are downloaded)

### ISSUE THREAD

**Issue by SimonKlausLudwig** [developit/preact-cli#539]
I want to request a bug.

I've create a app with about 10 routes. Only one is crucial (route-categories) for the app (The other nine routes are for admin purpose). When I visit the page for the first time the needed route gets downloaded, all right. But in the background, the serviceworker starts to download the remaining routes (and all other resources, like images, icons etc.). The problem is that I need some JSON for my crucial route and the service worker starts downloading all other stuff before this.

![screen shot 2018-04-06 at 01 42 30](https://user-images.githubusercontent.com/13765114/38397135-2d7fb1a6-393c-11e8-824c-57f8e7c3bce9.png)

Is there a way to solve this problem, maybe a delay before the service worker starts ?

Sometime the service worker starts downloading the files after the 'menu' and sometimes before.

**Comment by developit** [comment]
I've been moving towards delaying SW installation a little bit via setTimeout to fix this.
