### ISSUE TITLE
Using port flag isn't reflected in dev server notice

### ISSUE THREAD

**Issue by filoxo** [developit/preact-cli#55]
I just installed preact-cli 1.0.1. I modified the dev script to use the `-p` flag. Now when I run `npm start` or `npm run dev` the server is started on the port correct but the dev server notice still displays the default port (8080). 

This is my console's output.
```
dev/test-pwa » npm run dev

> test-pwa@1.0.0 dev /Users/me/dev/test-pwa
> preact watch -p 8001

  > Development server started at http://localhost:8080
```

Again, the dev server is correctly running on the right port but the error is with the notice.

**Comment by developit** [comment]
ha! how'd I miss that? thanks :)
