### ISSUE TITLE
Unable to minify when using styled components

### ISSUE THREAD

**Issue by robinvdvleuten** [developit/preact-cli#557]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behaviour?**

When I try to create a production build, Uglify errors. It seems that it's unable to minify any styled-components related code;

```
Unexpected token: operator (>) [./components/cookie/styled.js:5,12][bundle.ede6b.js:6194,189]
```

**What is the expected behaviour?**

I expect styled's template literals to be minified.

**Please mention other relevant information.**
- Node version: v8.9
- npm version: v5.6
- Operating system: OSX
- CLI version: v2.2.1
- Browser: n/a

**Comment by prateekbh** [comment]
what template are you using?

**Comment by robinvdvleuten** [comment]
I am not using a template, but added the preact-cli package directly. Currently investigating the uglify options passed by preact-cli to check what went wrong.

**Comment by robinvdvleuten** [comment]
It seems when I disable the plugin I was using ([developit/preact-cli-plugin-async](https://github.com/developit/preact-cli-plugin-async)). The uglifier breaks on some generator related code where I am using async/await;

```
Unexpected token operator «*», expected punc «(» [./sections/signup/index.js:144,21][bundle.2cbc2.js:9857,43]
```

**Comment by robinvdvleuten** [comment]
Hmm when I rewrite the code from async/await to promises, it seems to build correctly. Looks like an issue with the async plugin then 🤔

**Comment by developit** [comment]
Likely the same issue as developit/preact-cli-plugin-async#11.
There's a fork of that plugin that uses fast-async that should solve your problem:
https://github.com/plusCubed/preact-cli-plugin-fast-async

**Comment by mxrguspxrt** [comment]
Problem still exists....

**Comment by ForsakenHarmony** [comment]
try `preact-cli@next`
