### ISSUE TITLE
the command 'preact create' only support options : '--name --cwd --force --yarn --git --install ' ,how I use option like 'preact create app --less'? unrecognized options less

### ISSUE THREAD

**Issue by Orecic** [developit/preact-cli#558]
the command 'preact create' only support options :  '--name --cwd  --force   --yarn   --git  --install ' ,how I use  option like 'preact create app --less'?   unrecognized options less

**Comment by lukeed** [comment]
Just create any `.less` files then install `less` and `less-loader`. You can rename the existing `.css` files if you want.

**Comment by Orecic** [comment]
@lukeed it works, it's so easy, thank you very much.
