### ISSUE TITLE
Critical css + styled-components + prerender

### ISSUE THREAD

**Issue by gbreux** [developit/preact-cli#561]
**Do you want to request a *feature* or report a *bug*?**
Informations and maybe a feature..

**What is the current behaviour?**
The pre-render does not insert critical css in the head, even though styled-components does that out of the box. And since [preact-cli-plugin-critical-css](https://github.com/matthewlynch/preact-cli-plugin-critical-css) is using the npm module critcalCss under the hood, it won't work with styled-components because the css files is basically empty.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
During the pre-render phase, maybe it should take into account if there is styled associated to the component?

At the moment I wonder if my only options is to go with a SSR solution or to go back using css files + [preact-cli-plugin-critical-css](https://github.com/matthewlynch/preact-cli-plugin-critical-css) plugins.. 

Thanks :)

**Comment by developit** [comment]
I have some stuff coming for this.

**Comment by guillaumebreux** [comment]
You said too much! :D 

Can't wait then :)
