### ISSUE TITLE
Using WorkBox as a custom service worker

### ISSUE THREAD

**Issue by ashokvishwakarma** [developit/preact-cli#562]
**Do you want to request a *feature* or report a *bug*?**
Don't know where to categorise this but seems like I needed some help with Service Worker using `prect.config.js`

**What is the current behaviour?**
I have added the `preact.config.js` into the `root` directory of my `preact` app which is
```
const WorkboxBuildWebpackPlugin = require('workbox-webpack-plugin');
export default function (config, env, helpers) {
  /** you can change config here **/
  config.plugins.push(
    new WorkboxBuildWebpackPlugin({
      globPatterns: ['**/*.{html,js,css}'],
      swDest: `../builds/pwa/serviceworker.js`,
      runtimeCaching: [{
        urlPattern: '/api/',
        handler: 'staleWhileRevalidate',
      }]
    })
  );
  return config;
}
```
Disabled the default Service Worker using `--service-worker false` in my build script

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
I am expecting to generate and register the `serviceworker.js` from my `build` directory

I have posted the same on preact Slack channel and got this
@Ashok those seem correct. Are you registering the SW?
Also make sure you're using GenerateSW() from @developit 

Can anyone provide an example to register the SW and also include GenerateSW into it?

I am really stuck in here.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version v9.11.1
- npm version 5.6.0
- Operating system macOS
- CLI version 1.4.1
- Browser Chrome 65.0.3325.181 (Official Build) (64-bit)

**Comment by ashokvishwakarma** [comment]
It seems my `preact.config.js` is not treated at all :(

**Comment by ashokvishwakarma** [comment]
Solved by `--config pwa/preact.config.js` thanks but no thanks :)

**Comment by lukeed** [comment]
The CLI expects `preact.config.js` in the root of your project. The root is not determined by your files' installation, but where your (main) `package.json` resides --- aka, where you run `npm run *` from.
