### ISSUE TITLE
State not maintained inside Router component

### ISSUE THREAD

**Issue by apuravchauhan** [developit/preact-cli#563]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
State maintenance issue while using two instances of same component inside Router.

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. create a new project using preact create default myproject
2. cd myproject
3. npm start
4. Click on Me link and increment the click count
5. Notice the same count reflects in John link.

In below shots: increment the click count in Me tab, and you will see the same count in John tab
![screen shot 2018-04-27 at 6 14 12 pm](https://user-images.githubusercontent.com/1810431/39363137-d84eb8a0-4a46-11e8-8289-742755a7dc51.png)
![screen shot 2018-04-27 at 6 14 02 pm](https://user-images.githubusercontent.com/1810431/39363138-d87cdd3e-4a46-11e8-9276-bff6fa4946d1.png)

**What is the expected behaviour?**
State should be separately maintained in two separately instantiated objects of same component. This is happening only inside Router children. However, the same works outside the Router, so most probably related to Router but not sure.

**Please mention other relevant information.**
- Node version: v7.10.0
- npm version 4.2.0
- Operating system Mac OS Sierra
- CLI version:  2.2.1
- Browser: Chrome

**Comment by apuravchauhan** [comment]
Any pointers are highly appreciated?

**Comment by azulkipli** [comment]
> State should be separately maintained in two separately instantiated objects of same component

Why you expected that behaviour, for what purpose? 

I didn't experience what you have

but I already use unistore in my app here
https://github.com/azulkipli/preactstarter

![screen shot 2018-04-28 at 22 26 20](https://user-images.githubusercontent.com/8231792/39398121-60a3a2f0-4b33-11e8-856c-2fdb8bfd8e3c.png)

**Comment by apuravchauhan** [comment]
My usecase wont require a unistore dependency. Can you help in checking where the bug might be while performing steps to reproduce.

**Comment by azulkipli** [comment]
I dont have problem with my new preact app
<div style="width:100%;height:0px;position:relative;padding-bottom:26.286%;"><iframe src="https://streamable.com/s/by6rv/psooyb" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>
![screen shot 2018-04-29 at 00 49 03](https://user-images.githubusercontent.com/8231792/39399405-330c6fde-4b47-11e8-905c-cfd1bd327284.png)

**Comment by apuravchauhan** [comment]
@azulkipli And heres the video link: 
https://streamable.com/pt2ub

**Comment by azulkipli** [comment]
I think that is correct behaviour because /profile/me & profile/john use same component and print same `count` state. what make it different only `user` props value which is "john" and "me"

**Comment by psabharwal123** [comment]
that is correct behavior, https://clidemo.preactjs.com is not updated and so incorrect behvior. To fix your issue add different keys to each Profile route in app.js
