### ISSUE TITLE
Building and dev server results in TypeError: Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by NicolaiSchmid** [developit/preact-cli#567]
**Do you want to request a *feature* or report a *bug*?**
I'm reporting a bug
**What is the current behaviour?**
When running `npm start` I get a `TypeError: Cannot read property 'compilation' of undefined`. The same error occurs when trying to run `npm build`.
**If the current behaviour is a bug, please provide the steps to reproduce.**
I'm using the preact default template with version `2.1.0` and [this custom `preact.config.js`](https://gist.github.com/NicolaiSchmid/61430a2a1f0fd8395413536d539b4aff) 

**What is the expected behaviour?**
It should just start the dev server or build the production version.
**Please mention other relevant information.**
- Node version: 8.11.1
- npm version: 5.6.0
- Operating system: Windows 10
- CLI version: 2.1.0

**Comment by hassanbazzi** [comment]
Have you tried running the build without the custom config file?

**Comment by reznord** [comment]
Can you provide a link to the repo? So I can go through that and see where the issue is?

**Comment by NicolaiSchmid** [comment]
@hassanbazzi Good idea. But it still won't work.
@reznord I'm afraid that's not possible since it's a private repository for my company.

**Comment by hassanbazzi** [comment]
@NicolaiSchmid It may also be an issue with your code. Can you search for compilation in your codebase and see what comes up?

**Comment by NicolaiSchmid** [comment]
I did that already, and there's no such string in my codebase..

**Comment by marvinhagemeister** [comment]
This looks like an error caused by webpack. I stumbled upon a similar message last week which was caused by mixing webpack 3 and webpack 4 loaders and plugins

**Comment by NicolaiSchmid** [comment]
Has the plugin and/or loader api changed in webpack 4?
So, do I need to use specific versions for plugins and loaders, which are taylored specificly for wb 3?

**Comment by marvinhagemeister** [comment]
Yes, they changed the api quite a bit. Three current release of `preact-cli` is based on webpack 3 and the next version will include webpack 4.

**Comment by NicolaiSchmid** [comment]
But shouldn't the cli work, after I removed my custom `preact.config.js`? Because then there wouldn't be any misversioned loaders and plugins.

**Comment by marvinhagemeister** [comment]
yes, it should. Seems like the cause is something else. Do you have a small repo where the issue can be reproduced?

**Comment by NicolaiSchmid** [comment]
I'm gonna whip something up tomorrow.
BTW: The issue is also reproducible on Ubuntu 18.4

**Comment by NicolaiSchmid** [comment]
I'm sorry it took so long, but I just tried reproducing the bug with a fresh project. And tried step by step, adding configuration from my project and I can't seem to reproduce it.
If I stumble upon this error again, I will reopen the issue, but so far the v3 pre-release has served me well.
