### ISSUE TITLE
SASS: @import from node_modules issues

### ISSUE THREAD

**Issue by wei** [developit/preact-cli#570]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
import .scss file from a node module produces the following error:
```bash
@import "primer-base/index.scss";
^
      File to import not found or unreadable: primer-base/index.scss.
Parent style sheet: stdin
```

**If the current behaviour is a bug, please provide the steps to reproduce.**
```bash
preact create widget test
cd test && npm i --save primer-base
echo -e "@import \"primer-base/index.scss\";\n\n$(cat ./src/components/hello-world/style.scss)" > ./src/components/hello-world/style.scss
npm run start
```

**What is the expected behaviour?**
`npm run start` to run dev server successfully with the primer stylesheet included in the dom.

**Please mention other relevant information.**
- Node version
v8.2.1
- npm version
6.0.1
- Operating system
Mac OSX 10.13.4
- CLI version
2.2.1
- Browser
Irrelevant

**Comment by lukeed** [comment]
Hi there,

In order to specify a `node_modules` import, you need to use the `~` character prefix.

```sass
@import "~bootstrap/dist/css/bootstrap"
```

Taken from [`sass-loader` docs(https://github.com/webpack-contrib/sass-loader#imports).

**Comment by wei** [comment]
Hi @lukeed, thank you for the fast response!

**Comment by lukeed** [comment]
No problem!

**Comment by wei** [comment]
@lukeed, one problem with the primer scss is that it uses things like `@import 'primer-core/index.scss'` to reference .scss files inside other node modules. So even after I did the import with ~ in my style.scss, `npm run start` still throws similar errors. 

I know this is probably the wrong repo to ask, but do you know a solution to this off of top of your head? No worries if you don't : D

**Comment by lukeed** [comment]
Ya, that part stinks. You have to add the module directory to your `includePaths` inside custom config. I don't know what the directory name should actually be in this case:

```js
// preact.config.js

module.exports = (config, env, helpers) => {
  let { rule } = helpers.getLoaderByName('sass-loader')[0];
  rule.options.includePaths.push(
    path.resolve('./node_modules/prism-core/scss')
  )
}
```

You'd have the check that, I'm sure the config code is wrong too 😂 I'm in the car now, but that's the start.

**Comment by wei** [comment]
Really appreciate the help!! Safe drive!

**Comment by cromefire** [comment]
```javascript
let { rule } = helpers.getLoadersByName('sass-loader')[0];
```
does not find anything
