### ISSUE TITLE
Link to my default TypeScript template, or add it to the templates org

### ISSUE THREAD

**Issue by ascorbic** [developit/preact-cli#572]
**Do you want to request a *feature* or report a *bug*?**

Feature

I have created a TypeScript template, based on the default template. It might be good to add it to  @preactjs-templates, or at least link it from the readme. You can find it here: [`preact-default-typescript`](https://github.com/aerian-studios/preact-default-typescript). If there's interest I could port some of the other templates too.

**Comment by SleeplessByte** [comment]
Maybe remove all the "Aerian studios" stuff if this is supposed to be a "default" template.

**Comment by ascorbic** [comment]
@SleeplessByte Which style guide would you suggest we use? As far as I was aware, Preact doesn't have a TypeScript styleguide of its own (or at least it didn't when I wrote it). There shouldn't be anything particularly controversial in there.

**Comment by ascorbic** [comment]
I've removed the dependency and moved the rules into the project.

**Comment by SleeplessByte** [comment]
> @SleeplessByte Which style guide would you suggest we use? As far as I was aware, Preact doesn't have a TypeScript styleguide of its own (or at least it didn't when I wrote it). There shouldn't be anything particularly controversial in there.

Your styles are highly opinionated, which is a *good* thing, but hiding it in a dependency, for a template, in my opinion is not, because preact does not have a default styleguide! By moving them into the template, people can easily change the rules, so that to me is the way to go <3

**Comment by ascorbic** [comment]
@bestwestern The style guide I use for this *is* prettier, but with extra non-formatting rules.

**Comment by bestwestern** [comment]
@ascorbic That part was about the default template, where if I use the prettier plugin in VS Code and then 'npm run lint' I get plenty of errors:
![image](https://user-images.githubusercontent.com/3617433/48900309-53797d80-ee52-11e8-9df9-782f4eca6d13.png)

Your template is too strict for my taste - a method in a component requires public/private in front of it.

**Comment by ForsakenHarmony** [comment]
Feel free to push to the template repo I just invited you to, we can figure the rest out there

**Comment by ascorbic** [comment]
Thanks @ForsakenHarmony. I've made a few updates and pushed, and successfully tried `preact create typescript my-project`. The repo was based on the default boilerplate back in May, but I've updated the dependencies and applied a couple of other updates from the original repo. I'm happy to close this now.
