### ISSUE TITLE
Flicker on initial page load, first time

### ISSUE THREAD

**Issue by psabharwal123** [developit/preact-cli#574]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
there is a flicker on low end devices for initial page load

**If the current behaviour is a bug, please provide the steps to reproduce.**
on a machine with low end cpu, simulate 6x slowdown in chrome 
clear all data, unregister service worker
visit https://clidemo.preactjs.com/
what happens is the following - 
1. html and css load and you see SSR home component
2. bundle.js loads and it clears the screen and starts async load of home chunk
3. home chunk loads and preact renders the home component again

**What is the expected behaviour?**
component for the path requested by browser should be in bundle.js, all others can be async

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version
- npm version
- Operating system
- CLI version
- Browser

**Comment by prateekbh** [comment]
what version of preact-cli are you on?

**Comment by prateekbh** [comment]
I guess the demo site was never re-deployed with latest changes.
https://material.preactjs.com/ does not have this problem.

This was fixed as a part of: https://github.com/developit/preact-cli/issues/274

**Comment by psabharwal123** [comment]
thanks, looks like the exact same issue. let me try that link

**Comment by psabharwal123** [comment]
i tried https://material.preactjs.com/component/chips/, and it works better but in this case the menu icon doesnt show up until route chunk has loaded, is that due to the same reason as above?
