### ISSUE TITLE
reserved words before compile

### ISSUE THREAD

**Issue by mehmetkose** [developit/preact-cli#575]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behaviour?**
I need to reserve some words and variables before compile the source. 
Something like this;

![screen shot 2018-05-21 at 04 27 11](https://user-images.githubusercontent.com/706678/40286406-51cb0240-5caf-11e8-824a-44f071b69105.png)

How can i do it with preact-cli boilerplate?

**Comment by lukeed** [comment]
I don't know what this is, but if it's a Webpack plugin (looks to be), then you can filter thru existing `config.plugins` to remove the `UglifyjsPlugin` we have attached, and then attach your own with these settings.

**Comment by mehmetkose** [comment]
I'm sorry I didn't explain well. got a react based project and now I'm switching over preact. 
So I need to do the same thing, how can I use reserved words with preact-cli boilerplate? I don't know under the hood well. 

![screen shot 2018-05-21 at 12 10 59](https://user-images.githubusercontent.com/706678/40299896-63492cea-5cf0-11e8-804c-90606af930ec.png)

![screen shot 2018-05-21 at 12 10 31](https://user-images.githubusercontent.com/706678/40299903-6c1bc7f6-5cf0-11e8-9294-1c8e8c63a4a8.png)

**Comment by mehmetkose** [comment]
I'm not talking about javascript's reserved words brü, I mean I need these keywords un-uglified. 
see;

![screen shot 2018-05-21 at 17 07 42](https://user-images.githubusercontent.com/706678/40311789-8e9c3cc4-5d19-11e8-9f08-7dc8eb59aa1b.png)

**Comment by ForsakenHarmony** [comment]
you could probably do this in the config
