### ISSUE TITLE
production build flag

### ISSUE THREAD

**Issue by psabharwal123** [developit/preact-cli#576]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
currently the build out put is minified irrespective of whats passed into --production / -p flag

**If the current behaviour is a bug, please provide the steps to reproduce.**
use the default template and build with -p false

**What is the expected behaviour?**
build output should not be minified

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version 6.10.0
- npm version 4.1.2
- Operating system windows 10
- CLI version 2.2.1
- Browser any

**Comment by lukeed** [comment]
There is no `--production` flag -- the CLI does not extend from or pass along arguments to Webpack CLI.

Builds are always production and `watch` is always development.

If you want to disable minification, you must add a custom config file and manually disable the Uglifyjs plugin.

**Comment by psabharwal123** [comment]
its mentioned in https://github.com/developit/preact-cli#preact-build

**Comment by psabharwal123** [comment]
@lukeed should i submit a PR to remove it from readme?
