### ISSUE TITLE
ERROR self signed certificate in certificate chain

### ISSUE THREAD

**Issue by vinyfc93** [developit/preact-cli#580]
Good Afternoon,

I'm having a problem with preact-cli, when I create a new project it returns the following:

```bash
ℹ INFO Assuming you meant preactjs-templates/default...
(node:1068) ExperimentalWarning: The fs.promises API is experimental
✖ ERROR self signed certificate in certificate chain
```

Can you give me a light around this case? Was it a bug? or do I have a configuration error?

thank you in advance

### Infos:
- node@10.1.0
- npm@6.1.0
- preact-cli@2.2.1
- macOs 10.13.4

**Comment by vinyfc93** [comment]
@developit

**Comment by developit** [comment]
Are you behind a corporate proxy?
