### ISSUE TITLE
How to upload static files to CDN

### ISSUE THREAD

**Issue by Orecic** [developit/preact-cli#581]
When I'm finished with preact build, the build file is generated. How to upload static files to CDN?  thanks

**Comment by Orecic** [comment]
@developit can you help me ? thank you very much.

**Comment by marvinhagemeister** [comment]
@Orecic This depends on the CDN/hoster that you are using. They usually have quite a detailed documentation about putting something on their servers.

**Comment by jorunfa** [comment]
@Orecic: It doesn't really have anything to do with the _preact-cli_ project, so please consider closing this issue if you're able to do so.

The content in the build folder is html, css, js, and images - any CDN or webserver like Nginx or Apache can be used to serve these files.
If CDN is the desire then one commonly used solution might be using AWS S3 and Cloudfront: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/MigrateS3ToCloudFront.html
disclaimer: I'm not affiliated with AWS.

**Comment by Orecic** [comment]
I understand, thank you ver much  @jorunfa @marvinhagemeister
