### ISSUE TITLE
How to add 'test' env

### ISSUE THREAD

**Issue by Orecic** [developit/preact-cli#582]
The default is only the production and development environment， How to add 'test' env ，thanks.

**Comment by Orecic** [comment]
@developit can you help me ? thank you very much.

**Comment by marvinhagemeister** [comment]
@Orecic For this to work you need to extend the webpack config through `preact.config.js (see our docs). Basically you need to overwrite this line: https://github.com/developit/preact-cli/blob/bc0c665f77841e755a913bcdf7a1434da2195221/src/lib/webpack/webpack-base-config.js#L206-L208

**Comment by Orecic** [comment]
@marvinhagemeister I completed this requirement ， thank  you very much
