### ISSUE TITLE
Simplify generating firebase config files

### ISSUE THREAD

**Issue by mikaturk** [developit/preact-cli#584]
**Do you want to request a *feature* or report a *bug*?**
*feature*
**What is the current behaviour?**
`preact build --template ./template.html --json`
`preact serve --server config`

is currently the only way to generate the config but I'd like a --firebaseconfig or something on preact build so I don't have to execute as many commands.

**What is the expected behaviour?**
`preact build --template ./template.html --json --firebaseconfig`

**If this is a feature request, what is motivation or use case for changing the behaviour?**
ease of use

**Please mention other relevant information.**
- Node version v10.0.0
- npm version v6.0.0
- Operating system osx 10.10.5
- CLI version 2.2.1

**Comment by developit** [comment]
I think we're looking at rolling it into build like you suggested in the next version:
`preact build --config firebase.json`
