### ISSUE TITLE
Modifying the service worker registration code

### ISSUE THREAD

**Issue by chinchang** [developit/preact-cli#588]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behaviour?**
Can't modify the service worker registration code

**If this is a feature request, what is motivation or use case for changing the behaviour?**
I would like to switch to a more comprehensive registration. Eg. https://github.com/GoogleChromeLabs/sw-precache/blob/5699e5d049235ef0f668e8e2aa3bf2646ba3872f/demo/app/js/service-worker-registration.js

Is that possible?

**Comment by prateekbh** [comment]
Yes! but then you'll have to build the service worker yourself too.

`--no-service-worker` will switch off everything(building + registeration) related to sw from our side.

**Comment by chinchang** [comment]
That should work! Thanks @prateekbh for that ultra-quick response :)
