### ISSUE TITLE
Prerender vs noprerender option 

### ISSUE THREAD

**Issue by sampotts** [developit/preact-cli#589]
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behaviour?**
Docs indicate that `--no-prerender=true` is an option but it throws an error:
```bash
Unknown argument: no-prerender
``` 

I appears it's now `--prerender=false` but when you try to use that, it throws an error stating: 

```bash
Alternatively use 'preact build --no-prerender' to disable prerendering.
```

So I'm confused which is the correct option? 

**If the current behaviour is a bug, please provide the steps to reproduce.**

Try `preact build --no-prerender=true` or `preact build prerender=false` - neither will work now due to the above issue.

**What is the expected behaviour?**
One option or the other works and is documented accordingly. 

**If this is a feature request, what is motivation or use case for changing the behaviour?**
N/A

**Please mention other relevant information.**
- Node version: 9.8.0
- npm version: 6.1.0
- Operating system: MacOS 10.13.6
- CLI version: 2.2.1
- Browser: Chrome 68.0.3440.25

**Comment by henriquesa** [comment]
Both `--prerender=false` and `--service-worker=false` still include the files inside /build, although I'm not sure they're being imported in the code

**Comment by psabharwal123** [comment]
That's not how you use the flags, try removing '=true' and '=false and instead only use --prerender or --no-prerender

**Comment by sampotts** [comment]
> That's not how you use the flags, try removing '=true' and '=false and instead only use --prerender or --no-prerender

Are you sure? Docs don't imply that. How do you pass a boolean for no service-worker then?

**Comment by sampotts** [comment]
Seems `--no-prerender` worked but the statement about the service worker still applies...
