### ISSUE TITLE
Bug, UglifyJs Unexpected token: operator (>)

### ISSUE THREAD

**Issue by thisconnect** [developit/preact-cli#593]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behaviour?**

error when building

```
✖ ERROR bundle.70001.js from UglifyJs
Unexpected token: operator (>) [bundle.70001.js:4780,16]
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

make sure you have at least one fat arrow function `() => {}` 
update `package.json` to only support 2 newest chrome 
```
  "browserslist": [
    "last 2 Chrome versions"
  ]
```
`npm run build` or `yarn build`

**What is the expected behaviour?**

building without error, no polyfills (fetch), modern ES output (class, fatarrows), ideally minified.

**Please mention other relevant information.**
- Node version v8.9.4
- npm version 5.6.0
- Operating system macos 10.13.5
- CLI version preact-cli@2.2.1

Thanks in advance for looking into it :heart:
FYI
According to the deprecation notice in https://www.npmjs.com/package/uglify-es-webpack-plugin 
the uglifyjs-webpack-plugin should already support uglify-es, but only newer versions.

**Comment by lukeed** [comment]
Our `preact-cli@2.2.1` uses Webpack@3 which relies on [`uglifyjs-webpack-plugin@0.4.6`](https://www.npmjs.com/package/uglifyjs-webpack-plugin/v/0.4.6), which can only handle ES5 syntax. Because you specified last 2 _Chrome_ versions, you're allowing a large portion of ES6 syntax to make its way to Uglify, which throws the error.

To fix this, you'd have to either (1) broaden your browserslist range, or (2) manually attach an UglifyES plugin via `preact.config.js`. Of course, with the second option, you should also filter thru existing plugins & removing the existing UglifyJS instance.

**Comment by thisconnect** [comment]
Thanks @lukeed !
Yes I try to go with 2) related https://github.com/developit/preact-cli/blob/master/docs/webpack-helpers.md  and installed `uglifyjs-webpack-plugin@1.2.7`

Does that look correct, is this the way to go?:
```js
const UglifyJsPlugin = require('uglifyjs-webpack-plugin'); // 

export default function (config, env, helpers) {
    const { index } = helpers.getPluginsByName(config, 'UglifyJsPlugin')[0];
    config.plugins.splice(index, 1);

    config.plugins.push(new UglifyJsPlugin());
}

```

**Comment by liudonghua123** [comment]
@thisconnect Thanks for you fix, I had the same problem. But I got the following error:
```
Error: Error at D:\code\electron\epmd-master\preact.config.js:
TypeError: Cannot read property 'index' of undefined
```
I have to write like this
```
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

export default (config, env, helpers) => {
	config.target = 'electron-renderer';
	if (env.production) {
		config.output.publicPath = env.pkg.homepage;
		let { plugin } = helpers.getPluginsByName(config, 'DefinePlugin')[0];
		plugin.definitions.PUBLIC_PATH = env.pkg.homepage;
	}
	// https://github.com/developit/preact-cli/issues/593
	// remove the old
	const uglifyJsPlugin = helpers.getPluginsByName(config, 'UglifyJsPlugin')[0];
	if (uglifyJsPlugin) {
		const { index } = uglifyJsPlugin;
		// console.info(`helpers.getPluginsByName(config, 'UglifyJsPlugin'): ${JSON.stringify(helpers.getPluginsByName(config, 'UglifyJsPlugin'))}`);
		// console.info(`index: ${index}`);
		// console.info(`before config.plugins: ${JSON.stringify(config.plugins[index])}`);
		// console.info(`before config.plugins.length: ${JSON.stringify(config.plugins.length)}`);
		config.plugins.splice(index, 1, new UglifyJsPlugin());
		// console.info(`after config.plugins: ${JSON.stringify(config.plugins[index])}`);
		// console.info(`after config.plugins.length: ${JSON.stringify(config.plugins.length)}`);
	}
};

```
