### ISSUE TITLE
publish 3.0.0-next.6 ?

### ISSUE THREAD

**Issue by tadeuszwojcik** [developit/preact-cli#594]
Hi,
Great project, thanks for hard work!
@lukeed  I'd like to ask if there there an easy way to try out latest next branch for the project? Or perhaps could you publish next version to npm with latest changes?

**Comment by lukeed** [comment]
Hey, thanks for the reminder. Done! Now we can all enjoy & test out @prateekbh's awesome new feature 🎉

**Comment by prateekbh** [comment]
That feature still needs to fix the service worker portion to it, but yes feel free to take it for a ride otherwise

**Comment by lukeed** [comment]
We can also pump out another tag. Some of the earlier `next`s were broken/incomplete on my end.

**Comment by tadeuszwojcik** [comment]
Great ,thanks a lot!
