### ISSUE TITLE
Add WebpackPwaManifest Plugin

### ISSUE THREAD

**Issue by SimonKlausLudwig** [developit/preact-cli#595]
I want to request a 'feature'

Currently, there is a folder with icons for the manifest, I had to resize it by myself.

There is a webpack plugin called WepbackPwaManifest https://github.com/arthurbergmz/webpack-pwa-manifest which resizes the icons to the preferred sizes. So you just need one base icon.

I think this would be an enhancement for many users.

**Comment by SimonKlausLudwig** [comment]
To include https://github.com/RealFaviconGenerator/cli-real-favicon would also be a nice feature. It would be possible to store just one logo.png in the projects root and preact-cli does the resizing, .ico generation, append icons to html-markup etc. 

This has to be done currently manually and i assume that most of the projects have a custom logo for their web app.

**Comment by developit** [comment]
Hi @SimonKlausLudwig! It'd be tricky to ship a favicon/icon generator with Preact CLI, since some folks like to create each size of icon separately (different icons for each size).

FWIW you can use any Webpack plugin with Preact CLI:

**preact.config.js:** _(in your project root folder)_

```js
import WebpackPwaManifest from 'webpack-pwa-manifest';

export default (config) => {
  config.plugins.push(
    new WebpackPwaManifest({
      name: 'My Progressive Web App',
      short_name: 'MyPWA',
      description: 'My awesome Progressive Web App!',
      background_color: '#ffffff',
      icons: [
        {
          src: path.resolve('src/assets/icon.png'),
          sizes: [96, 128, 192, 256, 384, 512]
        }
      ]
    })
  );
};
```
