### ISSUE TITLE
"Uncaught ReferenceError: process is not defined" when importing Influx

### ISSUE THREAD

**Issue by dandv** [developit/preact-cli#596]
# Bug report

**What is the current behaviour?**

Importing the [influx](https://www.npmjs.com/package/influx) package in `src/components/app.js` causes this error in the browser:

![image](https://user-images.githubusercontent.com/33569/42882497-ec08ec48-8a4d-11e8-94fe-855d7f0ac8b7.png)

Influx is not a React package, yet it seems impossible to use influx in preact apps. It can be imported without issue in a React app.

**If the current behaviour is a bug, please provide the steps to reproduce.**

```sh
preact create default preact-influx
cd preact-influx
npm install influx
# edit src/component/app.js and add an `import Influx from 'influx';` line
npm run start
```

**What is the expected behaviour?**

This works in React:

```sh
npx create-react-app react-influx
cd react-influx
npm install influx
# edit src/App.js and add an `import Influx from 'influx';` line
yarn start
```

**Please mention other relevant information.**
- Node version: 10.5.0
- npm version: 6.2.0
- Operating system: Ubuntu
- CLI version: 2.2.1
- Browser: Chrome 67

**Comment by lukeed** [comment]
I think you mean to use the browser version: https://node-influx.github.io/manual/usage.html#browser-setup

The error says it's expecting `process`, which means it's a Node.js library. This is 100% something you don't want to be shimmed on the browser. CRA allows this mistake.

**Comment by lukeed** [comment]
I've never used this library, so if it still complains about wanting `process`, here's how you enable it:

```js
// preact.config.js

module.exports = config => {
  config.node.process = true
}
```

> https://github.com/developit/preact-cli/blob/6742f94664cf88ca0159f809e715fd441495e653/src/lib/webpack/webpack-base-config.js#L245

**Comment by dandv** [comment]
I've tried that preact.config.js setting, and now I get "Buffer is not defined".

Here's a [repo](https://github.com/dandv/influx-browser) showing that influx can be used in the browser apparently [without any shimming](https://github.com/dandv/influx-browser/blob/master/webpack.config.js). It's reduced to the minimum from a project in which I am able to actually use Influx in the browser to retrieve data from a database.

**Comment by lukeed** [comment]
Okay. You can do the same with `Buffer`. You'll see all the node shims we disable in that link I provided.

**Comment by dandv** [comment]
Didn't realize that webpack shimmed process and Buffer by default. Thanks!

**Comment by lukeed** [comment]
No problem!
