### ISSUE TITLE
passing third argument in prerendering app , which will be optional

### ISSUE THREAD

**Issue by DilipCoder** [developit/preact-cli#597]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behaviour?**
prerender mount app automatically in the body, when I do SSR it double renders the app instead of merging client side markup with the server side

**What is the expected behaviour?**
in SSR there is a need of passing the third argument (node) so that my app doesn't double rendered

**If this is a feature request, what is motivation or use case for changing the behaviour?**
code duplication will be solved and preact-cli-ssr will be used frequently for ssr

**Comment by prateekbh** [comment]
+1,
 @developit happening to https://material.preactjs.com/
