### ISSUE TITLE
Consider using the NamedModulesPlugin for module names.

### ISSUE THREAD

**Issue by osdevisnot** [developit/preact-cli#6]
Consider using the NamedModulesPlugin for module names. This option lists names of the modules that are hot reloaded vs the ids as displayed currently:

![image](https://cloud.githubusercontent.com/assets/802242/26272023/b2c3f6f4-3cc3-11e7-89be-57f2e5ac2afd.png)

**Comment by lukeed** [comment]
This would have to be for development only, since full filepath names are retained in the output. 

I'd be happy to PR this.

**Comment by developit** [comment]
Yup, would love to have this enabled in development!
