### ISSUE TITLE
Error with service worker when depoloying to firebase

### ISSUE THREAD

**Issue by andrantis** [developit/preact-cli#60]
I'm seeing a bunch of erros (below) in the browser console after deploying a newly created app to firebase. Looks like the sw is referencing my local files instead of the ones in the server. 

I'm on Windows 10 and I had a similar issue with create-react-app that they fixed with this commit: https://github.com/facebookincubator/create-react-app/commit/22ca584b2b8db5cb6dfa601412a72e6947054cf9

`
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/2.chunk.dee19c0c2b89ad8a3492.js?_sw-precache=cecc045fb475b3d5f4f96d2140782cf1. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/assets/favicon.ico?_sw-precache=53ac170e970ad034a55ee15ce198708c. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/assets/icons/android-chrome-192x192.png?_sw-precache=1ea58b225a597f78adfd987ed164e573. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/assets/icons/android-chrome-512x512.png?_sw-precache=b65626103d4cd30abdb0423e6ab15179. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/assets/icons/apple-touch-icon.png?_sw-precache=4e32b9c4edcb5babb823e4824f90bb8d. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/assets/icons/favicon-16x16.png?_sw-precache=2cbedfd68f59e42b0d03ba3946863ee7. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/assets/icons/favicon-32x32.png?_sw-precache=b9108564a20f06675f60b29337c71b3e. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/assets/icons/mstile-150x150.png?_sw-precache=3eb725b0686148a67f2feb546670b313. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/bundle.js?_sw-precache=d5bb8d2c92704cc0f102c0896195782e. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/favicon.ico?_sw-precache=53ac170e970ad034a55ee15ce198708c. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/index.html?_sw-precache=f1b6dd4db31797ed11807b114bcbdae2. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/manifest.json?_sw-precache=409a6ab1239000b8c4b64cf7c808d616. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/polyfills.chunk.906967bd865a58e79868.js?_sw-precache=fc493e4fc1f1a71239b36865099aaf69. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ sw.js:1
(anonymous) @ sw.js:1
sw.js:1 Fetch API cannot load file:///D:/projects/pwa/preact/one/build/style.css?_sw-precache=3ce120ab4c8b971cba535fc84d789361. URL scheme must be "http" or "https" for CORS request.`

**Comment by RodSwanston** [comment]
Same with ZEIT NOW

`> preact-mhc@1.0.0 start /home/nowuser/src
> NODE_ENV=production npm run -s serve
05/28 12:46 AM (21s)
Error: EACCES: permission denied, open '/home/nowuser/src/build/polyfills.chunk.906967bd865a58e79868.js'
05/28 12:46 AM (21s)

npm ERR! Linux 4.9.16-coreos-r1
05/28 12:46 AM (21s)
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
05/28 12:46 AM (21s)
npm ERR! node v7.10.0
05/28 12:46 AM (21s)
npm ERR! npm  v4.2.0
05/28 12:46 AM (21s)
npm ERR! code ELIFECYCLE
05/28 12:46 AM (21s)
npm ERR! errno 1
05/28 12:46 AM (21s)
npm ERR! preact-mhc@1.0.0 start: `NODE_ENV=production npm run -s serve`
05/28 12:46 AM (21s)
npm ERR! Exit status 1

**Comment by prateekbh** [comment]
I see that some effort regarding this is already thr
https://github.com/developit/preact-cli/blob/master/src/lib/webpack-config.js#L431

I cant check on a windows machine, can anyone pick this and try the fix suggested in the issue description?

**Comment by ooade** [comment]
@prateekbh Maybe we could do something like [this](https://github.com/ooade/NextSimpleStarter/blob/master/next.config.js#L25) so that the service worker takes in only HTTP requests???

**Comment by bestwestern** [comment]
@andrantis could you please describe exactly how you deployed to firebase?

**Comment by developit** [comment]
Possibly due to #50?  I can take a look on windows.

**Comment by NekR** [comment]
Hmm.. How good it would be if there would be a plugin without such issues 😱

**Comment by lukeed** [comment]
Related to #7

**Comment by developit** [comment]
Time to add `--sw offline-plugin`.

**Comment by prateekbh** [comment]
off note: I'll raise a PR to migrate to `workbox` by default by next monday

**Comment by NekR** [comment]
@prateekbh what does that solve exactly? :-)

**Comment by prateekbh** [comment]
AFAIK it takes care of this problem, and it will bring much more flexible approach
Adding @addyosmani for more info :p

**Comment by rkostrzewski** [comment]
@developit should I close this as #7 has been resolved and absolute paths are no longer there, or do we want to track `--no-service-worker` here?

**Comment by developit** [comment]
I think we're good to close since the original issue is fixed.
