### ISSUE TITLE
--production=false seems to have no effect

### ISSUE THREAD

**Issue by schwiet** [developit/preact-cli#600]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
`preact build -p false` `preact build --production=false` `preact build --production false`
all result in minified output.

**What is the expected behaviour?**
changing this flag to false seems like it should result in non-minified code

**Please mention other relevant information.**
- Node version 8.6.0
- npm version 5.7.1
- Operating system Mac OS
- CLI version 2.2.1

**Comment by lukeed** [comment]
Hey, so yargs can't interpret `=false` unfortunately. You will need to do `--no-production` instead.

Hope that helps!
