### ISSUE TITLE
Serviceworker in case of module/nomodule script tags

### ISSUE THREAD

**Issue by prateekbh** [developit/preact-cli#601]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behaviour?**
With `--esm` build service worker caches both versions of `.js` and `.esm.js` whereas the browser uses only one.

**If the current behaviour is a bug, please provide the steps to reproduce.**
- Build with `--esm` flag.
- Serve
- Check the files precached by the serviceworker

**What is the expected behaviour?**
There should be two service workers generated and the sw, caching the right files should be registered.
Although right now service worker registration is a part of our code and not in our template.html

if this would be in our `tempate.html`, it would be as easy as this:

```
<script type=module>
// register sw caching .esm.js files
</script>
<script noscript>
// register old service worker caching .js files
</script>
```

**Comment by prateekbh** [comment]
or make SW not pre-cache js, and put cache first runtime strategy to it

**Comment by lukeed** [comment]
I think the `bundle.mjs` file should be registering the ESM-only SW, while the `bundle.js` file should be calling to register the regular, current SW file. The only changes needed are (1) emitting a new `sw.esm.js` (eg) file via `sw-precache` and (2) updating the ESM bundle reference to service worker.

**Comment by prateekbh** [comment]
>(2) updating the ESM bundle reference to service worker.
We'd need some transform to go and update `bundle.esm` post processing, because both `bundle.js` and `bundle.esm.js` are built of the same source.

**Comment by lukeed** [comment]
Yeah, that's easy though. We just need to update this line: https://github.com/developit/preact-cli/blob/master/src/lib/entry.js#L9

**Comment by prateekbh** [comment]
thats the thing, first `bundle.js` is built, then `bundle.esm.js` is built from the same file...
there's nothing in between that can be changed.

Its after we've built these bundles, that we can change one.

or may be we can add a webpackDefinePlugin in the `.esm` run and use it conditionally in the file... WDYT? like`ENV_ESM = true`

**Comment by lukeed** [comment]
Sure, either way works! The third, least elegant solution is just a post-script that runs 

```js
let pub = __webpack_public_path__;
let contents = fs.readFileSync('bundle.esm.js', 'utf8');
fs.writeFileSync('bundle.esm.js', content.replace(pub + 'sw.js', pub + 'sw.esm.js');
```

I'm more concerned about the ESM SW filtering down correctly & writing a new SW file.

**Comment by hassanbazzi** [comment]
@prateekbh I know you've been doing a bunch of work everywhere for this. This one can be closed now right because of the latest merged PR?
