### ISSUE TITLE
could not locate fileMock.js when running tests

### ISSUE THREAD

**Issue by ThHareau** [developit/preact-cli#603]
**Do you want to request a *feature* or report a *bug*?**
report a *bug*
**What is the current behaviour?**
The jest configuration in package.json contains an error for the image filemock
**If the current behaviour is a bug, please provide the steps to reproduce.**
`preact create default test` 
Then the produces `package.json` will have: 
```js
{
// ...
   "jest": { 
        "moduleNameMapper": {
            "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/src/tests/__mocks__/fileMock.js"
        } // ... 
}
``` 
Whereas the file `<rootDir>/src/tests/__mocks__/fileMock.js` (but `fileMocks.js` does). 

**What is the expected behaviour?**

The value should be `"<rootDir>/src/tests/__mocks__/fileMocks.js"`. 

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version: v8.11.3
- npm version: 5.6.0
- Operating system: fedora 28
- CLI version: preact-cli 2.2.1
- Browser: NA

**Comment by developit** [comment]
We need to create a wrapper around Jest to encapsulate this, and it should use webpack-jest rather than relying on mocking.
