### ISSUE TITLE
How do i put in a favicon? 

### ISSUE THREAD

**Issue by Loogin17** [developit/preact-cli#608]
I finally figured out what the little sprite on the tab is, and now I need to know how to put one in. 
I looked it up, and all I can find are some confusing answers. Is there a simple way to do it? 

thanks.

**Comment by matthewlynch** [comment]
Hi @Loogin17,

The favicon is location here `<project root>/src/assets/favicon.ico`.

There is also a folder than contains other icons here: `<project root>/src/assets/icons`.

I've assumed that you've used the default template when you created your preact-cli project so the paths might be different if you have used a different template.

You can use a tool like http://www.favicomatic.com/ (or google favicon generator) to create all the different sized favicons.

Hope this helps.

**Comment by Loogin17** [comment]
Alright, thanks a lot! I got it now!
