### ISSUE TITLE
`preact build` doesn't exit with proper code on error

### ISSUE THREAD

**Issue by thangngoc89** [developit/preact-cli#61]
`preact build` always exit with code = 0 where there are errors or not. And this is pretty annoying because you can't catch this on CI.

P/s: After a quick digging, a try ...catch block is missing here https://github.com/developit/preact-cli/blob/35fd84a86fe6b6c8abd60aeb721494771930c4ff/src/commands/build.js#L41 . 
I think it's the root of this evil

**Comment by developit** [comment]
ah actually it looks like asyncCommand isn't accounting for synchronous errors in the async functions (promises):  https://github.com/developit/preact-cli/blob/master/src/lib/async-command.js#L16-L17

**Comment by thangngoc89** [comment]
@developit Is there anything I can help to push this forward? This is killing my CI workflow.

**Comment by oren** [comment]
I would love to hear more about your CI workflow (:

**Comment by thangngoc89** [comment]
@oren I think it's called continous development && deployment process. I use Gitlab CI to automatically test each commit and then automatically deploy the site to my server. If there is an error (test process exited with non-zero code) , the CI will emit an error and cancel the deployment.

**Comment by oren** [comment]
Got it. Thanks
