### ISSUE TITLE
Feature request: Webpack 4 support

### ISSUE THREAD

**Issue by tom-sherman** [developit/preact-cli#611]
Is there plans/discussions/PRs to support Webpack 4?

It brings loads of improvements

**Comment by lukeed** [comment]
We are using it in the `next` tag, which is still under development

**Comment by tom-sherman** [comment]
Thanks @lukeed. How close is this to being released? How can I help?

**Comment by lukeed** [comment]
We're still working on a new plugin architecture & a revamped set of config `helper`s. There's also being work done w/ ESM builds, ServiceWorker behavior, and Babel@7.

I use the `next` release in most of my builds. TBH, I'm a little out of touch of what the most _current_ status is, but what's there is definitely functional & the best way to suss out any bugs and/or needs.

**Comment by prateekbh** [comment]
IIRC we still send css file for the first page which results into this: 
<img width="702" alt="screen shot 2018-08-08 at 11 47 58 am" src="https://user-images.githubusercontent.com/5960497/43857726-0b83c926-9b01-11e8-80fa-bb63d71db126.png">

we can use some help for removing this and inlining the css while pre-rendering. am i right @lukeed ?

**Comment by developit** [comment]
@tom-sherman you should join [our Slack](https://preact-slack.now.sh), we'd some help!

**Comment by prateekbh** [comment]
is it ok to close this?
