### ISSUE TITLE
support for live reload on browser extensions

### ISSUE THREAD

**Issue by krisboit** [developit/preact-cli#620]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behaviour?**
Everything is fine when running `preact watch` and open the web app with `http/https` protocol. When trying to develop a chrome extension live reload is not working, the connection to WDS websocket cannot be made:
```
Uncaught SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'chrome-extension:' is not allowed.
```

**If this is a feature request, what is motivation or use case for changing the behaviour?**
`preact-cli` it's a great project adding support and some documentation on how to use it on browser extension development would be great.

**Please mention other relevant information.**
I've fixed this problem by adding this in my preact.config.js:
```
if (Array.isArray(config.entry.bundle)) {
    config.entry.bundle = config.entry.bundle.map((bundle) => {
        if (bundle === "webpack-dev-server/client") {
            const liveReloadProtocol = env.https ? "https" : "http";
            const liveReloadHost = env.host.replace(/^0\.0\.0\.0$/, "localhost");

            const liveReloadUrl = `${liveReloadProtocol}://${liveReloadHost}:${env.port}`;
            return "webpack-dev-server/client?" + liveReloadUrl;
        }
        return bundle;
    });
}
```
If you agree with this solution, i could do a pull request.

**Comment by ForsakenHarmony** [comment]
I'm not sure if a lot of people need this, seems like this could be done (as a plugin) in preact.config.js as well

**Comment by developit** [comment]
@krisboit I wonder if we could submit this as a fix for `webpack-dev-server/client` itself?  It seems like the URL-guessing it's doing in the browser doesn't account for documents loaded over non-http schemes.
