### ISSUE TITLE
watch command should have a log style output option

### ISSUE THREAD

**Issue by haggen** [developit/preact-cli#626]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behaviour?**

The `watch` command output is destructive. i.e. it clears the screen. This does not play nice when coming from inside processes managers, for instance, when inside a docker container being ran in a cluster, because it remove output from other commands as well.

**If the current behaviour is a bug, please provide the steps to reproduce.**

N/A

**What is the expected behaviour?**

The `watch` command should have an option (e.g. `--log`) that prints its output in a _cumulative_ manner (appending at the bottom) instead of clearing the screen. I understand that I'd lose the _progress indicator_ with this change but that would be okay. Simply indicating that the files are being rebuilt and showing a confirmation when it's done and how long it took is just fine.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

For when running `watch` inside a process manager like foreman, docker-compose, etc.

**Please mention other relevant information.**

N/A

I tried my best to explain everything but my English skills are kinda rusty today, so excuse me if something doesn't sound clear or makes no sense.

**Comment by torch2424** [comment]
Thanks for opening this! Was just about to do the same. On [my project](https://github.com/torch2424/wasmBoy), I have multiple different pieces going on (Core Wasm module, a lib compiled with rollup, and then the actual debugger), and the debugger (written in react), destroys the other output by the other two watch commands.

**Comment by developit** [comment]
Definitely open to a PR for this.
