### ISSUE TITLE
Build brotli bundles of assets

### ISSUE THREAD

**Issue by prateekbh** [developit/preact-cli#635]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behaviour?**
While using `preact build` we build the assets in text format and then its up to the hosting solution to gzip it.

**What is the expected behaviour?**
We should generate brotli compressed version of our assets so that it can be picked by the hosting providers if they support brotli

**If this is a feature request, what is motivation or use case for changing the behaviour?**
Better web perf

**Comment by prateekbh** [comment]
@kristoferbaxter,  @developit  do you know any provider who actually uses brotli bundles?
I checked firebase but no doc pointing that it'll use brotli

**Comment by developit** [comment]
@kristoferbaxter might know. I haven't come across any that do this (now / surge / firebase / netlify).

**Comment by prateekbh** [comment]
if none of us know, should we take this out of 3.0?

**Comment by lukeed** [comment]
Cloudflare is the only service I know that uses brotli, and they don't rely on origin. Instead, they produce their own brotli responses dynamically
