### ISSUE TITLE
Put template.html in user-land

### ISSUE THREAD

**Issue by prateekbh** [developit/preact-cli#638]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behaviour?**
`template.html` is never exposed to the user and has to be copied from `preact-cli` repo.

**What is the expected behaviour?**
Too many users have requested for this, may be its better to just put `template.html` in the user land.

**If this is a feature request, what is motivation or use case for changing the behaviour?**
User request and user confusion.

**Please mention other relevant information.**
- Node version: any
- npm version: any
- Operating system: any
- CLI version: next
- Browser: any

**Comment by lukeed** [comment]
Duplicate of #428 and #516

**Comment by prateekbh** [comment]
oh nice i'll swap them in the project thanks
