### ISSUE TITLE
How to run the projects in the example folder?

### ISSUE THREAD

**Issue by oren** [developit/preact-cli#64]
I tried each one of the following but nothing worked:
```
npm start
preact watch
preact serve
python -m SimpleHTTPServer
```

**Comment by oren** [comment]
just to make it clear - I cloned the repo and I am trying to run the examples folder. I didn't run the cli with --type argument.

**Comment by oren** [comment]
@lukeed explained to me on slack that I am not suppose to run it from the examples folder. I have to use the ---type from the CLI and create the type I want to be able to run it.

**Comment by developit** [comment]
yup yup.  if you did want to run them (if working on preact-cli, for example) there are examples as scripts in the package.json.
