### ISSUE TITLE
CSS classes don't work

### ISSUE THREAD

**Issue by biznickman** [developit/preact-cli#640]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
When using CSS classes 

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. `preact create widget project`
2. Go to the `/components/hello-world/style.scss` and add a class `.test { background-color: #000;}`
3. Add the `className='test'` to the parent widget.
4. Run the app and the background color will be white.

**What is the expected behaviour?**
The div should be black. Apparently the builder does not inject the sanitized class names (In my case `.test` became `.test_95fc` yet it doesn't inject that updated class name into the div.)

**Comment by lukeed** [comment]
You must import the stylesheet within your JS file and reference it by name. Please look [within here](https://github.com/preactjs-templates/default/blob/master/template/src/components/header/index.js#L9) for an example.

```css
.test {
  background: #000;
}
```

```js
import style from './index.css';

export default function (props) {
  return (
    <div class={ style.test }>
      I will have black background
    </div>
  );
}
```

Hope that helps!

**Comment by angelsalazar** [comment]
@lukeed  is there a way to avoid that?, that's a lot of work if you have lots of custom classes
