### ISSUE TITLE
Project fails to compile when using render props and enclosed variables

### ISSUE THREAD

**Issue by onnovisser** [developit/preact-cli#645]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
This component fails to compile:
```jsx
function Button({ onClick }) {
  return (
    <CompWithRenderProp
      render={() => <button onClick={onClick}>Click</button>}
    />
  );
}
```

**If the current behaviour is a bug, please provide the steps to reproduce.**
Minimal repo here: https://github.com/onnovisser/preact-cli-bug

Run `npm install` and `npm run dev`.

**What is the expected behaviour?**
It should compile, which does happen when the rendered component is changed to

```jsx
<CompWithRenderProp
    render={() => <button onClick={() => onClick()}>Click</button>}
/>
```

or

```jsx
<CompWithRenderProp
    render={() => {
    const handler = onClick;
    return <button onClick={handler}>Click</button>;
    }}
/>
```

**Please mention other relevant information.**
- Node 10.8
- npm 6.2
- MacOS
- CLI 2.2.1

**Comment by marvinhagemeister** [comment]
Thanks for the detailed report 👍

After digging around some bit it looks like an issue with babel's transpilation of jsx. This strangely only occurs when function arguments are destructured. This is confirmed by checking the transpiled output which somehow fails to convert the "inner" jsx part:

```js
 function Button((_temp = _ref, _ref2 = <button onClick={onClick}>Click</button>, _temp)) {
 //...
}
```
