### ISSUE TITLE
Adding the `--no-production` option to `preact build` produces a Pre-Render/Server-Side-Render error.

### ISSUE THREAD

**Issue by johnhaitas** [developit/preact-cli#651]
**Do you want to request a *feature* or report a *bug*?**

_Report a bug_

**What is the current behaviour?**

`preact build --no-production` causes a server-side exception. `ReferenceError: window is not defined`.

### Full Error Message
```
Unable to read sourcemap: /Users/johnhaitas/src/johnhaitas/preact-cli-no-production-ssr/build/ssr-build/ssr-bundle.js.map

ReferenceError: window is not defined
method: null
[object Object]
This is most likely caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.

Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'

Alternatively use 'preact build --no-prerender' to disable prerendering.

See https://github.com/developit/preact-cli#pre-rendering for further information.npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! preact-cli-no-production-ssr@0.0.0 build-dev: `preact build --no-production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the preact-cli-no-production-ssr@0.0.0 build-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johnhaitas/.npm/_logs/2018-10-03T18_50_35_625Z-debug.log
```

[2018-10-03T18_50_35_625Z-debug.log](https://github.com/developit/preact-cli/files/2443436/2018-10-03T18_50_35_625Z-debug.log)

The offending line comes from `style-loader` https://github.com/webpack-contrib/style-loader/blob/v0.18.2/lib/addStyles.js#L23.

**If the current behaviour is a bug, please provide the steps to reproduce.**

I have created a repo which adds a `build-dev` npm run script
https://github.com/johnhaitas/preact-cli-no-production-ssr

Reproduce the bug by running `npm run build-dev`

**What is the expected behaviour?**

The server-side pre-render should be successful.

**Please mention other relevant information.**
- Node version - `v8.12.0`
- npm version - `6.4.1`
- Operating system - `MacOS High Sierra`
- CLI version - `2.2.1`

**Comment by johnhaitas** [comment]
Please not that in [/src/lib/webpack/webpack-base-config.js](https://github.com/developit/preact-cli/blob/v2.2.1/src/lib/webpack/webpack-base-config.js) the is `isProd` variable is never evaluated using `isProd === true`.
https://github.com/developit/preact-cli/blob/v2.2.1/src/lib/webpack/webpack-base-config.js#L149

The only way to get the `isProd` to evaluate to `false` (boolean) is by setting `--no-production`. If someone were to try `--production false` then `isProd` is set to `'false'` (string) that will evaluate as `true` in [/src/lib/webpack/webpack-base-config.js](https://github.com/developit/preact-cli/blob/v2.2.1/src/lib/webpack/webpack-base-config.js) (because `'false' ? true : false` evaluates to `true`)

**Comment by johnhaitas** [comment]
@lukeed there-in lies the problem if `--production false` results in `isProd` to be `false` (boolean) then this problem will emerge

**Comment by lukeed** [comment]
Right right, the `next` branch accounts for that too simply because in that version, `env.production` is directly equal to the `argv.production` value – which, for that branch, is always a boolean.

**Comment by johnhaitas** [comment]
@lukeed I installed `preact-cli` `next` branch to test and the problem still occurs, now also for `--production false`.

This is expected as suggested in my previous comment - https://github.com/developit/preact-cli/issues/651#issuecomment-426767444
> @lukeed there-in lies the problem if `--production false` results in `isProd` to be `false` (boolean) then this problem will emerge


The fix that you describe in your previous comment results in the same error now occurring with `--production false` (since it is now correctly evaluating `isProd` to `false` (boolean) 

https://github.com/developit/preact-cli/issues/651#issuecomment-426766703
> Getting `--production false` to be `false` (boolean) is fixed in the next version, but we might as well fix it here too since it's simple 👍

https://github.com/developit/preact-cli/issues/651#issuecomment-426767913
> Right right, the `next` branch accounts for that too simply because in that version, `env.production` is directly equal to the `argv.production` value – which, for that branch, is always a boolean.

**Comment by johnhaitas** [comment]
The problem is with `style-loader`

Changing `isProd ? MiniCssExtractPlugin.loader : 'style-loader'` to simply `MiniCssExtractPlugin.loader` fixes the problem in the `next` branch

Here are the two lines that would 
https://github.com/developit/preact-cli/blob/next/packages/cli/lib/lib/webpack/webpack-base-config.js#L139
https://github.com/developit/preact-cli/blob/next/packages/cli/lib/lib/webpack/webpack-base-config.js#L166

I'm not sure if this is a valid fix though as it might not produce the results we're looking for - @lukeed thoughts?

**Comment by marvinhagemeister** [comment]
The miniextract loader should not be included in watch mode, because that would break hmr.

**Comment by johnhaitas** [comment]
The funny thing is that `mini-css-extract-plugin` recommends doing the `isProd ? MiniCssExtractPlugin.loader : 'style-loader'` line

perhaps the `style-loader` could only be introduced for client builds only - might that work?

**Comment by lukeed** [comment]
Right. What @marvinhagemeister mentioned is correct.

The issue here is that there's a discrepancy in what Preact CLI uses for "is this production?" logic. Basically everywhere, there's a reference to the original `argv.production` value, as you'd expect.

But then [here](https://github.com/developit/preact-cli/blob/master/src/lib/webpack/run-webpack.js#L26-L27) we are basing a `prodBuild` based off the `watch` parameter, which is a direct correlation to `preact watch` vs `preact build`.

So, because prerendering is tied to _production_ mode (only), this fails.

**Comment by lukeed** [comment]
Further, both issues (the `watch` reliance & the `argv.production` parsing) are still present on `next`.

**Comment by lukeed** [comment]
@johnhaitas If you want to check out & verify the changes to either branch that'd be great. I tested both branches with simple apps, but hoping you have something more substantial handy.

Thanks!

**Comment by johnhaitas** [comment]
@lukeed changes worked for me on both branches
