### ISSUE TITLE
Generated Material app error: Can't resolve preact-material-components/Toolbar/style.css

### ISSUE THREAD

**Issue by piotrkochan** [developit/preact-cli#655]
**Do you want to request a *feature* or report a *bug*?**

Bug. Material app wants not existing Toolbar style:

```
Build failed!

✖ ERROR ./src/components/header/index.js
Module not found: Error: Can't resolve 'preact-material-components/Toolbar/style.css' in '/path/to/app/src/components/header'
 @ ./src/components/header/index.js 20:0-54
 @ ./src/components/app.js
 @ ./src/index.js
 @ ./node_modules/preact-cli/lib/lib/entry.js
 @ multi ./node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

Just create material app and run it.

**What is the expected behaviour?**

Everything works without problem

**Please mention other relevant information.**
- Node version 8.11.3
- npm version 5.6.0
- Operating system ubuntu 18
- CLI version 2.2.1
- Browser - not revelant

**Comment by prateekbh** [comment]
pushed the fixed right now. do you mind re creating your project?
