### ISSUE TITLE
Prerender renders duplicate app contents when adding GTM no script tag in body

### ISSUE THREAD

**Issue by adrienshen** [developit/preact-cli#659]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behaviour?**
https://www.dropbox.com/s/bkg7ll25zfbuusn/Screenshot%202018-10-21%2023.57.40.png?dl=0
The prerender logic seems to not be working right when there are extra DOM nodes like GTM no script tag added to the body. In my case, it rendered the app contents twice. Once for the pre-render, and then my app again via javascript.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Add GTM noscript snippet to body before pre-render.
- Build the app and serve the contents.
- The content will be rendered twice when using pre-rendering.

**What is the expected behaviour?**
Expected to contents to render just once and correctly no matter what extra snippets we add to the body tags.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
preact-cli 2.2.1
Would be happy to provide a fix, if I can get some pointers. I have not done too much open source before.

**Comment by prateekbh** [comment]
According to this: https://github.com/developit/preact-cli/blob/6742f94664cf88ca0159f809e715fd441495e653/src/lib/entry.js#L18

It renders on body's first element.

Can you try putting this into your jsx shell

**Comment by lukeed** [comment]
Correct. You either have to add your GTM script(s) into the `head` or do as @prateekbh suggested.

**Comment by adrienshen** [comment]
Sorry, where do I need to put that? In the upmost root element?

On the GTM manager site, they even suggest that the noscript tag be added to the body.

**Comment by lukeed** [comment]
You should [create a custom template](https://github.com/developit/preact-cli#template) if you haven't already. The default one that Preact CLI uses is linked there. 

Then you must add the `--template <path>` flag to both your `build` & `watch` commands.

**Comment by lukeed** [comment]
Sorry, that was for the `<head>` route (option 1). Yes, to just render within the App itself, just include it at the top of your `App.render` method. The GTM library will still work.

```js
class App extends Component {
  // ...

  render(props, state) {
    return (
      <div id="app">
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XXXX');</script>
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

      <header>Welcome to My App</header>
    </div>
  )
}
```

---

Your third option is to dynamically append the script on `App.componentDidMount` – you run the risk of GTM not working on users with JS disabled, but that's it.

**Comment by adrienshen** [comment]
I will append the GTM script directly in App. I think that should fix it. Thanks.

**Comment by uuusoftware** [comment]
`	<body>
    
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XASDASD" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    
  
		<% preact.bodyEnd %>
	</body>`

This code in the template.html also triggers double page. We spent 1hr before identified this. Any ideas how to fix? The previous suggestions about using javascript are not valid for this case, since this is a noscript snippet.

**Comment by rschristian** [comment]
@uuusoftware

You should be able to correct that by just moving the iframe to after the body injection point:

```diff
<body>
-  <!-- Google Tag Manager (noscript) -->
-    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-123456" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
-  <!-- End Google Tag Manager (noscript) -->
   <% preact.bodyEnd %>
+  <!-- Google Tag Manager (noscript) -->
+  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-123456" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
+  <!-- End Google Tag Manager (noscript) -->
</body>
```
