### ISSUE TITLE
Build starts failing when integrating lingui with a preact project

### ISSUE THREAD

**Issue by chinchang** [developit/preact-cli#663]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Describe the bug**
I am trying to integrate lingui i18n library -> https://lingui.js.org/tutorials/setup-react.html
When I add @babel/core and babel-core/@bridge packages to my preact app (on Babel 6), the build starts failing with:

```
Module build failed: Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.
```

**To Reproduce**

I have a minimal project setup with preact-cli here -> https://github.com/chinchang/preact-lingui/

This is the specific commit to integrate lingui -> https://github.com/chinchang/preact-lingui/commit/1b61f18a02ec0760019dc878873fb0a15759555e

If you start the app with `yarn start`, it fails with above-mentioned error.

**Please mention other relevant information.**
- Node version: 11.0.0
- npm version: 6.4.1
- Operating system: ubuntu 16.04
- CLI version: 2.2.1
- Browser: chrome

**Comment by ForsakenHarmony** [comment]
it's telling you what it needs, this is not really related to preact-cli
