### ISSUE TITLE
(nice to have) Document what each type of project mean

### ISSUE THREAD

**Issue by oren** [developit/preact-cli#67]
It might be nice to have a quick document that explains the difference between each project type.
For example - the default is using CSS but the full is using less.

**Comment by developit** [comment]
Totally agree! I think we should evaluate the projects and make sure there is less overlap. I would like to have templates come from Github too, so we could have awesome community templates for things like TypeScript and things like that.

**Comment by krokofant** [comment]
Well, at least a word or two. Like _empty_ and _simple_ is kinda guessable in their complexity but _default_ and _root_? What does that even entail?

**Comment by rodush** [comment]
Is it a bug that all `type`'s except "full", the default one, generate build folder with all the compiled assets?..
