### ISSUE TITLE
How to reach a smaller bundle using widget template

### ISSUE THREAD

**Issue by rafaellages-hotmart** [developit/preact-cli#673]
Hi guys Im building a portable widget and what attracted me most to preact was its 3kb size. Ive setup my project with react cli using widget template and just after that I ran npm run build, gzipped(with -6) and checked the bundle size of the hello world. 
It was **8.1K**, to be honest I was expecting something around **4~4.5k**
I know that 8k is still very small but for my tool every byte counts.

Do you guys have any advice or trick to make it smaller? Maybe remove babel or something like that?

**Comment by ForsakenHarmony** [comment]
There are some polyfills included (promise and fetch) and possibly preact-compat

**Comment by reznord** [comment]
If you are not going to use any `react-*` libraries, then we can get rid of `preact-compat` (which consumes around ~3kb)

**Comment by rafaellages-hotmart** [comment]
Ive removed preact-compat and preact-router, but it had no effect on my build size :(

Still 8.2K

Here is my dependencies
```
  "devDependencies": {
    "eslint": "^4.5.0",
    "identity-obj-proxy": "^3.0.0",
    "if-env": "^1.0.0",
    "jest": "^21.2.1",
    "microbundle": "^0.6.0",
    "node-sass": "^4.5.3",
    "preact-cli": "^2.0.2",
    "preact-render-to-string": "^3.7.0",
    "preact-widget-scripts": "^0.6.0",
    "sass-loader": "^6.0.6"
  },
  "dependencies": {
    "preact": "^8.2.5",
    "preact-habitat": "^3.1.0"
  }
```

preact-habitat should not be a problem because its <1kb and I need it.

**Comment by ForsakenHarmony** [comment]
try adding `--json` and then use the resulting json file in https://chrisbateman.github.io/webpack-visualizer/

**Comment by rafaellages-hotmart** [comment]
@ForsakenHarmony Thanks for helping me to dig into this, here is the culprits(gziped):
Preact 3.4kb
Style and css loader 2.3kb
Promise polyfill: 1k
Fetch pollyfill: 650b
Preact cli: 250b

I got a big improvement by disabling css source map:
```js
  let cssLoader = helpers.getLoadersByName(config, 'css-loader')[0]
  cssLoader.loader.options.sourceMap = false
```
Im looking for a smaller alternative to style and css loader

**Comment by ForsakenHarmony** [comment]
How big is your css gzipped?

**Comment by rafaellages-hotmart** [comment]
7.3k

**Comment by developit** [comment]
Seems like we might have a messed up css-loader config.

**Comment by yaitskov** [comment]
What style loader did you use?
 https://github.com/webpack-contrib/style-loader has ridiculous size (5kb).
