### ISSUE TITLE
How to add custom polyfill?

### ISSUE THREAD

**Issue by lchimaru** [developit/preact-cli#676]
Hey I wanted to ask what's the best approach to add custom polyfill (like IntersectionObserver)? I believe it should be added to html template file similar to fetch polyfill. The only difference is that such import is done on application side, not preact-cli webpack configuration. Any ideas? 
Sorry I'm not very familiar with webpack.

**Comment by ForsakenHarmony** [comment]
We're looking to expore the html template very soon, so you could add it there

**Comment by ForsakenHarmony** [comment]
next exports the template
