### ISSUE TITLE
MiniCssExtractPlugin uses '[id]' rather than '[name]' for 'chunkFilename'

### ISSUE THREAD

**Issue by johnhaitas** [developit/preact-cli#679]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behaviour?**
`next` branch names css chunk files with `[id]` rather than `[name]`

**If the current behaviour is a bug, please provide the steps to reproduce.**
production build using `preact build` using `preact-cli@next`

**What is the expected behaviour?**
files should be named according to their chunk name rather than with a number.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version
- npm version
- Operating system
- CLI version: 3.0.0-next.14
- Browser

**Comment by johnhaitas** [comment]
My short-term local workaround is to add the following to my preact config transform
```javascript
helpers.getPluginsByName(config, 'MiniCssExtractPlugin')
	.forEach(({ plugin }) => plugin.options.chunkFilename = plugin.options.chunkFilename.replace('[id]', '[name]'));
```

**Comment by reznord** [comment]
Yep, cuz it is already merged in `next`

**Comment by johnhaitas** [comment]
Thanks all
