### ISSUE TITLE
npm Err! code EPERM and errno 4048 syscall unlink

### ISSUE THREAD

**Issue by michaeldoss21** [developit/preact-cli#682]
I am unable to create new Angular project. I got this error.

I done the following steps
1. npm cache clean
2. npm init
3. ng new newAngApp

- Node version - 10.14.1
- npm version - 6.4.1
- Operating system - Windows 10
- CLI version 
- Browser

What i am missing. Kindly help me.
![issue2](https://user-images.githubusercontent.com/45739271/49709280-8648b180-fc59-11e8-967f-201b3ee24a7b.png)

**Comment by ForsakenHarmony** [comment]
This is preact-cli, not angular 🤔
