### ISSUE TITLE
Can't setup Preact with express

### ISSUE THREAD

**Issue by UzumakiNaruto777** [developit/preact-cli#687]
Hello everyone, I really like Preact and I already have 1 project up and running. Now I am having issues to set up preact with express. I searched all the web but I couldn't find a clean example of how can I serve the pages with express. I am using Preact CLI to create my app (default). 

Or if there is an easier way to connect to database will be even better.

Thanks.

**Comment by prateekbh** [comment]
So once `preact-cli` builds the project you can serve the `build` folder as a static folder and expose APIs in regular fashion. 

Is there a specific part you are stuck with?

**Comment by UzumakiNaruto777** [comment]
I solved it thanks anyway
