### ISSUE TITLE
Blank source map for style.css

### ISSUE THREAD

**Issue by thangngoc89** [developit/preact-cli#69]
The generated style.css.map is currently blank right now

**Comment by developit** [comment]
funky. is that using less or sass at all?

**Comment by thangngoc89** [comment]
@developit just plain CSS Modules

**Comment by reznord** [comment]
@thangngoc89 can you confirm if this issue still persists?

It is not blank for plain CSS Modules. Have to test it for less/sass though.

**Comment by thangngoc89** [comment]
@reznord I don't use preact-cli newest version so can't confirm it. In fact, I'm forking preact-cli

**Comment by reznord** [comment]
@thangngoc89 it is generating the source maps for the `style.css` also.
