### ISSUE TITLE
Add push notification preact-cli

### ISSUE THREAD

**Issue by mweissen** [developit/preact-cli#699]
**Do you want to request a *feature* or report a *bug*?**
I want to request a feature.

**What is the current behaviour?**

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**
I fear that is the wrong group, but I did not find another one. Is there any group / forum  for beginners with preact? I have started with my first small project with preact (a website to show the content of my library) - it worked fine. Now I want to add  push and notification. I think, these are very important functions and there should a feature to install these functions in a very simple way. Maybe a collection of working full examples would help. 

I have tried 

- [Service Worker Magic with Workbox & Preact](https://medium.com/@applification/service-worker-magic-with-workbox-preact-c9ef35e063ec)
- [Preact-cli and service worker](https://medium.com/@prateekbh/preact-cli-and-service-worker-2e0f034157e7)

and a lot of other pages. But everything worked only for the first steps and then I got some error messages like

> Invalid hosting.header extglob **/*.chunk.*.js: error parsing regexp: missing closing ]: `[^\]*\.chunk\.[^\]*\.js$`

Or a hint like: _Everything is now set up for you to add to service-worker.js and customise your service worker as needed._ Yes, I want to setup .. but how to get a push to run?

May I repeat: I want to install preacht-cli out of the box and add push + notifivcations: it should be made simple.

**Please mention other relevant information.**
- Node version 10.14.1
- npm version 6.4.1
- Operating system windows 10
- CLI version preact-cli 2.2.1
- Browser chrome, opera

**Comment by ForsakenHarmony** [comment]
Sorry we don't have anything like this currently and it's not planned, you'd have to write it yourself
