### ISSUE TITLE
Custom server support

### ISSUE THREAD

**Issue by robinvdvleuten** [developit/preact-cli#70]
Instead of having a static production-like server when building for production. It would definitely be awesome to have some kind of "custom server" type of output like [next.js](https://github.com/zeit/next.js#custom-server-and-routing) has.

**Comment by thangngoc89** [comment]
@robinvdvleuten I think preact-cli and next.js are 2 different beasts. You can serve the static build with any server. So no need for support from preact-cli. Just build your own :D

**Comment by robinvdvleuten** [comment]
@thangngoc89 I am aware of that, but the preact-cli also has supports for prerendering. It would be nice if there is some sort of exposed API for this so that you still can rely on the webpack / babel configuration of this project :)

**Comment by thangngoc89** [comment]
@robinvdvleuten I think the prerendering is done in build step. Check out `index.html`, you'll see the rendered code of your index route

**Comment by developit** [comment]
If we end up with a UMD or CommonJS bundle output from something like #71, you could use preact-cli as an opaque compiler within a Node server.  I'm not sure it'd fit perfectly into `preact-cli` itself, but certainly I could see supporting something like this:

```js
import { h } from 'preact';
import express from 'express';
import { build } from 'preact-cli';
import renderToString from 'preact-render-to-string';

const app = build('./client', { format: 'umd' }).then( output => require(output.main) );

const app = express();
app.get( (req, res) => {
  app.then( App => {
    let body = renderToString(<App url={req.path} />);
    res.send(`<!doctype html><html lang="en">${body}`);
  });
});
app.listen(process.env.PORT);
```

**Comment by robinvdvleuten** [comment]
@developit that's exactly the kind of interface I meant! I do not expect that preact-cli becomes some kind of prext.js, but it would be great if it provides some kind of interface / functionality to build this kind of tooling upon. The only thing the preact-cli should do extra I guess is to expose the build process. Is there any way I can help with this?

**Comment by developit** [comment]
Any experimentation you have time to do would be appreciated.  The API we can solidify later, but I'd love to get some experiments done around returning a reusable "preact compiler" instance.

**Comment by robinvdvleuten** [comment]
@developit I've created a PR for exposing a compiler instance, let's continue the discussion there.
