### ISSUE TITLE
Encoding images in base64 in scss

### ISSUE THREAD

**Issue by Acika00mk** [developit/preact-cli#703]
**Do you want to request a *feature* or report a *bug*?**
Reporting a bug

**What is the current behaviour?**
When i assign images in the scss it doesnt link them when built it creates base64 data image 
<img width="387" alt="screen shot 2019-01-18 at 16 02 04" src="https://user-images.githubusercontent.com/4304026/51437660-674e2e00-1ca1-11e9-9cab-1ecd831db7b3.png">
<img width="500" alt="screen shot 2019-01-18 at 16 01 57" src="https://user-images.githubusercontent.com/4304026/51437661-67e6c480-1ca1-11e9-836c-99029bdf00f9.png">

Is there any configuration fix for this ?
Coz the image quality is not that good and the file get bigger and bigger if more images are assigned like this. 
**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
To link the images, not to create data image

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version v10.14.2
- npm version 6.4.1
- Operating system macOS Mojave 
- CLI version 2.2.1
- Browser all

**Comment by Panya** [comment]
It's not Preact that doing this, I guess it's your webpack or other building tool (see for url-loader in webpack case).

**Comment by Panya** [comment]
It's only for dev mode. See https://github.com/developit/preact-cli/blob/master/src/lib/webpack/webpack-base-config.js#L197-L200
