### ISSUE TITLE
Provide prerender urls using JS file

### ISSUE THREAD

**Issue by psabharwal123** [developit/preact-cli#717]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behaviour?**
prerender urls file can only be json

**If the current behaviour is a bug, please provide the steps to reproduce.**
open any preact cli template

**What is the expected behaviour?**
we can provide prerender urls using a js file

**If this is a feature request, what is motivation or use case for changing the behaviour?**
Use case is that prerender urls might be generated dynamically by Js

**Please mention other relevant information.**
- Node version
- npm version
- Operating system
- CLI version
- Browser

**Comment by ForsakenHarmony** [comment]
it's in `@next`

**Comment by psabharwal123** [comment]
i am using 3.0.0-next.14, which next is it in?
