### ISSUE TITLE
Flag to enable react hot loader with default set to false

### ISSUE THREAD

**Issue by psabharwal123** [developit/preact-cli#722]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behaviour?**
no way to disable / not use react hot loader

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
react hot loader should be disabled by default, and a flag to enable it

**If this is a feature request, what is motivation or use case for changing the behaviour?**
As per https://github.com/gaearon/react-hot-loader#preact it does not support HOCs. In our particular case we are using unistore and HMR is broken now. When a change is made, page displays a banner with message error hot update was not successful. This was working fine before react hot loader was added. 

**Please mention other relevant information.**
- Node version latest
- npm version latest
- Operating system windows
- CLI version 3.0.0-next.16
- Browser chrome

**Comment by prateekbh** [comment]
cc: @ForsakenHarmony

**Comment by ForsakenHarmony** [comment]
I mean you could submit a pr for it

**Comment by psabharwal123** [comment]
done
