### ISSUE TITLE
ESM Build Causes error

### ISSUE THREAD

**Issue by hassanbazzi** [developit/preact-cli#733]
Getting a bug when esm build is used. Opting out using the esm flag fixes it.

Error:

Uncaught TypeError: Cannot read property 'webpackJsonp' of undefined
    at bootstrap:230
    at bootstrap:239

This is using the latest version of preact-cli.

**Comment by prateekbh** [comment]
I am still trying to debug this... Some funky code splitting has happened which has caused this...

**Comment by prateekbh** [comment]
preact-www has this line
https://github.com/developit/preact-www/blob/next-cli/preact.config.js#L15

which makes the global object to `this` and `this` is undefined in `<script type=module` thus the undefined error.

Please explain why we need this line.
