### ISSUE TITLE
'npm run serve' shows TLS error and the site is not running

### ISSUE THREAD

**Issue by oren** [developit/preact-cli#74]
`npm run serve` show me TLS error in the terminal and going to http://localhost:8080/ on chrome tells me "site can't be reached"

Steps to reproduce:
```
preact create app --type full
cd app
npm run serve
```

Output:
```
> app@1.0.0 serve /tmp/app
> preact build && preact serve

Build [==================  ] 91% (2.5s) additional asset processing
  Total precache size is about 173 kB for 15 resources.

  Listening on https://localhost:8080...
  http: TLS handshake error from [::1]:46434: read tcp [::1]:8080->[::1]:46434: use of closed network connection
  http: TLS handshake error from [::1]:46436: read tcp [::1]:8080->[::1]:46436: use of closed network connection
  http: TLS handshake error from [::1]:46440: read tcp [::1]:8080->[::1]:46440: use of closed network connection
  http: TLS handshake error from [::1]:46552: read tcp [::1]:8080->[::1]:46552: use of closed network connection
```

More info:

* Ubuntu 16.04
* npm 5.0.0
* node 7.7.4

**Comment by thangngoc89** [comment]
Try https://localhost:8080

**Comment by oren** [comment]
works (after I ignored the browser's warning about insecure connection). is that normal?
btw, when i tried to deployed it to my real production server I saw some error as well instead of the html. I can try it and report back.

**Comment by oren** [comment]
I was able to reproduce it. here is what I see in my browser.
```
Html Webpack Plugin:
  ReferenceError: window is not defined
  
  - polyfill.js:1 Object.
    [admin]/[unfetch]/polyfill.js:1:6
  
  - node.js:152 Object.require.extensions.(anonymous function) [as .js]
    [admin]/[babel-register]/lib/node.js:152:7
  
  - module.js:20 require
    internal/module.js:20:19
  
  - polyfills.js:5 Object.
    /home/oren/p/healthco/admin/src/lib/polyfills.js:5:1
  
  - node.js:144 loader
    [admin]/[babel-register]/lib/node.js:144:5
  
  - node.js:154 Object.require.extensions.(anonymous function) [as .js]
    [admin]/[babel-register]/lib/node.js:154:7
  
  - module.js:20 require
    internal/module.js:20:19
  
  - index.js:3 Object.
    /home/oren/p/healthco/admin/src/index.js:3:1
  
  - node.js:144 loader
    [admin]/[babel-register]/lib/node.js:144:5
  
  - node.js:154 Object.require.extensions.(anonymous function) [as .js]
    [admin]/[babel-register]/lib/node.js:154:7
```
It's based on `preact create app --type full` with some modifications.
This is my code base - https://github.com/oren/admin/tree/9cd58dd71f934098a4b619b2a396c069ba5d1e8c

**Comment by thangngoc89** [comment]
@oren This is the error from the prerender. You need to check for window object before adding anything to it. Open this file: https://github.com/oren/admin/blob/9cd58dd71f934098a4b619b2a396c069ba5d1e8c/src/lib/polyfills.js

Wrap everything in this block:

```
if (typeof window !== "underfined") {

}
```

> after I ignored the browser's warning about insecure connection

Add the cert of preact-cli to your system trust certificate list and you'll get a green lock. Or just ignore it

**Comment by oren** [comment]
I tried following your advice but maybe i did it wrong since i still see the error:
https://github.com/oren/admin/blob/c61a369498d7dddd658cd3dd6bfaa3a07f807b9f/src/lib/polyfills.js#L9
(i tried to wrap also the two mports but it didn't let me).

"Add the cert of preact-cli to your system trust certificate list" - where can I find those certs? I'll google for the entire thing. Thanks!

**Comment by thangngoc89** [comment]
@oren oh my fault. Typing this on the phone with out a IDE. It should be `typeof window !== undefined`

You can find preact-cli cert here. https://github.com/developit/preact-cli/tree/984476fb171e73a4224f304e7c127063266de8a8/src/resources

You can use it, or create your own certificates and run the server with it.

Some resources for you:

- https://gist.github.com/jed/6147872
- https://certsimple.com/blog/localhost-ssl-fix

**Comment by thangngoc89** [comment]
And I noticed you added an Object.assign polyfill. I think babel already include that when you use spread operator.

This is straight from my bundle:

![image](https://cloud.githubusercontent.com/assets/3049054/26584241/5689e364-4572-11e7-9df6-977ec09c3f58.png)

**Comment by oren** [comment]
even after correcting the spelling to "undefined" I get the same error. Also, it looks like it's impossible to have the import lines inside an if statement so the if should probably be right after the imports.

**Comment by oren** [comment]
It looks like the issue is coming from the import lines:
```js
/* eslint eqeqeq: "off" */
// polyfills for fetch, Promise, and Object.assign

import 'unfetch/polyfill'
import Promise from 'promise-polyfill'
```

[Here](https://github.com/oren/admin/blob/a29f8d8deeeedaed90ff5c935a2cd18ab70f2d63/src/lib/polyfills.js) is my code.

btw, if I remove the import lines I am getting another error: Template execution failed: ReferenceError: localStorage is not defined

I don't understand what changed from the boilerplate. I had no issues with the same exact codebase.

**Comment by developit** [comment]
@oren both of those libraries (unfetch and promise-polyfill) are actually already polyfilled for you by preact-cli, so you can remove those lines entirely including the window check :)

**Comment by oren** [comment]
Thanks for elaborating!

I'll try all that and report back but i don't understand why do i need to wrap the localStorage and what is the benefit of using the prerender?

also what happened if `typeof localStorage==='object'` is falsy? the function will return a useless object since the getter and setter returns empty object.

**Comment by oren** [comment]
btw, this is insightful for others as well and should be as part of a formal tutorial or a how-to guide. people won't notice it if this is buried in a closed issue on github (:

**Comment by thangngoc89** [comment]
@oren  Prerender means produces a static HTML build of your application at build time. If you want to learn more, search for React server side rendering. 

In  [PRPL Pattern](https://developers.google.com/web/fundamentals/performance/prpl-pattern/). R stands for render initial route.

Currently, preact-cli uses node environment to prerender your application. Since localstorage is a browser specific API and it's not available on Node enviroment. An error will be throw about accessing an property from `undefined` object. 

> what happened if typeof localStorage==='object' is falsy

Nothing. Prerender process skips that blocks of code and move on. ==> No error will be throwed

I hope I was clear enough.

**Comment by oren** [comment]
Thanks! i'll search for react server side rendering. what if i don't need
server side rendering (my backend in Go btw)? does it mean I can run it
with `npm run build -- --no-prerender` ?

**Comment by thangngoc89** [comment]
@oren Prerender !== server side rendering (SSR) 

Prerender means using SSR technique to render your initial route at build time. When prerender is enabled, the users of your application will see the first meaningful paint faster. ==> better UX.

But you can safely run it with `npm run build -- --no-prerender`

**Comment by rkostrzewski** [comment]
@oren yeah, running ```npm run build -- --no-prerender``` won't trigger prerendering. You could simplify things and change your package.json to have ```build``` script set up to ```preact build --no-prerender```.

You should be aware that prerendering done by preact-cli isn't exactly what normal server side rendering looks like. Traditionally SSR occurs when browser asks for a page (e.g. ```/products/1```) and whole page send to client contains product info right in html saving trips to the server from JS code. What preact-cli does is renders initial route (home route aka '/') right to the index.html this way when browser asks for any page it will receive default which means showing something to user as fast as possible, and later JS takes off and does it's magic with what should be displayed and how.

**Comment by oren** [comment]
Thanks for all the tips. I kept the prerender and removed everything I don't need. I also patched the localStorage. It looks like every time I use a browser-specific feature that is not available to Node.js I'll have to do that.

Thank you @thangngoc89 for making the connection between the prerenderer to the PRPL pattern. I wonder if the others letters are also being implemented by preact-cli? push, pre-cache, and lazy-load.

**Comment by lukeed** [comment]
> I wonder if the other letters of that pattern are also being implemented by preact-cli? push, pre-cache, and lazy-load.

Yup! All letters are included out-of-the-box!

**Comment by oren** [comment]
amazing. can you elaborate? where exactly can I find each one or it's not trivial to isolate them?

**Comment by lukeed** [comment]
- Push: `serve` (by default) creates a `simplehttp2server`, which is a HTTP2/Push server. You can check the console for verification.
- Precache: The service worker is configured for offline use.
- Lazy-Load: Automatic code-splitting for routes and shared "chunks" are optimized for reuse. Navigating from `/about` to `/contact` will dynamically (or "lazily") load the "contact" bundle and any associated chunks. This is all thanks to webpack.

**Comment by oren** [comment]
interesting. I am looking at the build folder and it seems like `npm run build` creates mulitple js files. is it safet to assume it's js file per component? That's interesting! I always thought webpack just create a single file.

```
assetsassets
bundle.js
favicon.ico
index.html
manifest.json
polyfills.chunk.c1c58f9d71972b0f655b.js
push-manifest.json
route-clinic.chunk.70eb7b50f758c42800e5.js
route-create-clinic.chunk.324b5aab5a797d8664f2.js
route-home.chunk.5ff61a9d8f158dd93dad.js
route-login.chunk.9e1344c11522cff8e6d8.js
style.css
style.css.map
sw.js
```

**Comment by lukeed** [comment]
Yup, by default it will, but it has been configured to route-split. If you take a look at your files:

* `bundle.js` is the shared/main file -- Preact & co will be there.
* Each `route-*` is a route-specific entry file. Your `route-login` will only ("lazy") load when `/login` is active. Same goes for `home`, `clinic`, etc.
* As your app grows, you'll get more `route-*` files. You will also (sometimes) get smaller chunks for the same route, depending on what kind of activity is happening on that page.

**Comment by oren** [comment]
amazing. it allows us to build apps with a lot of components and the client will only have to download the component that is actually being used. I wonder if there is a way to tell preact to to fetch a component a head of time if i know that a component is going to get rendered in the future. maybe based on mouse location.

Also, is [this](https://github.com/developit/preact-cli/blob/master/src/lib/webpack-config.js#L321) the correct webpack code that responsible for the route-split?

**Comment by lukeed** [comment]
Nope, [here](https://github.com/developit/preact-cli/blob/master/src/lib/webpack-config.js#L111-L137).

Also, what you're thinking about is calling `link-prefetch`. I've also seen a few components out there that "bake" in a similar behavior.

**Comment by developit** [comment]
Just to clarify - the JS files are automatically split up based on your routes by default.  You can also split any component by prefixing the import:

```js
// before: (bundled)
import Foo from './foo';
export () => <Foo />

// after: (automatically code-split)
import Foo from 'async!./foo';
export () => <Foo />
```

Regarding prefetch, that's something I'd love to get merged in.  Right now we do it for routes by h/2 pushing the chunks for that route.  For now, the ServiceWorker actually prefetches the remaining route chunks, so they're usually already downloaded by the time a user would click a link that depends on another chunk.

**Comment by oren** [comment]
@developit tell me if I understand what you wrote about the ServiceWorker. If the render function in my home component have the following:
```js
return (
	<div class={style.home}>
		<div class={style.createClinic}>
		<a href="/clinic/new">Create Clinic</a>
		</div>

		<h1>Clinics</h1>
		{clinics.map(clinic => {
			return (
				<section>
					<a href={"/clinic/" + slugify(clinic.name)}>{clinic.name}</a>
					{' '}
					{' '}
				</section>
			)
		})}
	</div>
)
```
Will the component behind /clinic/new and the component behing /clinic/clinic-name will be downloaded and rendered as soon as i am in the home component? That's not what I observe in the 'network' tab on the chrome dev console.

@lukeed I noticed this line
```
return isRoute ? 'route-' + relative.replace(/(^\/(routes|components\/(routes|async))\/|(\/index)?\.js$)/g, '') : false;
```
Does it mean that the only components that are in the routes folder or the components folder are not bundled in bundle.js and are not lazy loaded? I am asking this because if that's the case, it's important to share this with other developers that are using preact-cli. We should be aware of it and keep our components in those two folders.

**Comment by developit** [comment]
Yes, that is the default. I believe there is an option (can't remember the name) to specify a match pattern for automatic asynchronous components. 

Without using `routes/*`, you would just need to manually apply async to an import:

```js
import Clinic from 'async!./clinic';

<Router>
  <Clinic />
</Router>
```
