### ISSUE TITLE
[next] Service Worker precaches HTML files, but they aren't used

### ISSUE THREAD

**Issue by developit** [developit/preact-cli#751]
In CLI@next, the ServiceWorker setup pre-caches all HTML files produced by `prerender-urls.json`. This is great, except we never use those cache entries. They all have `/index.html` appended for our pretty URL handling, so they are cache misses.

Even with that stripped out though, routing around a website built with Preact CLI doesn't do full page navigations such that the prerendered HTML is used.

Instead, it seems like we need to pre-cache the route JS but not the HTML. The only HTML we should precache is `/index.html`, and it should be served up for all requests that are cache misses when offline.

/cc @prateekbh

**Comment by prateekbh** [comment]
added the fix in #674
