### ISSUE TITLE
Adding third parties script

### ISSUE THREAD

**Issue by thierryskoda** [developit/preact-cli#76]
Hi, I can't find the `index.html` file. Is there another way to add custom third parties scripts ? 

Thank you very much in advance!

**Comment by lukeed** [comment]
Hi there! This is a duplicate of #51 and is currently being discussed & worked on.

I'm going to go ahead & close this so that the issue can be tracked in one location. Thanks! 😃

**Comment by lukeed** [comment]
For the time being, you can import your 3rd party scripts & styles via the `index.js`. Most things are already on NPM && webpack is configured with the appropriate loaders to handle what you import.

Hope that helps!

**Comment by thierryskoda** [comment]
Sorry I didn't see the other thread. Great yes I will try this. 😄  

Thank you
