### ISSUE TITLE
bug: preact watch with --esm flag will crash to shell if syntax error is saved in any file being watched

### ISSUE THREAD

**Issue by shoojx** [developit/preact-cli#765]
**Do you want to request a _feature_ or report a _bug_?**
Report a bug.

**What is the current behaviour?**
local build being watched errors out and preact watch command has to be run again

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. Open any file in the project being watched.
2. Add a syntax error to the file.
3. Save / autosave the change.

**What is the expected behaviour?**
local build being watched displays stack, but doesn't error out of build, and then recovers after syntax error is fixed.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

- Node version
- npm version
- Operating system
- CLI version
- Browser

**Comment by psabharwal123** [comment]
@shoojx please fill out relevant information, after that @prateekbh could you please have a look?

**Comment by prateekbh** [comment]
I am out till Sunday, will look once m back

**Comment by prateekbh** [comment]
I can see the error stack with `--esm` https://pastebin.com/Z074d4bS
Fixing these in my editor also brings everything back on its track.

Is there a specific kind of bug which crashes it?

**Comment by psabharwal123** [comment]
unable to repro on 3.0.0-rc.1, was happening on an older version

**Comment by prateekbh** [comment]
closing this for now
