### ISSUE TITLE
Preact-CLI prerender issue after 'build' (in dev it works fine) 

### ISSUE THREAD

**Issue by Yeahjoep** [developit/preact-cli#779]
I am working on a Preact-CLI project with a Preact-Router and it works fine on the localhost. But the production doesn't work well after the build.

I have created a one page object which gets its content dynamically from a JSON file (inside the project not external). So I've loaded the same page object 2 times for each different page.

I get the page url (using this.props.permalink) and compare it with the JSONObject.title. If they are the same I want to get the corresponding JSON content to display it on the corrrct page. Works like a charm on localhost, but not in production.

Issue: Somehow all pages get the content of the first JSON element. First I thought it was a server issue but I was wrong. The builded files are wrong after the prerendering/build. So the prerendered html of page B contains the content of the prerendered page A. My guess is that during the build this.props.permalink doesn't work. How should I handle this?

Additional info: I use the prerender function but not the service worker for the build.

Thanks!

**Comment by Yeahjoep** [comment]
UPDATE: I have rewritten the function. I guessed I needed to set the dynamic content through a loop, so that during the build the compiler loops through it and is able to prerender all the pages.

The iteration and setting the state works, but only the final element of the PrerenderUrls array gets stored. so now I get one empty page and one page with content.
```

componentWillMount() {


        for (var i = 0; i <= PrerenderUrls.length; i++) {

            // the code you're looking for
            let removeDash = new RegExp("-")
            var needle = PrerenderUrls[i].title
            var needle1 = needle.replace(removeDash, " ")
            alert("1")


            // iterate over each element in the array
            if (needle1 != "Homepage") {
                for (var x = 0; x < Data.length; x++) {

                    // look for the entry with a matching `code` value
                    let removeDash = new RegExp("-")
                    var nodash = Data[x].title.replace(removeDash, " ")
                    var nocaps = nodash.toLowerCase()
                    if (nocaps == needle1) {

                        alert("needle2: "+ needle1 + " nocaps: " + nocaps)
                        //alert("data "+ Data[x].title)
                        this.setState({
                            pageTitle: Data[x].title,
                            descShort: Data[x].descShort,
                            description: Data[x].desc,
                            img: Data[x].img
                        })
                        alert("state "+ this.state.pageTitle)
                    } 
                } 
            }
        }
```

**Comment by ForsakenHarmony** [comment]
where do you get the `this.props.permalink` from?

**Comment by Yeahjoep** [comment]
I get it from the app.js like so. It does work.

```
			<div id="app">
				<Header />
				<Subheader /> 
				<Router onChange={this.handleRoute}>
					<Home path="/" />
					<Singlepage path="/page1" 	permalink={this.state.url} />
					<Singlepage path="/page2" 		permalink={this.state.url}/>
				</Router>
			</div>
```

**Comment by ForsakenHarmony** [comment]
You could instead just use `this.props.url` which gets passed by the router already afaik

**Comment by Yeahjoep** [comment]
Thanks! It was cleaned up my code and was related to an other issue I had.

**Comment by ForsakenHarmony** [comment]
oh, nice
