### ISSUE TITLE
How to pass object with information into my clinic component?

### ISSUE THREAD

**Issue by oren** [developit/preact-cli#78]
My home component makes HTTP requests and display list of clinics. When the user click on a link for a clinic I would like to pass that clinic information into the clinic component.
How do I do that?

[Here](https://github.com/oren/admin/blob/c146a55b57fdd4c666f4b41fc92b0a57b804f2df/src/routes/home/index.js#L60) are the links in my home component:
```js
{clinics.map(clinic => {
  return (
    <section>
      <a href={"/clinic/" + slugify(clinic.name)}>{clinic.name}</a>
      {' '}
      {' '}
    </section>
  )
})}

```

And [here](https://github.com/oren/admin/blob/c146a55b57fdd4c666f4b41fc92b0a57b804f2df/src/components/app.js#L52) is my Clinic inside the router component in app.js
```
<Clinic path="/clinic/:id" />
```

Thanks!

**Comment by prateekbh** [comment]
@oren though this doesn't seem related directly to `preact-cli`, i'll try to answer this.

You can always maintain a central data store where all of your components can access that.
dirties possible way: `window.clinicdata = {...}`
also you can try a more favorable way of using redux stores etc.

if you want a more deeper opinion, join the brilliant preact community on slack may b.
https://preact.slack.com

**Comment by oren** [comment]
Thank you prateek. Maybe I am at a point where it is worth adding a state management library. I was trying to not use it unless I see the need.

I am already in slack but I feel like slack is not good for documenting thinks since it's not organized and even if I get answer to my question, nobody else will benefit from it. I think we need a place for the community to add tutorials and how-to guides.

**Comment by developit** [comment]
You don't necessarily need a state management library, you need a cache.  Since your Clinic component is URL-addressable, it can't rely on some other component (another route) having fetched its data.  Instead, it should fetch the data itself when mounted.  Avoiding re-fetching the data when routing from a component that already did it is actually just an optimization problem.  A simple cache with a TTL would work there.

**Comment by oren** [comment]
Very interesting! 

What are my options when it comes to cache? Here are a few a can think of but I am sure there are better ways:
1. window.clinicData = {name: 'healthy life'}
2. localStorage.setItem(clinicData, {name: 'healthy life'})
3. cookies (I rather not use cookies)

Anything else I should consider? Any good how-to guides or tutorial would be fantastic.

**Comment by thangngoc89** [comment]
@oren 

1. Super fast. Not persist across tabs and sessions.
2. Fast enough. Persist. By synchronous API so beware of locking your main thread
3. Eh. I only use http only cookie these day.

To consider: IndexDB (async API, but not cross-browser support)

**Comment by oren** [comment]
can you elaborate about 3? is that your preferred approach? if so, why?

**Comment by thangngoc89** [comment]
@oren No. I dont prefer 3 approach. Mine prefer is localstorage, but again. It's a synchronous API so beware.

**Comment by oren** [comment]
awesome. i'll use localeStorage and make sure to measure the performance. currently my clinic object is pretty small but it's good to be aware of it. I really think preact should have another place where we can have how-to guides and tutorials. this conversation is relevant to many other developers and slack is not the right place for it.

**Comment by developit** [comment]
Personally I'd use the in-memory cache (option 1), since your goal here is to de-duplicate HTTP requests between components within the same page.  Using a persisted cache means you have to start looking at setting expiry and managing space (localStorage is limited to 5mb).
