### ISSUE TITLE
How can I call a method from an other class?

### ISSUE THREAD

**Issue by Yeahjoep** [developit/preact-cli#780]
I am still a rookie in frontend. I have 2 **NON RELATED** (no parent/child relation) classes:

search.js
Class Search{
   method 1,
   method 2
   state A,
   state B
}

view.js
Class view{
     content
}

I am trying to: 
1. call a **search.js** method from **view.js**.
2. change state value of **search.js** from **view.js**

Don't forget: these classes are non-related. Thanks!

**Comment by prateekbh** [comment]
You can use ES modules to import and create object of both of them and call the functions of each other.

A better suited question for stackoverflow may be?
