### ISSUE TITLE
sw-worker depreciated use Workbox

### ISSUE THREAD

**Issue by brandonkal** [developit/preact-cli#782]
**Do you want to request a _feature_ or report a _bug_?**

Feature request

**What is the current behaviour?**

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

sw-precache is depreciated. Please switch to workbox for the service worker.
https://github.com/GoogleChromeLabs/sw-precache
https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw

**Please mention other relevant information.**

- Node version
- npm version
- Operating system
- CLI version
- Browser

**Comment by prateekbh** [comment]
HI @brandonkal , Thanks for the issue, the next version of preact-cli `preact-cli@3.0.0-rc.1` has already been switched to Workbox.

**Comment by brandonkal** [comment]
@prateekbh Awesome! The readme doesn't reflect that change as it still mentions sw-precache.

**Comment by ForsakenHarmony** [comment]
Oh yeah we might want to update that, thanks

**Comment by jliebrand** [comment]
Is there any more information on how it is integrated and how to configure it? We used to use preact-cli-sw-precache but it would appear that it stopped working (I'm assuming because of the change to workbox).

In particular we like to set things like skipWaiting to true... some examples of config would be great!

**Comment by bionicles** [comment]
How do you set this up?

**Comment by prateekbh** [comment]
In next version when you setup a project you should be able to find sw.js in your codebase. 
You can either directly edit this file or use the plugin we'll write to change the configs for the new sw.

Right now you can copy this [file](https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/sw.js) and paste it in your folder to edit it. preact-cli will the file in your source code
