### ISSUE TITLE
TypeError: Transformer is not a function

### ISSUE THREAD

**Issue by NicolaiSchmid** [developit/preact-cli#789]
I'm running rc1 of preact-cli and whenever I create a `preact.config.js` file (empty or not) I get `TypeError: transformer is not a function`

**Do you want to request a _feature_ or report a _bug_?**
Bug
**What is the current behaviour?**

When creating a preact.config.js file the build fails with `TypeError: transformer is not a function`

I think I have narrowed the issue down to this [line](https://github.com/developit/preact-cli/blob/master/packages/cli/lib/lib/webpack/transform-config.js#L112)

When the file exists and contains this:
```javascript
export default {
    webpack() {}
};
```
The `const transformer` contains the config object itself: `{ webpack: [Function: webpack] }`
Shouldn't it have the value of the function itself? 

Plus, if I export an empty object `export default {}` `transformer` contains the empty object and not `undefined`

- Node version
v12.1.0
- npm version
6.9.0
- Operating system
arch
- CLI version
rc1

**Comment by prateekbh** [comment]
can you post a sample config of yours?

**Comment by NicolaiSchmid** [comment]
I did. The error occurs with an empty file (no default exports), an empty export (‘export default {}’) and even with the sample config from the Readme

**Comment by lukeed** [comment]
If a file exists, it has to export a function

**Comment by NicolaiSchmid** [comment]
Makes sense. But even with an empty object or and object with a function on the webpack key the error occurs

**Comment by ForsakenHarmony** [comment]
it works with your config, are you sure you're on `rc`?

**Comment by hnlinzhi19** [comment]
I have the same question, i only create a project from cli tool, then add preact.config.js

**Comment by NicolaiSchmid** [comment]
@ForsakenHarmony 
Fresh install of preact-cli@rc, 
`preact create default test`, 
```bash
cat > preact.config.js << EOF
export default {};
EOF
```
`npm start`: `TypeError: transformer is not a function`

So yes, I'm on RC and this is my exact setup in which the error occurs, same as @hnlinzhi19 described

**Comment by ForsakenHarmony** [comment]
oh you have to upgrade preact cli in the project as well, it'S still the old version

**Comment by NicolaiSchmid** [comment]
Thanks for that! 👍
Should've caught it myself! 🙈

**Comment by ForsakenHarmony** [comment]
No worries, happens to all of us sometimes 🙃
