### ISSUE TITLE
Spaces instead of tabs

### ISSUE THREAD

**Issue by JMSantos94** [developit/preact-cli#79]
I know this is a minor thing, but could we somewhere on the roadmap have a small configuration option to use **spaces** instead of **tabs**?

For now good old sed: `sed -i.bak -E $'s/\t/  /' fileName.js`

**Comment by prateekbh** [comment]
how about `prettier`?

**Comment by prateekbh** [comment]
@developit @kristoferbaxter @lukeed do we want linters and prettier to be added?

**Comment by lukeed** [comment]
I may be alone on this, but I believe this is user land. Once #56 makes its way in, devs can add in whatever they'd like. And in the meantime, `prettier` can be added now on top of any install.

Maybe we could include some recipes to illustrate how to achieve some of these things, but then this becomes yet another bit to maintain. What do you think?

**Comment by prateekbh** [comment]
@lukeed #56 is based for the project created with `preact-cli`.
whereas i was talking about adding `prettier` to the `preact-cli` codebase itself, to lint this repo, not the ones created with it.

**Comment by lukeed** [comment]
Oh, lol. But I think the issue was opened about the generated output?

**Comment by prateekbh** [comment]
ohh @JMSantos94 we need to ask you abt this 😛 
but anyways how about our project @lukeed ?

**Comment by lukeed** [comment]
Haha 😜 

As per our codebase, that's not up to me & I don't really have input there.

**Comment by JMSantos94** [comment]
@lukeed @prateekbh Sorry if I wasn't clear enough. Yes, I am referring to the output project when you use `preact create`. Prettier is a nice option, but I agree with @lukeed on it being on the user land.

**Comment by lukeed** [comment]
Cool 😄 Is it okay to close this issue then?

**Comment by JMSantos94** [comment]
I guess if it is complicated to do something like: 

`preact create some-project --indentation spaces`

... or not worth the time.

**Comment by developit** [comment]
Right now files aren't processed by `preact create`, just moved.

That said, I'd like to have `preact create [type]` actually go to Github to fetch the project, and scaffold it out from a real repo.  If we do that, we can have much more varied project types.  We'd also have the opportunity to transform incoming files, either manually or via `eslint --fix` / `prettier` / etc.  Vue-cli [uses a lib](https://github.com/vuejs/vue-cli/blob/master/bin/vue-init#L3) called `download-git-repo`, or we could use Yeoman which does transformations already.

**Comment by JMSantos94** [comment]
Thanks for the insight @developit!
Yeah, `.editorconfig` is pretty awesome.

As I mentioned before, this is not a big deal. Would be nice to keep it in somewhere though 😄

**Comment by reznord** [comment]
Leaving this here regarding 

https://twitter.com/JedWatson/status/875491536003186690

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by developit** [comment]
lol - correlation VS causation there, python is used for data science and that's a high paying career right now :P

**Comment by jeanleonino** [comment]
+1 for editorconfig

**Comment by reznord** [comment]
Now that we have moved to templates entirely, it is in the user-land.
