### ISSUE TITLE
Error with @babel/plugin-proposal-class-properties

### ISSUE THREAD

**Issue by douggr** [developit/preact-cli#791]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behaviour?**
Error: Decorating class property failed. Please ensure that proposal-class-properties is enabled and set to use loose mode.

**If the current behaviour is a bug, please provide the steps to reproduce.**
If you're able to run the `demo` in preact, just open the [people](https://github.com/developit/preact/tree/master/demo/people) app.

**What is the expected behaviour?**
No errors; use decorators.

**Please mention other relevant information.**

- Node version: v10.15.3
- npm version: 6.4.1
- yarn version: 1.15.2
- Operating system: N/A
- CLI version: 3.0.0-rc.1
- Browser: N/A

Option `{ loose: true }` should be set.

The error is at [babel-config.js#L28](https://github.com/developit/preact-cli/blob/master/packages/cli/lib/lib/babel-config.js#L28); replacing with `[require.resolve('@babel/plugin-proposal-class-properties'), { loose: true }]` will fix.

**Comment by ForsakenHarmony** [comment]
The people App?

**Comment by douggr** [comment]
Yes, in preact demos: https://github.com/developit/preact/tree/master/demo/people

**Comment by ForsakenHarmony** [comment]
Ah ok
