### ISSUE TITLE
host '0.0.0.0' is cast to 'localhost'

### ISSUE THREAD

**Issue by kekbait** [developit/preact-cli#796]
**Do you want to request a _feature_ or report a _bug_?**
Report a Bug
**What is the current behaviour?**
```preact watch``` command doesn't work in Docker
**If the current behaviour is a bug, please provide the steps to reproduce.**
Use this Dockerfile : 
```
FROM node:12.2.0-alpine as base
RUN npm install -g preact-cli
WORKDIR /app
```
and this docker-compose file:
```
version: "3.4"
services:

    app:
      build:
        context: .
      stdin_open: true
      tty: true
      ports :
        - "8080:8080"
      working_dir : /app
```

**What is the expected behaviour?**
When running ``` docker-compose run --service-ports app preact watch --host=0.0.0.0```, the port should be exposed to the external network.
It's not the case because of this line : 

https://github.com/developit/preact-cli/blob/533500309f982a2b03c6d49c977f7233ef561377/packages/cli/lib/lib/webpack/run-webpack.js#L46

**Comment by ForsakenHarmony** [comment]
you're saying it's unreachable externally?

**Comment by kekbait** [comment]
Yes exactly.
It's a way to specify "any IPv4 address at all", and it's always used when opening public ports in Docker containers. 

Create-react-app had the same kind of issue back then:
https://github.com/facebook/create-react-app/issues/137

**Comment by lukeed** [comment]
Yeah, it has to remain a network address for docker / VM users. Co-worker pointed this out to me for PWA
