### ISSUE TITLE
SASS: File to import not found or unreadable

### ISSUE THREAD

**Issue by ajviv** [developit/preact-cli#80]
importing `scss` seems to fail in index.scss

`
./~/css-loader?modules&localIdentName=[local]__[hash:base64:5]&importLoaders=1&sourceMap=false!./~/postcss-loader!./~/preact-cli/lib/lib/npm-install-loader.js?{"modules":["node-sass","sass-loader"],"save":true}!./~/preact-cli/~/sass-loader/lib/loader.js?{"sourceMap":true}!./components/header/style.scss
Module build failed: 
@import "themes/light";
^
      File to import not found or unreadable: themes/light.
Parent style sheet: stdin
      in /Users/avivek/Hack/experiments/preact/graburs/components/header/style.scss (line 1, column 1)
 @ ./components/header/style.scss 4:14-350 13:2-17:4 14:20-356
 @ ./components/header/index.js
 @ ./index.js
 @ ./~/preact-cli/lib/lib/entry.js
 @ multi ./~/preact-cli/lib/lib/entry webpack-dev-server/client?http://0.0.0.0:8080/ webpack/hot/dev-server?http://0.0.0.0:8080/
`

**Comment by developit** [comment]
Hi @ajviv - you need to use a relative path:

```css
@import "./themes/light";
```

**Comment by ajviv** [comment]
👍 That works
