### ISSUE TITLE
State array gets emptied after a method call

### ISSUE THREAD

**Issue by Yeahjoep** [developit/preact-cli#801]
I am trying to perform a filter on a Preact state array. From the HTML I call the search method.

Somehow the state array gets emptied from the moment I call:
**this.startSearch.bind(this).**

note: in the code underneath I've skipped the part where I fill the array.

```
export default class ItemList extends Component {
    state = {
        itemList: []
    }

startSearch(input){
    console.log(this.state.itemList)
    }


render() {
   return (
    <input type="text" id="inputField" value={this.state.searchInput} onInput={this.startSearch.bind(this)}></input>
    )}

```Any idea what I am missing out here?

**Comment by ForsakenHarmony** [comment]
I think this should be on the preact repo?
