### ISSUE TITLE
Should the source code not be stored in a src directory instead of the project root?

### ISSUE THREAD

**Issue by nelsyeung** [developit/preact-cli#81]
Shouldn't the generated source code be in a `src` directory by default instead of the project root?
I noticed that the default `npm test` script runs `eslint src ...` but initial file structure doesn't have a `src` directory so it won't lint anything. So shouldn't we either lint the root directory or just have the code generated in a `src` directory?

**Comment by lukeed** [comment]
Hi @nelsyeung, if you specify the `--full` flag during `preact create`, it will move all the source code into a `src` directory, as you've specified. 

That said, the `eslint src` you mentioned _is_ a mismatch & we should fix that. 👍

**Comment by developit** [comment]
ooh, good catch.

**Comment by developit** [comment]
FWIW it might be worth changing the default behavior of `create` to be `--type full`.  People seem to be getting tripped up by the lack of a `src/` directory, which is understandable. Personally I love that without configuration files I can just keep everything in the repo root, but it's not everyone's cup of tea.

**Comment by developit** [comment]
Fixed in 1.1.0 :)

**Comment by nelsyeung** [comment]
Thanks! May I ask whether we now need to fix the `npm test` script for  `create --type root`?

**Comment by developit** [comment]
It's also fixed in 1.1.0. For projects already-created, change `src` to `.`.
