### ISSUE TITLE
preact-cli with a backend (allow proxy requests)

### ISSUE THREAD

**Issue by joelgriffith** [developit/preact-cli#84]
As a developer of both a UI and API, it'd be nice if preact-cli allowed certain API calls to be handled by a disparate API (running on a potentially different host/port). There's documentation online with `create-react-app` about specifying a `proxy` in package.json (see [here](https://www.fullstackreact.com/articles/using-create-react-app-with-a-server/)).

I'm not sure if this is something that you have to "bake" into the CLI, but it doesn't appear to work out of the box when I've tested it.

[Webpack Proxy](http://webpack.github.io/docs/webpack-dev-server.html#proxy)

**Comment by lukeed** [comment]
Hi, this is a great idea! It's certainly doable once #56 is in, and also falls in line with #70. These are making it in shortly -- the next release, I believe.

Unless you feel that this is substantially different, I'm going to close this as a duplicate.

**Comment by joelgriffith** [comment]
Nice! Yeah, I'm all in favor of closing for #56. I just ask for docs on it once it's in :)

**Comment by lukeed** [comment]
Thanks 😄
