### ISSUE TITLE
Use source instead of src for consistency

### ISSUE THREAD

**Issue by ugin** [developit/preact-cli#89]
I would really appreciate if you'd think about this and don't treat it as a personal preference. 

`src`, `usr` or other abbreviations like this don't provide too much benefits, but as a drawback I've seen beginners try to abbreviate folder names because they've seen it in many other OS projects and you get folders like `cmps` for `components`, `sers` for `services`, etc.

**Comment by developit** [comment]
Hmm. Not sure this would fly since almost every project has a `src` directory.  For what it's worth, `preact-cli` actually doesn't care about the name of that directory, and works without it too (via `preact create --type root`).

**Comment by ugin** [comment]
I appreciate you took it into consideration, thanks
