### ISSUE TITLE
Unable to provide html template in 1.1.0

### ISSUE THREAD

**Issue by kpdecker** [developit/preact-cli#91]
e189bab7f4e44dacba60bbef4934ef4313cb8362 appears to have moved the CLI to use strict mode, meaning passing `--template filename` no longer works to populate the `config.template` field for `HtmlPlugin`

https://github.com/developit/preact-cli/blob/master/src/lib/webpack-config.js#L442

Not sure if this was a hack or not, but a custom html template seems like it will be a common issue for any larger-scale app.

**Comment by developit** [comment]
Ack! Good catch. A PR that adds that option to [build](https://github.com/developit/preact-cli/blob/master/src/commands/build.js#L38) and [watch](https://github.com/developit/preact-cli/blob/master/src/commands/watch.js#L33) would be awesome if you have some cycles!

**Comment by rkostrzewski** [comment]
Fixed in 1.1.2 via #98
