### ISSUE TITLE
Allow for source map mode selection

### ISSUE THREAD

**Issue by kpdecker** [developit/preact-cli#93]
Running into issues within my workflow with cheap-module-source-map and would be awesome to be able to configure this through some mechanism. (bonus: anything in the webpack config)

**Comment by thangngoc89** [comment]
There is a PR for it already. Stay tuned. https://github.com/developit/preact-cli/pull/56

**Comment by rkostrzewski** [comment]
In `1.3.0` you can do:

```
export default (config, env, helpers) => {
  config.devtool = 'your-own'
}
```
