### ISSUE TITLE
--server config with --dest option does not work as expected

### ISSUE THREAD

**Issue by mrdbarker** [developit/preact-cli#97]
I've started using `preact-cli` and have come across a couple of issues when trying to out the server config into a firebase.json file. The issues are:

1. When calling the serve command, `options.dest` is not being passed to the config server method - [as can be seen here](https://github.com/developit/preact-cli/blob/b57dac4c11bb0b6eb8eb835814b71eb79c31a269/src/commands/serve.js#L76).
2. In the check to see if the dest option is a directory, `options.dest` is not being passed to the `fs.stat` function - [here](https://github.com/developit/preact-cli/blob/b57dac4c11bb0b6eb8eb835814b71eb79c31a269/src/commands/serve.js#L195).
3. `dir` is not being set correctly if you have been able to get into [this block](https://github.com/developit/preact-cli/blob/b57dac4c11bb0b6eb8eb835814b71eb79c31a269/src/commands/serve.js#L202)
4. If the above is fixed an exception is thrown.

On top of this - in addition to allowing '-' to be pased into the `--dest` option, would it be useful to also allow '.' to signify the cwd and a filename of firebase.json?

Finally, would it be desirable to use `fs-extra` and write a key of `hosting` with the config object rather than writing a file that contains that object? Currently my config that was generated by Firebase's CLI tools would be overridden and when I deploy my config would be incorrect. This would make it much easier to work with Firebase's CLI tools and preact-cli at the same time.

Happy to PR this but wanted to get thoughts before I went ahead with the changes.

**Comment by developit** [comment]
Hmm - `dest` is only used by the `preact serve --server config` - it just defines the output location for `firebase.json`, specifically for that mode.  There isn't currently a configuration option for specifying an alternative directory to serve files from.

As for ouputting to stdout, that's already the behavior when omitting `--dest` with `--server config`:

```sh
preact serve --server config
```

To your last point, I'd actually like to have this parse and merge any existing `firebase.json`, `superstatic.json` or `static-app.json` it finds.

**Comment by mrdbarker** [comment]
Sorry I might not have been clear in my original post, I hadn't been expecting it to specify a different directory to serve files from.

The issue that I'm seeing is that this `--dest` option is not correctly being passed to the `SERVERS.config` function, and is then not being handled correctly in the body of that function. I hadn't noticed the `process.cwd()` default, so my comment on adding a '.' option is redundant.

I will submit a PR later today to fix the issues mentioned above that I'm seeing. With regards to the merging of the json files, I'll submit a separate issue later to pick this up.

Cheers
