### ISSUE TITLE
[Feature] Clone from Remote Boilerplate/Template

### ISSUE THREAD

**Issue by lukeed** [developit/preact-cli#99]
We've tossed this idea around a few times -- this is just to officially track it.

If we are to follow in Vue's wonderful footsteps, this would look something like:

```bash
# preact init <template-name> <project-path>
$ preact init lukeed/custom my-app
```

I imagine that `init` vs `create` is a nice distinction to have, but at the same time, could make it a bit confusing that `create` is for the included boilerplate only.

Although... the next logical step/argument is to extract the included templates (4 atm) to remote locations as well.

I have a similar functionality at play in another project, so I'd be thrilled to start this! Of course, any help and/or considerations are welcomed along the way.

**Comment by developit** [comment]
I'm 100% for moving the default templates into a Github org. We'd just see that there is no `/` in the name and know to go to `preact-cli-templates/${name}`.

**Comment by lukeed** [comment]
Correctomundo

**Comment by knight-bubble** [comment]
@lukeed @developit is the work already started on this?

**Comment by lukeed** [comment]
@knight-bubble Yup! I have the core logic in another module right now. Just waiting as we gather other features that constitute a 2.0 before I port it over.

**Comment by thangngoc89** [comment]
I think that we should put everything in a single repo instead, putting it in a github org with many repos won't get many reviewers

**Comment by lukeed** [comment]
@thangngoc89 Not sure what you mean? My remote-templates feature will be part of `preact-cli` internals. 

What I'm saying is, that I have the same logic _already_ inside another module of mine. So, when we're getting closer to a `preact-cli@2.0`, I will extract the logic _from_ my module & add it to `preact-cli`

**Comment by thangngoc89** [comment]
@lukeed I was replied to @developit about this 

> I'm 100% for moving the default templates into a Github org

In my mind, I think he's talking about each template will be in an individual git repo, which is going to be madness (updated multiple projects at once, get reviewer,...)

**Comment by lukeed** [comment]
Oh, I missed that / forgot that was said. 😆

**Comment by developit** [comment]
^ subfolder is an interesting idea, and that would serve the default templates well:

`preact create some-default-template foo`

>  Creates an app "foo" by cloning `github.com/preactjs/cli-templates/some-default-template`

`preact create user/custom-template bar`

>  Creates an app "bar" by cloning `github.com/user/custom-template`

Make sense?

**Comment by developit** [comment]
Only issue I can see (just realized this) is that it's possible we'd actually want the default templates to be version-locked to preact-cli, because they are kinda based on whatever version of the CLI you have running.  For example - in a month, whatever the current default template is might not work with `preact-cli@1.0.0`.

Thoughts?
